### ISSUE TITLE
[RFF] cxx plugin 0.9.7

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1024]
Hey everyone,

We would like to release version 0.9.7 of the cxx plugin.

**Enhancments and bugfixes are documented here:**
https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/cxx-0.9.7-rc1

**Download:**
https://github.com/SonarOpenCommunity/sonar-cxx/releases/download/cxx-0.9.7-rc1/sonar-cxx-plugin-0.9.7-SNAPSHOT.jar

**Issue tracker:**
https://github.com/SonarOpenCommunity/sonar-cxx/issues

As usual, we will eagerly wait for your testing and feedback of this version. The feedback period will end 5th January 2017, in order to let you time to test it!

Happy New Year

**Comment by guwirth** [comment]
From my point of view we are ready to release.

**Comment by jmecosta** [comment]
OK for me also

**Comment by scmbuildguy** [comment]
Hi,

Sorry a little late in testing this. I have been using an earlier 0.9.7-SNAPSHOT version and it was working well, however, when I use the RC1 jar with SonarQube 6.2, I get the following error on startup:

java.lang.IllegalStateException: One of HTML description or Markdown description
 must be defined for rule [repository=rats, key=HardcodedAccount]
        at org.sonar.api.server.rule.RulesDefinition$NewRule.validate(RulesDefin
ition.java:903)
        at org.sonar.api.server.rule.RulesDefinition$NewRule.access$800(RulesDef
inition.java:661)
        at org.sonar.api.server.rule.RulesDefinition$RepositoryImpl.<init>(Rules
Definition.java:568)
        at org.sonar.api.server.rule.RulesDefinition$RepositoryImpl.<init>(Rules
Definition.java:542)
        at org.sonar.api.server.rule.RulesDefinition$Context.registerRepository(
RulesDefinition.java:438)
        at org.sonar.api.server.rule.RulesDefinition$Context.access$500(RulesDef
inition.java:382)
        at org.sonar.api.server.rule.RulesDefinition$NewRepositoryImpl.done(Rule
sDefinition.java:514)
        at org.sonar.plugins.cxx.utils.CxxAbstractRuleRepository.define(CxxAbstr
actRuleRepository.java:98)
        at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoade
r.java:52)
        at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:99)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(
ReflectionLifecycleStrategy.java:110)
        at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89)
        at org.sonar.core.platform.ComponentContainer$1.start(ComponentContainer.java:320)
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
        at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
        at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
        at org.picocontainer.behaviors.Stored.start(Stored.java:110)
        at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
        at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
        at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:141)
        at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:88)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:40)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:70)
        at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:46)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:67)
        at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:201)
        at org.sonar.server.platform.Platform.doStart(Platform.java:114)
        at org.sonar.server.platform.Platform.doStart(Platform.java:99)
        at org.sonar.server.platform.web.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:45)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Any thoughts on what could be happening?

--Mark

**Comment by guwirth** [comment]
@scmbuildguy there seems to be an invalid rule definition in repository **rats** with key **HardcodedAccount**? Looking to our plugin there is no such rule definition?
Our integration tests are also working with SQ 6.2 on Linux. Is there something special in your configuration? Do you define own rules under **other**?

**Comment by scmbuildguy** [comment]
Nope, I do not define my own rules. I can see the key for the rule is 'cxx:HardcodedAccount' and it is not associated with any quality profiles. Interesting the stacktrace has it in 'rats' repository...

My 0.9.7-SNAPSHOT.jar that is working is from commit fe897b6ca0eb0c5668a80d21260e7e77a8a3cb97 ( September 8th, 2016), so it seems there is something in-between which is causing my issue.

If no one else is seeing this, then I will continue looking on my own.

Best Regards,
--Mark

**Comment by guwirth** [comment]
@scmbuildguy maybe your database is corrupt? Can you try with a new installation of SQ 6.2 please. Do you also see the the problem then?

**Comment by scmbuildguy** [comment]
I will work on with installing with a default sonarqube 6.2 + RC1.jar

In the meantime I see the HardcodedAccount rule comes from sonar-cxx/cxx-checks/src/main/java/org/sonar/cxx/checks/HardcodedAccountCheck.java. It seems as though the repositoryKey should be 'cxx' as what I see in the SNAPSHOT.jar, however, RC1 seems to expect the repositoryKey to be 'rats'

**Comment by guwirth** [comment]
@scmbuildguy you are right there is a check with the key `HardcodedAccount` but not in the repository `rats`. So my feeling is your database is corrupt?

**Comment by guwirth** [comment]
@scmbuildguy any news with a clean installation?

**Comment by scmbuildguy** [comment]
sorry for the delay. I get the same issue when starting from a clean installation and using the embedded H2 default database. The only plugin I added after the installation was the sonar-cxx 0.9.7 RC1 jar

**Comment by guwirth** [comment]
@scmbuildguy did also a test with SQ6.2 and latest snapshot - have no problems.

Below my settings (JSON), please compare with your settings:

```JSON
{
  "System": {
    "System Date": "2017-01-23T11:20:26+0100",
    "Start Time": "2017-01-23T11:11:37+0100",
    "JVM Vendor": "Oracle Corporation",
    "JVM Name": "Java HotSpot(TM) 64-Bit Server VM",
    "JVM Version": "25.71-b15",
    "Processors": 8,
    "System Classpath": "./lib/common/commons-cli-1.3.1.jar;./lib/common/commons-codec-1.8.jar;./lib/common/commons-io-2.4.jar;./lib/common/commons-lang-2.6.jar;./lib/common/compress-lzf-1.0.2.jar;./lib/common/elasticsearch-2.3.5.jar;./lib/common/guava-18.0.jar;./lib/common/HdrHistogram-2.1.6.jar;./lib/common/hppc-0.7.1.jar;./lib/common/jackson-core-2.6.6.jar;./lib/common/jackson-dataformat-cbor-2.6.6.jar;./lib/common/jackson-dataformat-smile-2.6.6.jar;./lib/common/jackson-dataformat-yaml-2.6.6.jar;./lib/common/jna-4.1.0.jar;./lib/common/jna-platform-4.1.0.jar;./lib/common/joda-convert-1.2.jar;./lib/common/joda-time-2.9.4.jar;./lib/common/jsr166e-1.1.0.jar;./lib/common/logback-classic-1.1.7.jar;./lib/common/logback-core-1.1.7.jar;./lib/common/lucene-analyzers-common-5.5.0.jar;./lib/common/lucene-backward-codecs-5.5.0.jar;./lib/common/lucene-core-5.5.0.jar;./lib/common/lucene-grouping-5.5.0.jar;./lib/common/lucene-highlighter-5.5.0.jar;./lib/common/lucene-join-5.5.0.jar;./lib/common/lucene-memory-5.5.0.jar;./lib/common/lucene-misc-5.5.0.jar;./lib/common/lucene-queries-5.5.0.jar;./lib/common/lucene-queryparser-5.5.0.jar;./lib/common/lucene-sandbox-5.5.0.jar;./lib/common/lucene-spatial-5.5.0.jar;./lib/common/lucene-spatial3d-5.5.0.jar;./lib/common/lucene-suggest-5.5.0.jar;./lib/common/netty-3.10.5.Final.jar;./lib/common/securesm-1.0.jar;./lib/common/slf4j-api-1.7.21.jar;./lib/common/snakeyaml-1.15.jar;./lib/common/sonar-process-6.2.jar;./lib/common/sonar-process-monitor-6.2.jar;./lib/common/spatial4j-0.5.jar;./lib/common/t-digest-3.0.jar;./lib/server/activation-1.1.1.jar;./lib/server/commons-beanutils-1.8.3.jar;./lib/server/commons-csv-1.0.jar;./lib/server/commons-dbcp-1.4.jar;./lib/server/commons-dbutils-1.5.jar;./lib/server/commons-email-1.3.2.jar;./lib/server/commons-pool-1.5.4.jar;./lib/server/gson-2.3.1.jar;./lib/server/jackson-annotations-2.6.6.jar;./lib/server/jackson-databind-2.6.6.jar;./lib/server/jcl-over-slf4j-1.7.21.jar;./lib/server/jjwt-0.6.0.jar;./lib/server/jna-4.1.0.jar;./lib/server/jruby-complete-1.7.9.jar;./lib/server/jruby-rack-1.1.13.2.jar;./lib/server/jul-to-slf4j-1.7.21.jar;./lib/server/log4j-over-slf4j-1.7.21.jar;./lib/server/logback-access-1.1.7.jar;./lib/server/lz4-1.3.0.jar;./lib/server/mail-1.4.5.jar;./lib/server/mybatis-3.2.7.jar;./lib/server/okhttp-3.3.1.jar;./lib/server/okio-1.8.0.jar;./lib/server/picocontainer-2.15.jar;./lib/server/protobuf-java-3.0.0-beta-2.jar;./lib/server/sonar-classloader-1.0.jar;./lib/server/sonar-core-6.2.jar;./lib/server/sonar-db-6.2.jar;./lib/server/sonar-markdown-6.2.jar;./lib/server/sonar-plugin-api-6.2.jar;./lib/server/sonar-plugin-bridge-6.2.jar;./lib/server/sonar-scanner-protocol-6.2.jar;./lib/server/sonar-server-6.2.jar;./lib/server/sonar-update-center-common-1.17.jar;./lib/server/sonar-ws-6.2.jar;./lib/server/stax2-api-3.1.4.jar;./lib/server/staxmate-2.0.1.jar;./lib/server/tomcat-embed-core-8.0.32.jar;./lib/server/tomcat-embed-el-8.0.32.jar;./lib/server/tomcat-embed-jasper-8.0.32.jar;./lib/server/tomcat-embed-logging-juli-8.0.32.jar;./lib/server/woodstox-core-lgpl-4.4.0.jar;C:\\temp\\sonarqube-6.2\\lib\\jdbc\\h2\\h2-1.3.176.jar;C:\\Program Files\\Java\\jre8\\lib\\management-agent.jar",
    "BootClassPath": "C:\\Program Files\\Java\\jre8\\lib\\resources.jar;C:\\Program Files\\Java\\jre8\\lib\\rt.jar;C:\\Program Files\\Java\\jre8\\lib\\sunrsasign.jar;C:\\Program Files\\Java\\jre8\\lib\\jsse.jar;C:\\Program Files\\Java\\jre8\\lib\\jce.jar;C:\\Program Files\\Java\\jre8\\lib\\charsets.jar;C:\\Program Files\\Java\\jre8\\lib\\jfr.jar;C:\\Program Files\\Java\\jre8\\classes",
    "Library Path": "C:\\Program Files\\Java\\jre8\\bin;C:\\WINDOWS\\Sun\\Java\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\ProgramData\\Oracle\\Java\\javapath;.",
    "Total Memory": "279 MB",
    "Free Memory": "178 MB",
    "Max Memory": "477 MB",
    "Heap": "init = 134217728(131072K) used = 101422640(99045K) committed = 279969792(273408K) max = 477626368(466432K)",
    "Non Heap": "init = 2555904(2496K) used = 139777512(136501K) committed = 144203776(140824K) max = -1(-1K)",
    "System Load Average": "-100,0% (last minute)",
    "Loaded Classes": 17135,
    "Total Loaded Classes": 17135,
    "Unloaded Classes": 0,
    "Threads": 54,
    "Threads Peak": 55,
    "Daemon Thread": 43
  },
  "Settings": {
    "jruby.compat.version": "1.8",
    "jruby.max.runtimes": "1",
    "jruby.min.runtimes": "1",
    "jruby.rack.logging": "slf4j",
    "process.index": "2",
    "process.key": "web",
    "process.sharedDir": "C:\\temp\\sonarqube-6.2\\temp",
    "process.terminationTimeout": "60000",
    "rails.env": "production",
    "sonar.ce.javaAdditionalOpts": "",
    "sonar.ce.javaOpts": "-Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError",
    "sonar.core.id": "AVnKx5uMWJt3_sCd65eo",
    "sonar.core.startTime": "2017-01-23T11:11:46+0100",
    "sonar.embeddedDatabase.port": "9092",
    "sonar.jdbc.driverPath": "C:\\temp\\sonarqube-6.2\\lib\\jdbc\\h2\\h2-1.3.176.jar",
    "sonar.jdbc.maxActive": "60",
    "sonar.jdbc.maxIdle": "5",
    "sonar.jdbc.maxWait": "5000",
    "sonar.jdbc.minEvictableIdleTimeMillis": "600000",
    "sonar.jdbc.minIdle": "2",
    "sonar.jdbc.timeBetweenEvictionRunsMillis": "30000",
    "sonar.jdbc.url": "jdbc:h2:tcp://localhost:9092/sonar",
    "sonar.path.data": "C:\\temp\\sonarqube-6.2\\data",
    "sonar.path.home": "C:\\temp\\sonarqube-6.2",
    "sonar.path.logs": "C:\\temp\\sonarqube-6.2\\logs",
    "sonar.path.temp": "C:\\temp\\sonarqube-6.2\\temp",
    "sonar.path.web": "C:\\temp\\sonarqube-6.2\\web",
    "sonar.permission.template.default": "default_template",
    "sonar.qualitygate": "1",
    "sonar.search.clusterName": "sonarqube",
    "sonar.search.host": "127.0.0.1",
    "sonar.search.javaAdditionalOpts": "",
    "sonar.search.javaOpts": "-Xmx1G -Xms256m -Xss256k -Djna.nosys=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError",
    "sonar.search.port": "9001",
    "sonar.web.javaAdditionalOpts": "",
    "sonar.web.javaOpts": "-Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError",
    "sonar.wrapped": "true"
  },
  "SonarQube": {
    "Version": "6.2",
    "Automatic User Creation": true,
    "Allow Users to Sign Up": false,
    "Force authentication": false,
    "Official Distribution": true,
    "Home Dir": "C:\\temp\\sonarqube-6.2",
    "Data Dir": "C:\\temp\\sonarqube-6.2\\data",
    "Temp Dir": "C:\\temp\\sonarqube-6.2\\temp",
    "Logs Dir": "C:\\temp\\sonarqube-6.2\\logs",
    "Logs Level": "INFO"
  },
  "Elasticsearch": {
    "State": "GREEN",
    "Indices": {
      "tests": {
        "Docs": 0,
        "Shards": 5,
        "Store Size": "795 bytes"
      },
      "projectmeasures": {
        "Docs": 0,
        "Shards": 5,
        "Store Size": "795 bytes"
      },
      "rules": {
        "Docs": 5018,
        "Shards": 1,
        "Store Size": "1 MB"
      },
      "issues": {
        "Docs": 0,
        "Shards": 5,
        "Store Size": "795 bytes"
      },
      "users": {
        "Docs": 1,
        "Shards": 1,
        "Store Size": "6 KB"
      },
      "views": {
        "Docs": 0,
        "Shards": 5,
        "Store Size": "795 bytes"
      }
    },
    "Number of Nodes": 1,
    "Nodes": {
      "sonarqube": {
        "Address": "127.0.0.1:9001",
        "Type": "Master",
        "Disk Available": "52 GB",
        "Store Size": "1 MB",
        "Open Files": -1,
        "JVM Heap Usage": "9,0%",
        "JVM Heap Used": "96 MB",
        "JVM Heap Max": "989 MB",
        "JVM Non Heap Used": "58 MB",
        "JVM Threads": 76,
        "Field Data Memory": "0 bytes",
        "Field Data Circuit Breaker Limit": "593 MB",
        "Field Data Circuit Breaker Estimation": "0 bytes",
        "Request Circuit Breaker Limit": "395 MB",
        "Request Circuit Breaker Estimation": "0 bytes",
        "Query Cache Memory": "0 bytes",
        "Request Cache Memory": "0 bytes"
      }
    }
  },
  "Plugins": {
    "csharp": {
      "Name": "C#",
      "Version": "5.5.1.522"
    },
    "cxx": {
      "Name": "C++ (Community)",
      "Version": "0.9.7-SNAPSHOT"
    },
    "java": {
      "Name": "Java",
      "Version": "4.3.0.7717"
    },
    "scmgit": {
      "Name": "Git",
      "Version": "1.2"
    },
    "scmsvn": {
      "Name": "SVN",
      "Version": "1.3"
    },
    "javascript": {
      "Name": "JavaScript",
      "Version": "2.18.0.3454"
    }
  },
  "JvmProperties": {
    "awt.toolkit": "sun.awt.windows.WToolkit",
    "catalina.base": "C:\\temp\\sonarqube-6.2\\temp\\tc",
    "catalina.home": "C:\\temp\\sonarqube-6.2\\temp\\tc",
    "catalina.useNaming": "false",
    "file.encoding": "UTF-8",
    "file.encoding.pkg": "sun.io",
    "file.separator": "\\",
    "http.agent": "SonarQube 6.2 # AVnKx5uMWJt3_sCd65eo",
    "java.awt.graphicsenv": "sun.awt.Win32GraphicsEnvironment",
    "java.awt.headless": "true",
    "java.awt.printerjob": "sun.awt.windows.WPrinterJob",
    "java.class.path": "./lib/common/commons-cli-1.3.1.jar;./lib/common/commons-codec-1.8.jar;./lib/common/commons-io-2.4.jar;./lib/common/commons-lang-2.6.jar;./lib/common/compress-lzf-1.0.2.jar;./lib/common/elasticsearch-2.3.5.jar;./lib/common/guava-18.0.jar;./lib/common/HdrHistogram-2.1.6.jar;./lib/common/hppc-0.7.1.jar;./lib/common/jackson-core-2.6.6.jar;./lib/common/jackson-dataformat-cbor-2.6.6.jar;./lib/common/jackson-dataformat-smile-2.6.6.jar;./lib/common/jackson-dataformat-yaml-2.6.6.jar;./lib/common/jna-4.1.0.jar;./lib/common/jna-platform-4.1.0.jar;./lib/common/joda-convert-1.2.jar;./lib/common/joda-time-2.9.4.jar;./lib/common/jsr166e-1.1.0.jar;./lib/common/logback-classic-1.1.7.jar;./lib/common/logback-core-1.1.7.jar;./lib/common/lucene-analyzers-common-5.5.0.jar;./lib/common/lucene-backward-codecs-5.5.0.jar;./lib/common/lucene-core-5.5.0.jar;./lib/common/lucene-grouping-5.5.0.jar;./lib/common/lucene-highlighter-5.5.0.jar;./lib/common/lucene-join-5.5.0.jar;./lib/common/lucene-memory-5.5.0.jar;./lib/common/lucene-misc-5.5.0.jar;./lib/common/lucene-queries-5.5.0.jar;./lib/common/lucene-queryparser-5.5.0.jar;./lib/common/lucene-sandbox-5.5.0.jar;./lib/common/lucene-spatial-5.5.0.jar;./lib/common/lucene-spatial3d-5.5.0.jar;./lib/common/lucene-suggest-5.5.0.jar;./lib/common/netty-3.10.5.Final.jar;./lib/common/securesm-1.0.jar;./lib/common/slf4j-api-1.7.21.jar;./lib/common/snakeyaml-1.15.jar;./lib/common/sonar-process-6.2.jar;./lib/common/sonar-process-monitor-6.2.jar;./lib/common/spatial4j-0.5.jar;./lib/common/t-digest-3.0.jar;./lib/server/activation-1.1.1.jar;./lib/server/commons-beanutils-1.8.3.jar;./lib/server/commons-csv-1.0.jar;./lib/server/commons-dbcp-1.4.jar;./lib/server/commons-dbutils-1.5.jar;./lib/server/commons-email-1.3.2.jar;./lib/server/commons-pool-1.5.4.jar;./lib/server/gson-2.3.1.jar;./lib/server/jackson-annotations-2.6.6.jar;./lib/server/jackson-databind-2.6.6.jar;./lib/server/jcl-over-slf4j-1.7.21.jar;./lib/server/jjwt-0.6.0.jar;./lib/server/jna-4.1.0.jar;./lib/server/jruby-complete-1.7.9.jar;./lib/server/jruby-rack-1.1.13.2.jar;./lib/server/jul-to-slf4j-1.7.21.jar;./lib/server/log4j-over-slf4j-1.7.21.jar;./lib/server/logback-access-1.1.7.jar;./lib/server/lz4-1.3.0.jar;./lib/server/mail-1.4.5.jar;./lib/server/mybatis-3.2.7.jar;./lib/server/okhttp-3.3.1.jar;./lib/server/okio-1.8.0.jar;./lib/server/picocontainer-2.15.jar;./lib/server/protobuf-java-3.0.0-beta-2.jar;./lib/server/sonar-classloader-1.0.jar;./lib/server/sonar-core-6.2.jar;./lib/server/sonar-db-6.2.jar;./lib/server/sonar-markdown-6.2.jar;./lib/server/sonar-plugin-api-6.2.jar;./lib/server/sonar-plugin-bridge-6.2.jar;./lib/server/sonar-scanner-protocol-6.2.jar;./lib/server/sonar-server-6.2.jar;./lib/server/sonar-update-center-common-1.17.jar;./lib/server/sonar-ws-6.2.jar;./lib/server/stax2-api-3.1.4.jar;./lib/server/staxmate-2.0.1.jar;./lib/server/tomcat-embed-core-8.0.32.jar;./lib/server/tomcat-embed-el-8.0.32.jar;./lib/server/tomcat-embed-jasper-8.0.32.jar;./lib/server/tomcat-embed-logging-juli-8.0.32.jar;./lib/server/woodstox-core-lgpl-4.4.0.jar;C:\\temp\\sonarqube-6.2\\lib\\jdbc\\h2\\h2-1.3.176.jar;C:\\Program Files\\Java\\jre8\\lib\\management-agent.jar",
    "java.class.version": "52.0",
    "java.endorsed.dirs": "C:\\Program Files\\Java\\jre8\\lib\\endorsed",
    "java.ext.dirs": "C:\\Program Files\\Java\\jre8\\lib\\ext;C:\\WINDOWS\\Sun\\Java\\lib\\ext",
    "java.home": "C:\\Program Files\\Java\\jre8",
    "java.io.tmpdir": "C:\\temp\\sonarqube-6.2\\temp",
    "java.library.path": "C:\\Program Files\\Java\\jre8\\bin;C:\\WINDOWS\\Sun\\Java\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\ProgramData\\Oracle\\Java\\javapath;.",
    "java.net.preferIPv4Stack": "true",
    "java.rmi.server.randomIDs": "true",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_71-b15",
    "java.specification.name": "Java Platform API Specification",
    "java.specification.vendor": "Oracle Corporation",
    "java.specification.version": "1.8",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.vendor.url.bug": "http://bugreport.sun.com/bugreport/",
    "java.version": "1.8.0_71",
    "java.vm.info": "mixed mode",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.specification.name": "Java Virtual Machine Specification",
    "java.vm.specification.vendor": "Oracle Corporation",
    "java.vm.specification.version": "1.8",
    "java.vm.vendor": "Oracle Corporation",
    "java.vm.version": "25.71-b15",
    "jruby.compile.invokedynamic": "false",
    "jruby.management.enabled": "false",
    "line.separator": "\r\n",
    "org.apache.catalina.startup.EXIT_ON_INIT_FAILURE": "true",
    "org.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH": "true",
    "os.arch": "amd64",
    "os.name": "Windows 7",
    "os.version": "6.1",
    "path.separator": ";",
    "sun.arch.data.model": "64",
    "sun.boot.class.path": "C:\\Program Files\\Java\\jre8\\lib\\resources.jar;C:\\Program Files\\Java\\jre8\\lib\\rt.jar;C:\\Program Files\\Java\\jre8\\lib\\sunrsasign.jar;C:\\Program Files\\Java\\jre8\\lib\\jsse.jar;C:\\Program Files\\Java\\jre8\\lib\\jce.jar;C:\\Program Files\\Java\\jre8\\lib\\charsets.jar;C:\\Program Files\\Java\\jre8\\lib\\jfr.jar;C:\\Program Files\\Java\\jre8\\classes",
    "sun.boot.library.path": "C:\\Program Files\\Java\\jre8\\bin",
    "sun.cpu.endian": "little",
    "sun.cpu.isalist": "amd64",
    "sun.desktop": "windows",
    "sun.io.unicode.encoding": "UnicodeLittle",
    "sun.java.command": "org.sonar.server.app.WebServer C:\\temp\\sonarqube-6.2\\temp\\sq-process1784022082233645418properties",
    "sun.java.launcher": "SUN_STANDARD",
    "sun.jnu.encoding": "Cp1252",
    "sun.management.compiler": "HotSpot 64-Bit Tiered Compilers",
    "sun.nio.ch.bugLevel": "",
    "sun.os.patch.level": "Service Pack 1",
    "user.country": "US",
    "user.country.format": "DE",
    "user.dir": "C:\\temp\\sonarqube-6.2",
    "user.home": "C:\\Users\\xxx",
    "user.language": "en",
    "user.language.format": "de",
    "user.name": "xxx",
    "user.script": "",
    "user.timezone": "Europe/Berlin",
    "user.variant": ""
  },
  "Database": {
    "Database": "H2",
    "Database Version": "1.3.176 (2014-04-05)",
    "Username": "",
    "URL": "jdbc:h2:tcp://localhost:9092/sonar",
    "Driver": "H2 JDBC Driver",
    "Driver Version": "1.3.176 (2014-04-05)",
    "Version Status": "UP_TO_DATE",
    "Pool Active Connections": 1,
    "Pool Max Connections": 60,
    "Pool Initial Size": 0,
    "Pool Idle Connections": 4,
    "Pool Min Idle Connections": 2,
    "Pool Max Idle Connections": 5,
    "Pool Max Wait (ms)": 5000,
    "Pool Remove Abandoned": false,
    "Pool Remove Abandoned Timeout (seconds)": 300
  },
  "Compute Engine Database Connection": {
    "Pool Initial Size": 0,
    "Pool Active Connections": 0,
    "Pool Idle Connections": 2,
    "Pool Max Active Connections": 60,
    "Pool Max Idle Connections": 5,
    "Pool Min Idle Connections": 2,
    "Pool Max Wait (ms)": 5000,
    "Pool Remove Abandoned": false,
    "Pool Remove Abandoned Timeout (sec)": 300
  },
  "Compute Engine State": {
    "Heap Committed (MB)": 238,
    "Heap Init (MB)": 128,
    "Heap Max (MB)": 455,
    "Heap Used (MB)": 47,
    "Non Heap Committed (MB)": 46,
    "Non Heap Init (MB)": 2,
    "Non Heap Used (MB)": 45,
    "Thread Count": 33
  },
  "Compute Engine Tasks": {
    "Pending": 0,
    "In Progress": 0,
    "Processed With Error": 0,
    "Processed With Success": 0,
    "Processing Time (ms)": 0,
    "Worker Count": 1
  }
}
```

**Comment by FloOows** [comment]
Hi, I have a similar issue using 0.9.7 SNAPSHOT. I upgraded SonarQube to 6.2, then C++ Community plugin to 0.9.7-SNAPSHOT and the error started from this point.

Extract of my stack :
```
 Caused by: org.sonar.squidbridge.api.AnalysisException: Unable to analyze file: MyFile 
 Caused by: java.lang.IllegalStateException: Cannot register highlighting rule for characters at
            Range[from [line=641, lineOffset=72] to [line=641, lineOffset=99]] as it overlaps at least one existing rule
```

Full Stack [there](http://stackoverflow.com/q/41766477/2394026)

**Comment by scmbuildguy** [comment]
@guwirth Not seeing anything glaring between settings...

I am using JDK 8 Update 65 and running on CentOS 6. If you had a clean start, I would go with that.

**Comment by guwirth** [comment]
@all like to do some final tests wit latest snapshot: https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts

Hope we can release it at long last. 😄

**Comment by scmbuildguy** [comment]
+1 - I am not sure what was happening on the original RC1, but my SonarQube 6.2 instance comes up without issue and scan is executed successfully.

**Comment by guwirth** [comment]
@jmecosta everything done and working. You can upload binaries and release it.

**Comment by jmecosta** [comment]
done

**Comment by guwirth** [comment]
@jmecosta thx!
