### ISSUE TITLE
Exception with Visual Studio Code Coverage

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1048]
We have recently upgraded our Sonar installation to version 5.6.5.
We also upgraded sonar-scanner to version 2.8.

Everything is fine but the code coverage metrics. The root cause is an exception during the parsing of the coverage report:

```
16:55:39.039 ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
        at org.sonar.plugins.cxx.coverage.CoverageMeasures.setConditions(CoverageMeasures.java:57)
        at org.sonar.plugins.cxx.coverage.VisualStudioParser.collectRangeMeasures(VisualStudioParser.java:121)
        at org.sonar.plugins.cxx.coverage.VisualStudioParser.collectFunctionMeasures(VisualStudioParser.java:98)
        at org.sonar.plugins.cxx.coverage.VisualStudioParser.handleModuleItems(VisualStudioParser.java:75)
        at org.sonar.plugins.cxx.coverage.VisualStudioParser.collectModuleMeasures(VisualStudioParser.java:65)
        at org.sonar.plugins.cxx.coverage.VisualStudioParser.access$000(VisualStudioParser.java:37)
        at org.sonar.plugins.cxx.coverage.VisualStudioParser$1.stream(VisualStudioParser.java:56)
        at org.sonar.plugins.cxx.utils.StaxParser.parse(StaxParser.java:110)
        at org.sonar.plugins.cxx.utils.StaxParser.parse(StaxParser.java:90)
        at org.sonar.plugins.cxx.utils.StaxParser.parse(StaxParser.java:80)
        at org.sonar.plugins.cxx.coverage.VisualStudioParser.processReport(VisualStudioParser.java:59)
        at org.sonar.plugins.cxx.coverage.CxxCoverageSensor.processReports(CxxCoverageSensor.java:179)
        at org.sonar.plugins.cxx.coverage.CxxCoverageSensor.execute(CxxCoverageSensor.java:90)

        ...

        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

**Comment by guwirth** [comment]
Found the issue. There is a typo in https://github.com/SonarOpenCommunity/sonar-cxx/blob/0abe151386820b6d3dfcf2a760880f63637f3902/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/coverage/CoverageMeasures.java#L56

```Java
   if (measuresConditions.containsKey(lineId)) {
      CoverageMeasure existentData = measuresLines.get(lineId);
```
must be:
```Java
   if (measuresConditions.containsKey(lineId)) {
      CoverageMeasure existentData = measuresConditions.get(lineId);
```
