### ISSUE TITLE
Inner public template class leads to NullPointerException

### ISSUE THREAD

**Issue by Nekto89** [SonarOpenCommunity/sonar-cxx#1067]
I've minimized failure to
```
struct A
  {
  template<class T>class B;
  };
```

It works with class and private declaration
```
class A
  {
  template<class T>class B;
  };
```

but fails with public:
```
class A
  {
  public:
    template<class T>class B;
  };
```

org.sonar.squidbridge.api.AnalysisException: Unable to analyze file: ...
        at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:131)
        at org.sonar.plugins.cxx.squid.CxxSquidSensor.execute(CxxSquidSensor.java:141)
        at org.sonar.batch.sensor.SensorWrapper.analyse(SensorWrapper.java:57)
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
        at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:234)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
        at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.NullPointerException
        at org.sonar.cxx.visitors.AbstractCxxPublicApiVisitor.visitTemplateDeclaration(AbstractCxxPublicApiVisitor.java:488)
        at org.sonar.cxx.visitors.AbstractCxxPublicApiVisitor.visitMemberDeclaration(AbstractCxxPublicApiVisitor.java:432)
        at org.sonar.cxx.visitors.AbstractCxxPublicApiVisitor.visitNode(AbstractCxxPublicApiVisitor.java:153)
        at com.sonar.sslr.impl.ast.AstWalker.visitNode(AstWalker.java:114)
        at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:85)
        at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
        at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
        at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
        at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
        at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
        at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
        at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
        at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
        at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
        at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
        at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
        at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
        at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
        at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
        at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
        at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
        at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
        at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
        at com.sonar.sslr.impl.ast.AstWalker.walkAndVisit(AstWalker.java:69)
        at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:110)
... 32 more

**Comment by guwirth** [comment]
Hi @Nekto89, can you try with sslr-toolkit https://github.com/SonarOpenCommunity/sonar-cxx/releases/download/cxx-0.9.7/sslr-cxx-toolkit-0.9.7.jar please. Parsing the code is not crashing if I'm doing it.

```C++
class A
  {
  public:
    template<class T>class B;
  };
```

**Comment by Nekto89** [comment]
It doesn't crash in cxx toolkit, only when I run sonar-scanner (2.8)
sonar-scanner.bat -Dsonar.projectVersion=C00001 -Dsonar.projectKey=Test:Test -Dsonar.projectName=Test:Test -X

sonar-project.properties:
```
sonar.cxx.errorRecoveryEnabled=True
sonar.language=c++
sonar.sourceEncoding=UTF-8
sonar.projectBaseDir=.
sonar.sources=.
```

test.h
```
struct A
  {
  template<class T>class B;
  };

```
Output:
```
19:50:47.042 INFO: Sensor CxxSquidSensor (wrapped)
19:50:47.276 DEBUG: Parse 'D:\Test\test.h' as C++ file
19:50:47.296 DEBUG: finished preprocessing 'D:\Test\test.h'
19:50:47.301 DEBUG: node: className line: 1 id: 'A' documented: false
19:50:47.305 INFO: ------------------------------------------------------------------------
19:50:47.306 INFO: EXECUTION FAILURE
```

**Comment by guwirth** [comment]
Bug in AbstractCxxPublicApiVisitor

**Comment by guwirth** [comment]
@Nekto89 please try with latest snapshot
