### ISSUE TITLE
Plugin does'nt work with SQ 6.2 and 6.3

### ISSUE THREAD

**Issue by neonman63** [SonarOpenCommunity/sonar-cxx#1101]
When SQ starts I get this error:

```
sonar_1  | 2017.04.06 09:43:11 ERROR web[][o.a.c.c.C.[.[.[/sonar]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.web.PlatformServletContextListener
sonar_1  | java.lang.IllegalArgumentException: The rule 'CustomRuleTemplate' of repository 'pclint' is declared several times
sonar_1  | 	at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
sonar_1  | 	at org.sonar.api.server.rule.RulesDefinition$NewRepositoryImpl.createRule(RulesDefinition.java:493)
sonar_1  | 	at org.sonar.api.server.rule.RulesDefinitionXmlLoader.processRule(RulesDefinitionXmlLoader.java:327)
sonar_1  | 	at org.sonar.api.server.rule.RulesDefinitionXmlLoader.load(RulesDefinitionXmlLoader.java:231)
sonar_1  | 	at org.sonar.cxx.sensors.utils.CxxAbstractRuleRepository.define(CxxAbstractRuleRepository.java:84)
sonar_1  | 	at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoader.java:52)
sonar_1  | 	at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:99)
sonar_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sonar_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sonar_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
sonar_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
sonar_1  | 	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110)
sonar_1  | 	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89)
sonar_1  | 	at org.sonar.core.platform.ComponentContainer$1.start(ComponentContainer.java:321)
sonar_1  | 	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
sonar_1  | 	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
sonar_1  | 	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
sonar_1  | 	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
sonar_1  | 	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
sonar_1  | 	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
sonar_1  | 	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
sonar_1  | 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
sonar_1  | 	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:88)
sonar_1  | 	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:40)
sonar_1  | 	at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:70)
sonar_1  | 	at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:45)
sonar_1  | 	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:67)
sonar_1  | 	at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:188)
sonar_1  | 	at org.sonar.server.platform.Platform.doStart(Platform.java:101)
sonar_1  | 	at org.sonar.server.platform.Platform.doStart(Platform.java:79)
sonar_1  | 	at org.sonar.server.platform.web.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:45)
sonar_1  | 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
sonar_1  | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
sonar_1  | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
sonar_1  | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
sonar_1  | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
sonar_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
sonar_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
sonar_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
sonar_1  | 	at java.lang.Thread.run(Thread.java:745)
```

Tried plugin version 0.9.7 and latest 0.9.8-SNAPSHOT from git master

**Comment by neonman63** [comment]
Latest log with plugins version:

`sonar_1  | 2017.04.06 09:43:07 INFO  web[][o.s.s.p.LogServerVersion] SonarQube Server / 6.3.0.19869 / 43ea4f4c43aa89d4c435017f86d0da254e115e6b
sonar_1  | 2017.04.06 09:43:07 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:postgresql://pgsql/sonar
sonar_1  | 2017.04.06 09:43:08 INFO  web[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /opt/sonarqube
sonar_1  | 2017.04.06 09:43:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin C# / 5.8.0.660 / 7f0fb93d3389e487f54c07f31be93e4799ab1508
sonar_1  | 2017.04.06 09:43:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin C++ (Community) / 0.9.8-SNAPSHOT / 3669b01af21ad99422e9de1f0d7a3ad12f703ae0
sonar_1  | 2017.04.06 09:43:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin Git / 1.2 / a713dd64daf8719ba4e7f551f9a1966c62690c17
sonar_1  | 2017.04.06 09:43:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin LDAP / 2.1.0.507 / 60b4a72c2042d0cad5233be63d0456815c9691e2
sonar_1  | 2017.04.06 09:43:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin Python / 1.7.0.1195 / 5c015d7ae2353373d3dc52a465d1cd805ab6535a
sonar_1  | 2017.04.06 09:43:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SVN / 1.4.0.522 / 1309b92a587d1c8fd55a2981c69ceadc1f79e79c
sonar_1  | 2017.04.06 09:43:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarJS / 2.21.0.4409 / 432ceb89f4b9266b30d038ab3159cf451d9cae6c
sonar_1  | 2017.04.06 09:43:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin Web / 2.5.0.476 / 636872f5d37fa7a440fe07d08d504e1a881225e5
`

**Comment by jmecosta** [comment]
Have you tried wiping the es folder in server. So the elastic search engine
data.

If that does not do it, then you have problems I'm your database and you
need to run some db queries to clean those rules

**Comment by neonman63** [comment]
I tried remove es folder, restart and got same error. What table need to be cleaned?

**Comment by jmecosta** [comment]
yes good question, i think you can try your luck in the google forums, usually they might give a hand there. otherwise you need to inspect the db.

**Comment by neonman63** [comment]
Hm, I tried this: 

```
delete FROM rules where plugin_name = 'pclint';
Query returned successfully: 1447 rows affected, 21 msec execution time.
```
And got same error. 
Ok. Let's try to debug plugin and I found the directory with pclint.xml and another rules xml files. I changed all <key>CustomRuleTemplate</key> inside this xmls to difference value. Restart and got new error:

```
sonar_1  | java.lang.IllegalArgumentException: The rule '1' of repository 'pclint' is declared several times
sonar_1  | 	at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
sonar_1  | 	at org.sonar.api.server.rule.RulesDefinition$NewRepositoryImpl.createRule(RulesDefinition.java:493)
sonar_1  | 	at org.sonar.api.server.rule.RulesDefinitionXmlLoader.processRule(RulesDefinitionXmlLoader.java:327)
sonar_1  | 	at org.sonar.api.server.rule.RulesDefinitionXmlLoader.load(RulesDefinitionXmlLoader.java:231)
sonar_1  | 	at org.sonar.cxx.sensors.utils.CxxAbstractRuleRepository.define(CxxAbstractRuleRepository.java:84)
sonar_1  | 	at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoader.java:52)
sonar_1  | 	at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:99)
sonar_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sonar_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sonar_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
sonar_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)

```

Hm, change rule keys from '1' numbers to 'L0001' inside pclint.xml and got another error:
```

sonar_1  | java.lang.IllegalArgumentException: Tag 'pclint,bug' is invalid. Rule tags accept only the characters: a-z, 0-9, '+', '-', '#', '.'
sonar_1  | 	at org.sonar.api.server.rule.RuleTagFormat.validate(RuleTagFormat.java:44)
sonar_1  | 	at org.sonar.api.server.rule.RulesDefinition$NewRule.addTags(RulesDefinition.java:874)
sonar_1  | 	at org.sonar.api.server.rule.RulesDefinition$NewRule.setTags(RulesDefinition.java:885)
sonar_1  | 	at org.sonar.api.server.rule.RulesDefinitionXmlLoader.processRule(RulesDefinitionXmlLoader.java:331)
sonar_1  | 	at org.sonar.api.server.rule.RulesDefinitionXmlLoader.load(RulesDefinitionXmlLoader.java:231)
sonar_1  | 	at org.sonar.cxx.sensors.utils.CxxAbstractRuleRepository.define(CxxAbstractRuleRepository.java:84)
sonar_1  | 	at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoader.java:52)
sonar_1  | 	at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:99)
sonar_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sonar_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sonar_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
sonar_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
```
I have no idea what i should to do :(

**Comment by jmecosta** [comment]
are you patching the plugin somehow? can you try in a new instance? all our
integration tests are working properly, so at least it should rule out any
problme in the plugin

**Comment by neonman63** [comment]
No, I was made editing only for debug purpose and only .xml-files. I tried this with clean database and it work as espected. So, this is database issue, may be with our custom rules/profiles.

**Comment by JStb** [comment]
Do you have defined a rule "CustomRuleTemplate" in you custom rules?
`select * from properties where prop_key like 'sonar.cxx.pclint%';`

check, if yes, then
`delete from properties where prop_key='sonar.cxx.pclint.customRules';`

**Comment by neonman63** [comment]
Yes, found one entry, deleted this and it's now working with our old database! Thanks for help!
