### ISSUE TITLE
parser exception in sslr-toolkit

### ISSUE THREAD

**Issue by jmecosta** [SonarOpenCommunity/sonar-cxx#1131]
#define ABC   DFC"SOME TEST"
func(ABC)

this crashes the analysis and parsing recovery does not ignore this

**Comment by jmecosta** [comment]
com.sonar.sslr.api.RecognitionException: Parse error at line 2 column 9:

  -->  func(DFC "AD_ENG_PAR_OFF")EOF

	at org.sonar.sslr.internal.vm.Machine.parse(Machine.java:74)
	at com.sonar.sslr.impl.Parser.parse(Parser.java:87)
	at com.sonar.sslr.impl.Parser.parse(Parser.java:81)
	at org.sonar.sslr.internal.toolkit.SourceCodeModel.setSourceCode(SourceCodeModel.java:62)
	at org.sonar.sslr.internal.toolkit.ToolkitPresenter.onSourceCodeParseButtonClick(ToolkitPresenter.java:124)
	at org.sonar.sslr.internal.toolkit.ToolkitViewImpl$5.actionPerformed(ToolkitViewImpl.java:203)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)


#1094 also has some concatenated string perhpas the same issue

**Comment by guwirth** [comment]
@jmcosta The crash is for sure an issue should be fixed.

To you other comments:
* `#define ABC DFC"SOME TEST"` is not string concatenation, there are no two strings
* Parsing recovery: is working only on declaration level (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Error-Recovery). Sample below have to syntax errors: first the wrong parameter `DFC"SOME TEST"`and then the missing semicolon. Means `before` and `after` should be parsed and `func` ignored.
```C++
void before();
#define ABC DFC"SOME TEST"
func(ABC)
void after();
```

**Comment by jmecosta** [comment]
not sure if i understand: this is the actual code and it compiles fine:

```cpp
static int FindEngine(const std::string &AttrNameBase);
#define ENGINE_PARAMETER_OFFSET   ATTRIBUTE_PREFIX"ENG_OFF"
FindEngine(ENGINE_PARAMETER_OFFSET);
```

should the recovery be extended so that it skips this file isntead of failing the analysis?

**Comment by guwirth** [comment]
@jmecosta still don't understand the problem

> his is the actual code and it compiles fine

sample is invalid C++?

using sslr-toolkit I get (in toolkit error-recovery is off):
```
com.sonar.sslr.api.RecognitionException: Parse error at line 3 column 28:
    1: static int FindEngine(const std::string &AttrNameBase);
    2: 
  -->  FindEngine(ATTRIBUTE_PREFIX "ENG_OFF");EOF
```
Using VS2015 with your sample, I get:
```C++
static int FindEngine(const std::string &AttrNameBase);
#define ENGINE_PARAMETER_OFFSET   ATTRIBUTE_PREFIX"ENG_OFF"
FindEngine(ENGINE_PARAMETER_OFFSET); // <= error  this declaration has no storage class or type specifier
```
Or with a more complete sample:
```C++
#include "stdafx.h"
#include <string>

static int FindEngine(const std::string &AttrNameBase);
#define ENGINE_PARAMETER_OFFSET   ATTRIBUTE_PREFIX"ENG_OFF"

int main() {
    FindEngine(ENGINE_PARAMETER_OFFSET);
    return 0;
}
```
error message:
```
1>c:\test.cpp(12): error C2065: 'ATTRIBUTE_PREFIX': undeclared identifier
1>c:\test.cpp(12): error C2059: syntax error: 'string'
```

**Comment by guwirth** [comment]
@jmecosta its this still an issue or can we close it?

**Comment by guwirth** [comment]
@jmecosta behaviour is as expected.
