### ISSUE TITLE
SQ 6.4 multi-module issue

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1174]
There seems to be a problem with multi-module projects with SQ6.4. Our integration test cpp-multimodule-project-2 is no more working.

Error:
```
Feature: cpp-multimodule-project

  Test multimodule project with reports at root of the project

  @SqApi56 @SqApi62
  Scenario: cpp-multimodule-project-2 
    Given the project "cpp-multimodule-project-2"
Given the project "cpp-multimodule-project-2"
    And platform is not "Windows"
And platform is not "Windows"
    When I run "sonar-scanner -X"
When I run "sonar-scanner -X"
    Then the analysis finishes successfully
Then the analysis finishes successfully
    And the analysis in server has completed
    Read Log : _cpp-multimodule-project-2_.log
     Get Analysis In Background : http://localhost:9000/api/ce/task?id=AVyGqdQdLYUUK8YxAoIM
     CURRENT STATUS : IN_PROGRESS
     CURRENT STATUS : IN_PROGRESS
     CURRENT STATUS : FAILED
     ...
```

Server error:
```
org.sonar.server.computation.task.projectanalysis.component.VisitException: Visit failed for Component {key=cpp-multimodule-project-2:A:1:a,type=DIRECTORY}  located cpp-multimodule-project-2:A:1(type=MODULE)->cpp-multimodule-project-2:A(type=MODULE)->cpp-multimodule-project-2(type=PROJECT)
	at org.sonar.server.computation.task.projectanalysis.component.VisitException.rethrowOrWrap(VisitException.java:44)
	at org.sonar.server.computation.task.projectanalysis.component.PathAwareCrawler.visit(PathAwareCrawler.java:52)
	at org.sonar.server.computation.task.projectanalysis.component.PathAwareCrawler.visitChildren(PathAwareCrawler.java:87)
	at org.sonar.server.computation.task.projectanalysis.component.PathAwareCrawler.visitImpl(PathAwareCrawler.java:70)
	at org.sonar.server.computation.task.projectanalysis.component.PathAwareCrawler.visit(PathAwareCrawler.java:50)
	at org.sonar.server.computation.task.projectanalysis.component.PathAwareCrawler.visitChildren(PathAwareCrawler.java:87)
	at org.sonar.server.computation.task.projectanalysis.component.PathAwareCrawler.visitImpl(PathAwareCrawler.java:70)
	at org.sonar.server.computation.task.projectanalysis.component.PathAwareCrawler.visit(PathAwareCrawler.java:50)
	at org.sonar.server.computation.task.projectanalysis.component.PathAwareCrawler.visitChildren(PathAwareCrawler.java:87)
	at org.sonar.server.computation.task.projectanalysis.component.PathAwareCrawler.visitImpl(PathAwareCrawler.java:70)
	at org.sonar.server.computation.task.projectanalysis.component.PathAwareCrawler.visit(PathAwareCrawler.java:50)
	at org.sonar.server.computation.task.projectanalysis.step.PersistComponentsStep.execute(PersistComponentsStep.java:99)
	at org.sonar.server.computation.task.step.ComputationStepExecutor.executeSteps(ComputationStepExecutor.java:64)
	at org.sonar.server.computation.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:52)
	at org.sonar.server.computation.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:75)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.executeTask(CeWorkerImpl.java:92)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:59)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:35)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PROJECTS_KEE ON PUBLIC.PROJECTS(KEE) VALUES ( /* 9207 */ 'cpp-multimodule-project-2:A:1:a' )"; SQL statement:
INSERT INTO projects (
    organization_uuid,
    kee,
    deprecated_kee,
    uuid,
    uuid_path,
    project_uuid,
    module_uuid,
    module_uuid_path,
    name,
    long_name,
    qualifier,
    scope,
    language,
    description,
    private,
    tags,
    root_uuid,
    path,
    copy_component_uuid,
    developer_uuid,
    enabled,
    created_at,
    authorization_updated_at,
    b_changed,
    b_copy_component_uuid,
    b_description,
    b_enabled,
    b_language,
    b_long_name,
    b_module_uuid,
    b_module_uuid_path,
    b_name,
    b_path,
    b_qualifier
    )
    VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    false,
    null,
    null,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    null
    ) [23505-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103)
	at org.h2.index.PageBtree.find(PageBtree.java:121)
	at org.h2.index.PageBtreeLeaf.addRow(PageBtreeLeaf.java:151)
	at org.h2.index.PageBtreeLeaf.addRowTry(PageBtreeLeaf.java:104)
	at org.h2.index.PageBtreeNode.addRowTry(PageBtreeNode.java:206)
	at org.h2.index.PageBtreeNode.addRowTry(PageBtreeNode.java:206)
	at org.h2.index.PageBtreeNode.addRowTry(PageBtreeNode.java:206)
	at org.h2.index.PageBtreeIndex.addRow(PageBtreeIndex.java:97)
	at org.h2.index.PageBtreeIndex.add(PageBtreeIndex.java:88)
	at org.h2.table.RegularTable.addRow(RegularTable.java:120)
	at org.h2.command.dml.Insert.insertRows(Insert.java:157)
	at org.h2.command.dml.Insert.update(Insert.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.server.TcpServerThread.process(TcpServerThread.java:346)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:160)
	at java.lang.Thread.run(Unknown Source)

### The error may involve org.sonar.db.component.ComponentMapper.insert-Inline
### The error occurred while setting parameters
### Cause: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PROJECTS_KEE ON PUBLIC.PROJECTS(KEE) VALUES ( /* 9207 */ 'cpp-multimodule-project-2:A:1:a' )"; SQL statement:
INSERT INTO projects (
    organization_uuid,
    kee,
    deprecated_kee,
    uuid,
    uuid_path,
    project_uuid,
    module_uuid,
    module_uuid_path,
    name,
    long_name,
    qualifier,
    scope,
    language,
    description,
    private,
    tags,
    root_uuid,
    path,
    copy_component_uuid,
    developer_uuid,
    enabled,
    created_at,
    authorization_updated_at,
    b_changed,
    b_copy_component_uuid,
    b_description,
    b_enabled,
    b_language,
    b_long_name,
    b_module_uuid,
    b_module_uuid_path,
    b_name,
    b_path,
    b_qualifier
    )
    VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    false,
    null,
    null,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    null
    ) [23505-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103)
	at org.h2.index.PageBtree.find(PageBtree.java:121)
	at org.h2.index.PageBtreeLeaf.addRow(PageBtreeLeaf.java:151)
	at org.h2.index.PageBtreeLeaf.addRowTry(PageBtreeLeaf.java:104)
	at org.h2.index.PageBtreeNode.addRowTry(PageBtreeNode.java:206)
	at org.h2.index.PageBtreeNode.addRowTry(PageBtreeNode.java:206)
	at org.h2.index.PageBtreeNode.addRowTry(PageBtreeNode.java:206)
	at org.h2.index.PageBtreeIndex.addRow(PageBtreeIndex.java:97)
	at org.h2.index.PageBtreeIndex.add(PageBtreeIndex.java:88)
	at org.h2.table.RegularTable.addRow(RegularTable.java:120)
	at org.h2.command.dml.Insert.insertRows(Insert.java:157)
	at org.h2.command.dml.Insert.update(Insert.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.server.TcpServerThread.process(TcpServerThread.java:346)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:160)
	at java.lang.Thread.run(Unknown Source)

	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:154)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:141)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:51)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy29.insert(Unknown Source)
	at org.sonar.db.component.ComponentDao.insert(ComponentDao.java:312)
	at org.sonar.server.computation.task.projectanalysis.step.PersistComponentsStep$PersistComponentStepsVisitor.persistComponent(PersistComponentsStep.java:225)
	at org.sonar.server.computation.task.projectanalysis.step.PersistComponentsStep$PersistComponentStepsVisitor.persistAndPopulateCache(PersistComponentsStep.java:217)
	at org.sonar.server.computation.task.projectanalysis.step.PersistComponentsStep$PersistComponentStepsVisitor.visitDirectory(PersistComponentsStep.java:189)
	at org.sonar.server.computation.task.projectanalysis.component.PathAwareCrawler.visitNode(PathAwareCrawler.java:102)
	at org.sonar.server.computation.task.projectanalysis.component.PathAwareCrawler.visitImpl(PathAwareCrawler.java:67)
	at org.sonar.server.computation.task.projectanalysis.component.PathAwareCrawler.visit(PathAwareCrawler.java:50)
	... 24 more
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PROJECTS_KEE ON PUBLIC.PROJECTS(KEE) VALUES ( /* 9207 */ 'cpp-multimodule-project-2:A:1:a' )"; SQL statement:
INSERT INTO projects (
    organization_uuid,
    kee,
    deprecated_kee,
    uuid,
    uuid_path,
    project_uuid,
    module_uuid,
    module_uuid_path,
    name,
    long_name,
    qualifier,
    scope,
    language,
    description,
    private,
    tags,
    root_uuid,
    path,
    copy_component_uuid,
    developer_uuid,
    enabled,
    created_at,
    authorization_updated_at,
    b_changed,
    b_copy_component_uuid,
    b_description,
    b_enabled,
    b_language,
    b_long_name,
    b_module_uuid,
    b_module_uuid_path,
    b_name,
    b_path,
    b_qualifier
    )
    VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    false,
    null,
    null,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    null
    ) [23505-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103)
	at org.h2.index.PageBtree.find(PageBtree.java:121)
	at org.h2.index.PageBtreeLeaf.addRow(PageBtreeLeaf.java:151)
	at org.h2.index.PageBtreeLeaf.addRowTry(PageBtreeLeaf.java:104)
	at org.h2.index.PageBtreeNode.addRowTry(PageBtreeNode.java:206)
	at org.h2.index.PageBtreeNode.addRowTry(PageBtreeNode.java:206)
	at org.h2.index.PageBtreeNode.addRowTry(PageBtreeNode.java:206)
	at org.h2.index.PageBtreeIndex.addRow(PageBtreeIndex.java:97)
	at org.h2.index.PageBtreeIndex.add(PageBtreeIndex.java:88)
	at org.h2.table.RegularTable.addRow(RegularTable.java:120)
	at org.h2.command.dml.Insert.insertRows(Insert.java:157)
	at org.h2.command.dml.Insert.update(Insert.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.server.TcpServerThread.process(TcpServerThread.java:346)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:160)
	at java.lang.Thread.run(Unknown Source)

	at org.h2.engine.SessionRemote.done(SessionRemote.java:606)
	at org.h2.command.CommandRemote.executeUpdate(CommandRemote.java:192)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:199)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:44)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:69)
	at org.apache.ibatis.executor.ReuseExecutor.doUpdate(ReuseExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:105)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:71)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:152)
	... 35 more
```

**Comment by guwirth** [comment]
leftover from ##1157

To test activate https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/integration-tests/features/multimodule_analysis_2.feature for `SqApi62` again:

```
  @SqApi56 @SqApi62
   Scenario: cpp-multimodule-project-2
...
```

**Comment by guwirth** [comment]
@jmecosta is everything working on your servers? Think this test case was added by you? Starting with SQ6.4 it is no more working.

**Comment by Bertk** [comment]
@guwirth, @jmecosta  The test multimodule_analysis_2.feature was removed - this was a not windows platform test. Is this issue still relevant?

**Comment by jmecosta** [comment]
I can check thia better at some point, I'm a bit busy with other stuff at
moment. I think around Christmas I might a bit of time to go through this.
Sorry guys

**Comment by guwirth** [comment]
@jmecosta some time to verify this? It’s about reports outside of root...

**Comment by Bertk** [comment]
@guwirth @jmecosta I have no problem with this limitation and my reports are anyway located in the source folder or root folder of the multi module project (MSVC project file location).

**Comment by jmecosta** [comment]
No time yet to see this, as @bertk we don't experience any issues with these. I try to check soon.

**Comment by guwirth** [comment]
No known issue in this area. I close it.
