### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by gyorb** [SonarOpenCommunity/sonar-cxx#1177]
During the analysis of the doxygen project I got an error:

I've used SonarQube 6.4 server, sonar-scanner-3.0.3.778-linux and I built the plugin from the master branch.

I think the new sslr version causes the problem introduced in [521f753](https://github.com/SonarOpenCommunity/sonar-cxx/commit/521f75308d2d8838d9f33ce55b7826f004123eb8). Reverting that commit I was able to analyze the project without any errors as before.

Should I write to the SonarQube google group about the issue?

This is the error message I've got during the analysis and no results were stored to the central server.
```
18:33:40.122 ERROR: Error during SonarQube Scanner execution
org.sonar.squidbridge.api.AnalysisException: Unable to parse file: ~/doxygen/build/generated_src/doctokenizer.cpp
        at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:105)
        at org.sonar.cxx.sensors.squid.CxxSquidSensor.execute(CxxSquidSensor.java:181)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:87)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:81)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:67)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:75)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:178)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:259)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:254)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:243)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOf(Arrays.java:3181)
        at java.util.ArrayList.toArray(ArrayList.java:376)
        at java.util.ArrayList.addAll(ArrayList.java:577)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:60)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
18:33:40.122 INFO: Final Memory: 45M/1756M
18:33:40.122 INFO: ------------------------------------------------------------------------
18:33:40.124 DEBUG: Execution getVersion
18:33:40.124 DEBUG: Execution stop
```

**Comment by guwirth** [comment]
Hi, 

have you tried with more memory, see https://docs.sonarqube.org/plugins/servlet/mobile#AnalyzingwithSonarQubeScanner-Troubleshooting

Regards

**Comment by guwirth** [comment]
@gyorb is this issue solved?

Java heap space error or java.lang.OutOfMemoryError,

Increase the memory via the SONAR_SCANNER_OPTS environment variable:
```
export SONAR_SCANNER_OPTS="-Xmx512m"
```
On Windows environments, avoid the double-quotes, since they get misinterpreted and combine the two parameters into a single one.
```
set SONAR_SCANNER_OPTS=-Xmx512m
```

**Comment by gyorb** [comment]
I've set the environment variable `export SONAR_SCANNER_OPTS="-Xmx512m"` but I've got the same error.

**Comment by guwirth** [comment]
@gyorb please try again with bigger value, e.g. `export SONAR_SCANNER_OPTS="-Xmx2048m"`. If problem is still present you can also try to ask SonarQube group.

**Comment by gyorb** [comment]
Thanks @guwirth! Increasing the maximum heap size to 2GB solved the problem.

**Comment by guwirth** [comment]
@gyorb you are welcome. Seem that 1.22 SSLR needs a little bit more memory?

**Comment by gyorb** [comment]
Yes, I've run the same analysis on the same project and it was successful with the default settings if  v1.21 SSLR was used but failed with v1.22.

**Comment by vxr07990** [comment]
export SONAR_SCANNER_OPTS="-Xmx2048m" we should specify this in sonar-scanner properties or my pc .bashrc

**Comment by ucheakajiuba** [comment]
where do i set this SONAR_SCANNER_OPTS environment variable since i use sonarcloud UI and properties file

**Comment by guwirth** [comment]
Hi @ucheakajiuba,

you always should open a new issue for a new question.

SONAR_SCANNER_OPTS Is only in use during the scan of a project. There are different scanners, which one are you using? See the documentation for more details https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/overview/

Regards,
