### ISSUE TITLE
Relative path causes NPE

### ISSUE THREAD

**Issue by yachoor** [SonarOpenCommunity/sonar-cxx#1199]
After change in https://github.com/SonarOpenCommunity/sonar-cxx/commit/ef20a95ff34b665397f7da9135f7c00d1c8db3a9#diff-12a8ec1d2a533c7305380c2611271cc4R254 I get java.lang.NullPointerException in org.sonar.cxx.sensors.utils.CxxUtils.normalizePathFull(CxxUtils.java:74), called from org.sonar.cxx.sensors.utils.CxxReportSensor.saveViolation(CxxReportSensor.java:265) for filename with relative path ("../../src/hardware/ISerialPort.cpp")

Also you might want to improve logging exceptions in CxxReportSensor - "Cannot feed the data into sonar, details: 'java.lang.NullPointerException'" isn't really helpful without stack trace.

**Comment by yachoor** [comment]
Sorry, latest versions: sonar-cxx 0.9.8-SNAPSHOT and SonarQube 6.5

The problem is that PathUtils.sanitize() returns null for relative path filename here: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/CxxReportSensor.java#L265

Stack trace:
```
java.lang.NullPointerException: null
        at org.sonar.cxx.sensors.utils.CxxUtils.normalizePathFull(CxxUtils.java:74)
        at org.sonar.cxx.sensors.utils.CxxReportSensor.saveViolation(CxxReportSensor.java:265)
        at org.sonar.cxx.sensors.utils.CxxReportSensor.saveUniqueViolation(CxxReportSensor.java:244)
        at org.sonar.cxx.sensors.compiler.CxxCompilerSensor.processReport(CxxCompilerSensor.java:128)
        at org.sonar.cxx.sensors.utils.CxxReportSensor.executeReport(CxxReportSensor.java:116)
        at org.sonar.cxx.sensors.utils.CxxReportSensor.execute(CxxReportSensor.java:87)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:179)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:261)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:256)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:245)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:119)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:240)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:72)
        at org.sonarsource.scanner.cli.Main.main(Main.java:60)
```

**Comment by guwirth** [comment]
Hi @Bertk,
seems there is an regression (https://github.com/SonarOpenCommunity/sonar-cxx/commit/ef20a95ff34b665397f7da9135f7c00d1c8db3a9#diff-12a8ec1d2a533c7305380c2611271cc4R254) in one of your changes. Do you have time to fix it?
Regards,

**Comment by guwirth** [comment]
@yachoor please try again with latest snapshot.

**Comment by guwirth** [comment]
@yachoor maybe you can document your environment in #1196

**Comment by yachoor** [comment]
Thanks, works great
