### ISSUE TITLE
sonar-scanner hangs during scan

### ISSUE THREAD

**Issue by fgsalomon** [SonarOpenCommunity/sonar-cxx#1383]
Hello,

When running `sonar-scanner` on one of my projects the scan hangs without completing:
```
[...]
WARN: [/usr/include/c++/5/system_error:39]: cannot find the sources for '#include <bits/error_constants.h>'
WARN: [/usr/include/c++/5/streambuf:38]: cannot find the sources for '#include <bits/c++config.h>'
WARN: [/usr/include/c++/5/cwctype:41]: cannot find the sources for '#include <bits/c++config.h>'
WARN: [/usr/include/c++/5/bits/locale_facets.h:41]: cannot find the sources for '#include <bits/ctype_base.h>'
WARN: [/usr/include/c++/5/bits/locale_facets.h:1534]: cannot find the sources for '#include <bits/ctype_inline.h>'
WARN: [/usr/local/include/opencv2/core/types_c.h:62]: cannot find the sources for '#include <assert.h>'
WARN: [/usr/local/include/opencv2/core/types_c.h:63]: cannot find the sources for '#include <stdlib.h>'
WARN: [/usr/local/include/opencv2/core/types_c.h:64]: cannot find the sources for '#include <string.h>'
WARN: [/usr/local/include/opencv2/core/types_c.h:65]: cannot find the sources for '#include <float.h>'
WARN: [/usr/local/include/opencv2/ml.hpp:53]: cannot find the sources for '#include <float.h>'
WARN: [/usr/include/c++/5/iostream:38]: cannot find the sources for '#include <bits/c++config.h>'
```
I tried running it with `-X` but it doesn't provide significant information.

My environment is:
```
SonarQube Scanner: 3.0.3.778 (running on Ubuntu 16.04)
SonarQube server: 6.4.0
sonar-cxx-plugin: 0.9.8
```

My `sonar-project.properties` file:
```
sonar.language=c++
sonar.sourceEncoding=UTF-8
sonar.cxx.includeDirectories=/usr/local/include/opencv,/usr/local/include/opencv2,/usr/local/include,/usr/include/c++/5,/usr/include/c++/5/bits,/usr/include/x86_64-linux-gnu/c++/5/bits,/usr/include/x86_64-linux-gnu/c++/5,/usr/include,/usr/include/x86_64-linux-gnu/bits/,/usr/include/c++/5.4.0/tr1/
```
In addition to hanging I don't know why it keeps warning about missing sources, I've included the system directories as in your sample project.

What I'm doing wrong?

Thanks

**Comment by guwirth** [comment]
Hi @fgsalomon,

* Do you have always the problem, also with a small demo project?
* Is there a hint on server side in the LOG file?
* Would play around:
  * Is it possible to narrow it down to a specific cpp file?
  * Does it occur without providing `sonar.cxx.includeDirectories`?
  * Does it occur without providing `sonar.sourceEncoding`?

> In addition to hanging I don't know why it keeps warning about missing sources

Maybe you can try to add `.` to `sonar.cxx.includeDirectories`.

Regards,

**Comment by fgsalomon** [comment]
Thank you @guwirth, I narrowed to a header file. It's a dependency problem, this header file is only used in one specific configuration and references external code that is not available in the standard configuration. The header file contains similar code to [this](http://dlib.net/dnn_imagenet_train_ex.cpp.html). Excluding this file the scan finishes without additional errors. It would be nicer if the scanner would output an error instead of hanging though.

I tried adding `.` to `sonar.cxx.includeDirectories` but it keeps throwing these kind of warnings:
```
WARN: [/usr/include/c++/5/streambuf:38]: cannot find the sources for '#include <bits/c++config.h>'
WARN: [/usr/include/c++/5/cwctype:41]: cannot find the sources for '#include <bits/c++config.h>'
```

**Comment by guwirth** [comment]
@fgsalomon looking to the file it could be the templates and the `>`:
```C++
using residual_down = add_prev2<avg_pool<2,2,2,2,skip1<tag2<block<N,BN,2,tag1<SUBNET>>>>>>;
```
Maybe you can try to add blanks between the `>`.

`
WARN: [/usr/include/c++/5/streambuf:38]: cannot find the sources for '#include <bits/c++config.h>'
`

Searching for "bits/c++config.h" is the remaining part to the folder of this file part of "sonar.cxx.includeDirectories"?

**Comment by sofaglass** [comment]
I have the same problem using dlib. @fgsalomon did you manage to solve the problem without excluding the file?

**Comment by guwirth** [comment]
@sofaglass thanks for the hint. Which version of the cxx plugin are you using?

**Comment by fgsalomon** [comment]
I'm sorry. We've moved from dlib to another framework and I forgot about this. Thank you for your support @guwirth.

**Comment by sofaglass** [comment]
However, the bug in the scanner persists 😃It should be able to run and report an error (if there is one) without freezing.

**Comment by jft44** [comment]
Hello, I have the same bug with one of my sonar project... The analysis don't finish and hangs after listing of headers warning. 
I use sonarqube 7.3 and cxx community 1.2.0-SNAPSHOT (downloaded this morning).
I have another project, I use cxx community and it's works fine. I don't understand what is the issue...
Sonar SquidSensor don't generate logs ?

**Comment by guwirth** [comment]
@fgsalomon please turn debug info on and try again: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information.

**Comment by avocadomaster** [comment]
@jft44 I can confirm that adding spaces `<>` solves the problem for me using dlib and opencv.

**Comment by guwirth** [comment]
@jft44 could you also provide simple samples for testing? Maybe there is a problem with 3 and multiple (3,6,9, ...) `>` because of the CUDA support?

**Comment by guwirth** [comment]
@jft44 thx same code, same sample: 6x `>`. Is there another location you have to fix?

**Comment by liucc52** [comment]
we found this is a bug of sslr, the thread dump show the main thread hang at 
  java.lang.Thread.State: RUNNABLE
	at org.sonar.sslr.internal.vm.Machine.execute(Machine.java:162)
	at org.sonar.sslr.internal.vm.Machine.execute(Machine.java:105)
	at org.sonar.sslr.internal.vm.Machine.parse(Machine.java:61)
	at com.sonar.sslr.impl.Parser.parse(Parser.java:84)
	at com.sonar.sslr.impl.Parser.parse(Parser.java:69)
	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:94)
	at org.sonar.cxx.sensors.squid.CxxSquidSensor.execute(CxxSquidSensor.java:156)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:177)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:291)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:286)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:264)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
	- locked <0x00000007022abca8> (a org.sonar.batch.bootstrapper.Batch)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

**Comment by ericlemes** [comment]
Just to give some extra information about this. Every couple of months, I bump in this issue again.

Seems like there's some sort of memory leak in AstNodes. I've run the process with a jvisualvm to get some insights about what is going on with the memory.

This is what I've got?

![image](https://user-images.githubusercontent.com/1776244/50302306-98102d00-0481-11e9-89b7-6ca77bd09a2b.png)

Even though I run my process with -Xmx16G on a 64bit vm, seems like the VM is not willing to allow the heap to grow more than 8GB. But the problem itself is a general performance problem due to the amount of memory used.

Looking at a heap dump, I notice that there's a lot of AstNode instances. Is there any chances that we are holding node instances after we finish the scan?

![image](https://user-images.githubusercontent.com/1776244/50302399-e58c9a00-0481-11e9-8896-3e26cc2fdb4f.png)

There are 15 million instances of AstNode :-(

**Comment by guwirth** [comment]
@ericlemes may be update to SSLR 1.23 fixed it (cxx 1.2.1). There was a memory leak fixed?

**Comment by ivangalkin** [comment]
@ericlemes 

> seems like the VM is not willing to allow the heap to grow more than 8GB

In general the sawtooth-like diagram looks ok to me: it looks after the ParallelOldGC (or maybe the CMS). The referenced memory is permanently increased (from 0 in the beginning to ~2 GB at the end). The structure of these 2GB is not really clear. At least the half of them might be collected metrics (`java.lang.Object[]`, `java.util.ArrayList`?). but the large amount of `AstNode` instances looks in fact a bit strange. It is possible, that some of our/SSLR structures still references the ASTs. We have to take look at the lifetime of our parsed ASTs and eliminate the global objects.

My first candidate would be `CxxParser::cxxpp`. I will try to eliminate this singleton.

**Comment by ericlemes** [comment]
This is my prod environment, so I'll do some more tests tomorrow with the upgraded version that @guwirth  suggested. And maybe get some more insights for  @ivangalkin . 

Thanks for your feedback guys!

**Comment by ericlemes** [comment]
About the sawtooth pattern, what happens is that everytime the GC runs, the overall memory increases. Until it gets to the point that the process stalls. I left once by literally days running like this. What is really suprising for me is the fact that the JVM doesn't allow the heap to grow more, even having free memory and a -Xmx16G

**Comment by ivangalkin** [comment]
@ericlemes most probably you are running a generational garbage collector with young/old generation (aka eden/tenured). Young generation aimed to hold objects with a short lifetime. It is garbage-collected often but fast. If some of objects survive multiple young-GCs, they are moved to the old generation. If such move is not possible, the old-GC or the full-GC are executed. Such GC should be seldom, since it's more time-intensive.This is a very simplified explanation, at which points in time the GC is executed. There are several GC algorithms with different options how to tune them. If you want to utilize all the 16 GBs of your heap, you might want to increase the young-generation size... but than the young-GC will take longer. So it's not necessary a benefit.

**Comment by ericlemes** [comment]
Just an update about this:

I've upgraded to 1.2.2 as suggested by @guwirth, one memory leak is definitely solved there. But it still hangs. Hanging is probably not the right word, since it is still running, but gets slower and slower as the code base grows.

The thread dump looks like: 

"main" #1 prio=5 os_prio=0 tid=0x0000000002c12800 nid=0x532c runnable [0x0000000002c0d000]
   java.lang.Thread.State: RUNNABLE
        at org.sonar.sslr.internal.vm.Machine.execute(Machine.java:162)
        at org.sonar.sslr.internal.vm.Machine.execute(Machine.java:105)
        at org.sonar.sslr.internal.vm.Machine.parse(Machine.java:61)
        at com.sonar.sslr.impl.Parser.parse(Parser.java:84)
        at com.sonar.sslr.impl.Parser.parse(Parser.java:69)
        at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:94)
        at org.sonar.cxx.sensors.squid.CxxSquidSensor.execute(CxxSquidSensor.java:155)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:177)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:291)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:286)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:264)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
        at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)

Which seems to be parsing, and doing some magic related to the sslr library (there's a //Todo in SonarSource:

 public AstNode parse(List<Token> tokens) {
    // TODO can be compiled only once
    CompiledGrammar g = MutableGrammarCompiler.compile((CompilableGrammarRule) rootRule);
    return LexerfulAstCreator.create(Machine.parse(tokens, g), tokens);
  }

Looking at the heap it seems that the biggest offender are char[] and strings: 
![image](https://user-images.githubusercontent.com/1776244/50834378-cc259200-134b-11e9-8b2d-ea8df70924b0.png)

What grabs my attention are objects like SourceFunction alive, but I'm not sure if it is a memory leak or not. It could be only the ones that the GC didn't have a chance to collect.

So, my bet here is a performance issue. It seems that there's a lot of TreeMap$Entry that holds objects related to the parser. My bet is that there's some sort of performance optmisation that can help here, perhaps reducing the number of alive objects or using better data structures, but everything points at the structure of the sslr library or the way the grammar is defined. 

Just to give an idea, the process now is using about 1.3GB of memory, but the analysis is running for over 2 hours with a codebase of about 1 million lines of code. If I break down this codebase in 3, it takes less than 20 minutes to scan. That's what makes me think that the analysis time get exponentially slower as the code base grows.

**Comment by ericlemes** [comment]
Just an update about this:

I've upgraded to 1.2.2 as suggested by @guwirth, one memory leak is definitely solved there. But it still hangs. Hanging is probably not the right word, since it is still running, but gets slower and slower as the code base grows.

The thread dump looks like: 

"main" #1 prio=5 os_prio=0 tid=0x0000000002c12800 nid=0x532c runnable [0x0000000002c0d000]
   java.lang.Thread.State: RUNNABLE
        at org.sonar.sslr.internal.vm.Machine.execute(Machine.java:162)
        at org.sonar.sslr.internal.vm.Machine.execute(Machine.java:105)
        at org.sonar.sslr.internal.vm.Machine.parse(Machine.java:61)
        at com.sonar.sslr.impl.Parser.parse(Parser.java:84)
        at com.sonar.sslr.impl.Parser.parse(Parser.java:69)
        at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:94)
        at org.sonar.cxx.sensors.squid.CxxSquidSensor.execute(CxxSquidSensor.java:155)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:177)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:291)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:286)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:264)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
        at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)

Which seems to be parsing, and doing some magic related to the sslr library (there's a //Todo in SonarSource:

 public AstNode parse(List<Token> tokens) {
    // TODO can be compiled only once
    CompiledGrammar g = MutableGrammarCompiler.compile((CompilableGrammarRule) rootRule);
    return LexerfulAstCreator.create(Machine.parse(tokens, g), tokens);
  }

Looking at the heap it seems that the biggest offender are char[] and strings: 
![image](https://user-images.githubusercontent.com/1776244/50834378-cc259200-134b-11e9-8b2d-ea8df70924b0.png)

What grabs my attention are objects like SourceFunction alive, but I'm not sure if it is a memory leak or not. It could be only the ones that the GC didn't have a chance to collect.

So, my bet here is a performance issue. It seems that there's a lot of TreeMap$Entry that holds objects related to the parser. My bet is that there's some sort of performance optmisation that can help here, perhaps reducing the number of alive objects or using better data structures, but everything points at the structure of the sslr library or the way the grammar is defined. 

Just to give an idea, the process now is using about 1.3GB of memory, but the analysis is running for over 2 hours with a codebase of about 1 million lines of code. If I break down this codebase in 3, it takes less than 20 minutes to scan. That's what makes me think that the analysis time get exponentially slower as the code base grows.

**Comment by guwirth** [comment]
see #1685
