### ISSUE TITLE
CppCheck parse error: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by GOMSPACEMartin** [SonarOpenCommunity/sonar-cxx#1392]
Trying to parse the cppcheck result xml file results in an error:
`java.lang.NoSuchMethodError: org.sonar.api.resources.File.fromIOFile(Ljava/io/File;Lorg/sonar/api/resources/Project;)Lorg/sonar/api/resources/File;`

**Versions:**
- cppcheck v. 1.82
- SonarQube v. 6.7 (build 33306) 
- Ubuntu 16.04.3 LTS (Linux 4.13.0-26-generic amd64)
- C (Community) v. 0.9.9
- SonarQube Scanner v. 3.0.3.778
- Java v. 1.8.0_151 Oracle Corporation (64-bit)

**Execution**
```
# cppcheck src --enable=all --inconclusive --std=posix --std=c99 --inline-suppr --xml --xml-version=2 2> ./build/cppcheck-results.xml
# sonar-scanner -X -Dsonar.verbose=true -Dsonar.log.level=DEBUG
```

**Result:**
```
14:38:14.355 DEBUG: Sensors : Cppcheck -> c++ XunitSensor -> c SquidSensor -> c RatsSensor -> c CppCheckSensor -> c PCLintSensor -> c DrMemorySensor -> c CompilerSensor -> c VeraxxSensor -> c ValgrindSensor -> c ClangTidySensor -> c ClangSASensor -> c ExternalRulesSensor -> c XunitSensor -> c CoverageSensor -> SonarJavaXmlFileSensor -> XML Sensor -> Analyzer for "php.ini" files -> Zero Coverage Sensor -> CPD Block Indexer
14:38:14.364 INFO: Sensor Cppcheck [cppcheck]
14:38:14.585 INFO: Cppcheck version: 1.82
14:38:14.780 INFO: ------------------------------------------------------------------------
14:38:14.784 INFO: EXECUTION FAILURE
14:38:14.784 INFO: ------------------------------------------------------------------------
14:38:14.785 INFO: Total time: 1:11.431s
14:38:14.964 INFO: Final Memory: 51M/154M
14:38:14.966 INFO: ------------------------------------------------------------------------
14:38:14.966 ERROR: Error during SonarQube Scanner execution
java.lang.NoSuchMethodError: org.sonar.api.resources.File.fromIOFile(Ljava/io/File;Lorg/sonar/api/resources/Project;)Lorg/sonar/api/resources/File;
	at org.sonarqube.cppcheck.CppcheckSensor.save(CppcheckSensor.java:103)
	at org.sonarqube.cppcheck.CppcheckSensor.saveAll(CppcheckSensor.java:80)
	at org.sonarqube.cppcheck.CppcheckSensor.analyse(CppcheckSensor.java:72)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
14:38:14.978 DEBUG: Execution getVersion
14:38:14.979 DEBUG: Execution stop
```

**Additional Information**

I noticed that I also got this information in the beginning of the analysis :

> ... API compatibility mode is enabled on plugin SonarQube :: Cppcheck Plugin [cppcheck] (built with API lower than 5.2)

```
14:37:07.545 DEBUG: Load plugins
14:37:07.623 DEBUG: Load plugins (done) | time=79ms
14:37:07.750 DEBUG: API compatibility mode is enabled on plugin SonarQube :: Cppcheck Plugin [cppcheck] (built with API lower than 5.2)
14:37:08.229 DEBUG: Plugins:
14:37:08.230 DEBUG:   * C++ (Community) 0.9.9 (cxx)
14:37:08.230 DEBUG:   * GitHub 1.4.2.1027 (github)
14:37:08.237 DEBUG:   * SonarPython 1.8.0.1496 (python)
14:37:08.238 DEBUG:   * C (Community) 0.9.9 (c)
14:37:08.240 DEBUG:   * GitHub Authentication for SonarQube 1.3 (authgithub)
14:37:08.242 DEBUG:   * SonarQube :: Plugins :: SCM :: SVN 1.6.0.860 (scmsvn)
14:37:08.243 DEBUG:   * SonarJS 3.2.0.5506 (javascript)
14:37:08.243 DEBUG:   * SonarC# 6.5.0.3766 (csharp)
14:37:08.243 DEBUG:   * SonarJava 4.15.0.12310 (java)
14:37:08.244 DEBUG:   * SonarQube :: Cppcheck Plugin 1.0 (cppcheck)
14:37:08.246 DEBUG:   * Flex 2.3 (flex)
14:37:08.246 DEBUG:   * SonarQube :: Plugins :: SCM :: Git 1.3.0.869 (scmgit)
14:37:08.252 DEBUG:   * SonarXML 1.4.3.1027 (xml)
14:37:08.255 DEBUG:   * SonarPHP 2.11.0.2485 (php)
14:37:08.260 DEBUG:   * SonarTS 1.1.0.1079 (typescript)
14:37:08.272 DEBUG:   * Build Breaker 2.2 (buildbreaker)
14:37:08.274 DEBUG:   * SVG Badges 3.0.1 (status)
```
** This might also be related to this issue : https://github.com/SonarQubeCommunity/sonar-cppcheck/issues/6

**Comment by Bertk** [comment]
Hi,

please remove the [cppcheck plugin ](https://github.com/SonarQubeCommunity/sonar-cppcheck) which uses SQ API V4.5.4 and was not updated since 2 years. There is also an identical issue for the CppCheck plugin [#6](https://github.com/SonarQubeCommunity/sonar-cppcheck/issues/6)

Try again and configure the SonarOpenCommunity C plug-in to detect the cppcheck result file. 
```sonar.c.cppcheck.reportPath=cpp-results.xml```

Best Regrads
Bert

**Comment by guwirth** [comment]
@GOMSPACEMartin in general it should work. We are testing this in an unit test, integration test and all our local projects are also using cppcheck file format v2.

**Comment by guwirth** [comment]
Cppcheck Plugin issue:

`14:37:08.244 DEBUG:   * SonarQube :: Cppcheck Plugin 1.0 (cppcheck)`

**Comment by GOMSPACEMartin** [comment]
This was solved by removing the cppcheck plugin alright, but the SonarOpenCommunity C plug-in should not fail if this was installed along with it.
