### ISSUE TITLE
org.sonar.squidbridge.api.AnalysisException: Unable to parse file

### ISSUE THREAD

**Issue by ctonur** [SonarOpenCommunity/sonar-cxx#1393]
I set java setting like that export SONAR_SCANNER_OPTS="-Xmx3062m -XX:MaxPermSize=512m -XX:ReservedCodeCacheSize=128m"

sonar scanner failed could you help me, please 
 

ARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 4,505ms last 8 cycles average is 563ms
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 12:53.388s
INFO: Final Memory: 70M/1514M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
org.sonar.squidbridge.api.AnalysisException: Unable to parse file: /src/vrdsCpmFsmComponent.c
        at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:105)
        at org.sonar.cxx.sensors.squid.CxxSquidSensor.execute(CxxSquidSensor.java:164)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseE

**Comment by ctonur** [comment]
add log 

mpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:69)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
        at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAst

**Comment by ctonur** [comment]
plugin version sonar-cxx-plugin-0.9.9
sonar-scanner-3.0.3.778-linux
sonarqube sonarqube-6.7.1

**Comment by Bertk** [comment]
Hi, can you please provide more details.
- Are you able to run a analysis successfully with another C project?
- Did you observe the memory problem only with /src/vrdsCpmFsmComponent.c

Please also check the Wiki e.g. https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Force-Include
