### ISSUE TITLE
Sonarqube does not start

### ISSUE THREAD

**Issue by HugoSecteur4** [SonarOpenCommunity/sonar-cxx#1446]
Hi, I download sonarqube-6.7.2 on Ubuntu 16.04. When I lunch the server it doesn't work but I do not know why. If you wan maybe help me please 

log :

hugogda@hugogda-G74Sx:~/Téléchargements/sonarqube-6.7.2/bin/linux-x86-64$ sudo ./sonar.sh console
Running SonarQube...
wrapper  | --> Wrapper Started as Console
wrapper  | Launching a JVM...
jvm 1    | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
jvm 1    |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
jvm 1    | 
jvm 1    | 2018.03.31 17:50:14 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /home/hugogda/Téléchargements/sonarqube-6.7.2/temp
jvm 1    | 2018.03.31 17:50:14 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
jvm 1    | 2018.03.31 17:50:14 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/home/hugogda/Téléchargements/sonarqube-6.7.2/elasticsearch]: /home/hugogda/Téléchargements/sonarqube-6.7.2/elasticsearch/bin/elasticsearch -Epath.conf=/home/hugogda/Téléchargements/sonarqube-6.7.2/temp/conf/es
jvm 1    | 2018.03.31 17:50:14 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
jvm 1    | 2018.03.31 17:50:14 INFO  app[][o.e.p.PluginsService] no modules loaded
jvm 1    | 2018.03.31 17:50:14 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
jvm 1    | 2018.03.31 17:50:15 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 1
jvm 1    | 2018.03.31 17:50:15 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
jvm 1    | 2018.03.31 17:50:15 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
wrapper  | <-- Wrapper Stopped

**Comment by HugoSecteur4** [comment]
If I run it without the sudo, this is the trace :  

hugogda@hugogda-G74Sx:~/Téléchargements/sonarqube-6.7.2/bin/linux-x86-64$ ./sonar.sh console
Running SonarQube...
wrapper  | --> Wrapper Started as Console
wrapper  | Launching a JVM...
jvm 1    | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
jvm 1    |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
jvm 1    | 
jvm 1    | 2018.03.31 17:58:32 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /home/hugogda/Téléchargements/sonarqube-6.7.2/temp
jvm 1    | 
jvm 1    | WrapperSimpleApp: Encountered an error running main: java.nio.file.AccessDeniedException: /home/hugogda/Téléchargements/sonarqube-6.7.2/temp/conf/es/log4j2.properties
jvm 1    | java.nio.file.AccessDeniedException: /home/hugogda/Téléchargements/sonarqube-6.7.2/temp/conf/es/log4j2.properties
jvm 1    | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
jvm 1    | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
jvm 1    | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
jvm 1    | 	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
jvm 1    | 	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
jvm 1    | 	at java.nio.file.Files.delete(Files.java:1126)
jvm 1    | 	at org.sonar.process.FileUtils2$DeleteRecursivelyFileVisitor.visitFile(FileUtils2.java:170)
jvm 1    | 	at org.sonar.process.FileUtils2$DeleteRecursivelyFileVisitor.visitFile(FileUtils2.java:165)
jvm 1    | 	at java.nio.file.Files.walkFileTree(Files.java:2670)
jvm 1    | 	at java.nio.file.Files.walkFileTree(Files.java:2742)
jvm 1    | 	at org.sonar.process.FileUtils2.deleteDirectoryImpl(FileUtils2.java:127)
jvm 1    | 	at org.sonar.process.FileUtils2.deleteDirectory(FileUtils2.java:112)
jvm 1    | 	at org.sonar.application.AppFileSystem$CleanTempDirFileVisitor.visitFile(AppFileSystem.java:117)
jvm 1    | 	at org.sonar.application.AppFileSystem$CleanTempDirFileVisitor.visitFile(AppFileSystem.java:101)
jvm 1    | 	at java.nio.file.Files.walkFileTree(Files.java:2670)
jvm 1    | 	at org.sonar.application.AppFileSystem.createOrCleanTempDirectory(AppFileSystem.java:96)
jvm 1    | 	at org.sonar.application.AppFileSystem.reset(AppFileSystem.java:62)
jvm 1    | 	at org.sonar.application.App.start(App.java:55)
jvm 1    | 	at org.sonar.application.App.main(App.java:78)
jvm 1    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jvm 1    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jvm 1    | 	at java.lang.reflect.Method.invoke(Method.java:498)
jvm 1    | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
jvm 1    | 	at java.lang.Thread.run(Thread.java:748)
wrapper  | <-- Wrapper Stopped

**Comment by HugoSecteur4** [comment]
I resolve it by myself, it's dirty but I exec "sudo chmod 777 ./*" and I launch the script without "sudo."

**Comment by ivangalkin** [comment]
Hi @HugoSecteur4,

 it looks like your user fails to create a temp directory. One of the reasons can be wrong access permissions to the installation directory. If it's not possible to change them, you can configure custom temp and data directories in sonar.properties

```properties
# Paths to persistent data files (embedded database and search index) and temporary files.
# Can be absolute or relative to installation directory.
# Defaults are respectively <installation home>/data and <installation home>/temp
sonar.path.data=data
sonar.path.temp=temp
```
Please see also https://github.com/SonarSource/sonarqube/blob/master/sonar-application/src/main/assembly/conf/sonar.properties

**Comment by ivangalkin** [comment]
@HugoSecteur4 P.S. it doesn't look like an issue of the SonarCxx plugin, but rather of your installation.

**Comment by devoopsnaresh** [comment]
i would strongly recommend this [sonarqube not starting](https://www.decodingdevops.com/sonarqube-not-starting-in-linux-centos-rhel-docker-solved/)

**Comment by shweta2702** [comment]
> If I run it without the sudo, this is the trace :
> 
> hugogda@hugogda-G74Sx:~/Téléchargements/sonarqube-6.7.2/bin/linux-x86-64$ ./sonar.sh console
> Running SonarQube...
> wrapper | --> Wrapper Started as Console
> wrapper | Launching a JVM...
> jvm 1 | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
> jvm 1 | Copyright 1999-2006 Tanuki Software, Inc. All Rights Reserved.
> jvm 1 |
> jvm 1 | 2018.03.31 17:58:32 INFO app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /home/hugogda/Téléchargements/sonarqube-6.7.2/temp
> jvm 1 |
> jvm 1 | WrapperSimpleApp: Encountered an error running main: java.nio.file.AccessDeniedException: /home/hugogda/Téléchargements/sonarqube-6.7.2/temp/conf/es/log4j2.properties
> jvm 1 | java.nio.file.AccessDeniedException: /home/hugogda/Téléchargements/sonarqube-6.7.2/temp/conf/es/log4j2.properties
> jvm 1 | at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
> jvm 1 | at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
> jvm 1 | at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
> jvm 1 | at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
> jvm 1 | at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
> jvm 1 | at java.nio.file.Files.delete(Files.java:1126)
> jvm 1 | at org.sonar.process.FileUtils2$DeleteRecursivelyFileVisitor.visitFile(FileUtils2.java:170)
> jvm 1 | at org.sonar.process.FileUtils2$DeleteRecursivelyFileVisitor.visitFile(FileUtils2.java:165)
> jvm 1 | at java.nio.file.Files.walkFileTree(Files.java:2670)
> jvm 1 | at java.nio.file.Files.walkFileTree(Files.java:2742)
> jvm 1 | at org.sonar.process.FileUtils2.deleteDirectoryImpl(FileUtils2.java:127)
> jvm 1 | at org.sonar.process.FileUtils2.deleteDirectory(FileUtils2.java:112)
> jvm 1 | at org.sonar.application.AppFileSystem$CleanTempDirFileVisitor.visitFile(AppFileSystem.java:117)
> jvm 1 | at org.sonar.application.AppFileSystem$CleanTempDirFileVisitor.visitFile(AppFileSystem.java:101)
> jvm 1 | at java.nio.file.Files.walkFileTree(Files.java:2670)
> jvm 1 | at org.sonar.application.AppFileSystem.createOrCleanTempDirectory(AppFileSystem.java:96)
> jvm 1 | at org.sonar.application.AppFileSystem.reset(AppFileSystem.java:62)
> jvm 1 | at org.sonar.application.App.start(App.java:55)
> jvm 1 | at org.sonar.application.App.main(App.java:78)
> jvm 1 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> jvm 1 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> jvm 1 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> jvm 1 | at java.lang.reflect.Method.invoke(Method.java:498)
> jvm 1 | at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
> jvm 1 | at java.lang.Thread.run(Thread.java:748)
> wrapper | <-- Wrapper Stopped

how did you resolved ??????

**Comment by guwirth** [comment]
Hi @shweta2702,

please ask questions about SonarQube here: https://community.sonarsource.com/
This forum is only about the cxx plugin. 

Regards,
