### ISSUE TITLE
Sonarqube unable to parse C files

### ISSUE THREAD

**Issue by amitkumar2283** [SonarOpenCommunity/sonar-cxx#1458]
### Description

One of my team members is facing the below issue while scanning his project code. He gets a lot of Lexer errors, before the task finally dies with a "StackOverflowError"; which always occurs while parsing `C:/slave/workspace/kai/mops_conf_d4_umops_v4_4700/mops_core/MoPS_lua.c`

Does anyone know what may be happening here?

Full trace below:
### LOG file
```

11:20:47 11:20:47.317 DEBUG - Parse 'C:\slave\workspace\kai\mops_conf_d4_umops_v4_4700\mops_core\MoPS_led.h' as C++ file
11:20:47 11:20:47.431 ERROR - Unable to parse file: C:\slave\workspace\kai\mops_conf_d4_umops_v4_4700\mops_core\MoPS_led.h
11:20:47 11:20:47.431 ERROR - Lexer error: Unable to lex url: file:/C:/slave/workspace/kai/mops_conf_d4_umops_v4_4700/mops_core/MoPS_led.h
11:20:47 11:20:47.431 DEBUG - API File: MoPS_led.h
11:20:47 11:20:47.431 DEBUG - Header file suffixes: [.hxx, .hpp, .hh, .h]
11:20:47 11:20:47.431 DEBUG - finished preprocessing 'C:\slave\workspace\kai\mops_conf_d4_umops_v4_4700\mops_core\MoPS_led.h'
11:20:47 11:20:47.432 DEBUG - CxxFileLinesVisitor: 'C:/slave/workspace/kai/mops_conf_d4_umops_v4_4700/mops_core/MoPS_led.h'
11:20:47 11:20:47.432 DEBUG -    lines:           '50'
11:20:47 11:20:47.432 DEBUG -    executableLines: '[]'
11:20:47 11:20:47.432 DEBUG -    linesOfCode:     '[]'
11:20:47 11:20:47.432 DEBUG -    linesOfComments: '[]'
11:20:47 11:20:47.434 DEBUG - global settings for: 'C:\slave\workspace\kai\mops_conf_d4_umops_v4_4700\mops_core\MoPS_lua.c'
11:20:47 11:20:47.434 DEBUG - Parse 'C:\slave\workspace\kai\mops_conf_d4_umops_v4_4700\mops_core\MoPS_lua.c' as C file, ends in '*.c'
11:20:47 11:20:47.606 ERROR - Unable to parse file: C:\slave\workspace\kai\mops_conf_d4_umops_v4_4700\mops_core\MoPS_lua.c
11:20:47 11:20:47.607 ERROR - Lexer error: Unable to lex url: file:/C:/slave/workspace/kai/mops_conf_d4_umops_v4_4700/mops_core/MoPS_lua.c
11:20:47 11:20:47.607 DEBUG - API File: MoPS_lua.c
11:20:47 11:20:47.607 DEBUG - Header file suffixes: [.hxx, .hpp, .hh, .h]
11:20:47 11:20:47.607 DEBUG - finished preprocessing 'C:\slave\workspace\kai\mops_conf_d4_umops_v4_4700\mops_core\MoPS_lua.c'
11:20:47 11:20:47.607 DEBUG - CxxFileLinesVisitor: 'C:/slave/workspace/kai/mops_conf_d4_umops_v4_4700/mops_core/MoPS_lua.c'
11:20:47 11:20:47.607 DEBUG -    lines:           '272'
11:20:47 11:20:47.607 DEBUG -    executableLines: '[]'
11:20:47 11:20:47.607 DEBUG -    linesOfCode:     '[]'
11:20:47 11:20:47.607 DEBUG -    linesOfComments: '[]'
11:20:47 11:20:47.608 DEBUG - global settings for: 'C:\slave\workspace\kai\mops_conf_d4_umops_v4_4700\mops_core\MoPS_lua.h'
11:20:47 11:20:47.608 DEBUG - Parse 'C:\slave\workspace\kai\mops_conf_d4_umops_v4_4700\mops_core\MoPS_lua.h' as C++ file
11:20:47 INFO: ------------------------------------------------------------------------
11:20:47 INFO: EXECUTION FAILURE
11:20:47 INFO: ------------------------------------------------------------------------
11:20:47 Total time: 11.502s
11:20:47 Final Memory: 24M/783M
11:20:47 INFO: ------------------------------------------------------------------------
11:20:47 ERROR: Error during Sonar runner execution
11:20:47 org.sonar.runner.impl.RunnerException: Unable to execute Sonar
11:20:47    at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
11:20:47    at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
11:20:47    at java.security.AccessController.doPrivileged(Native Method)
11:20:47    at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
11:20:47    at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
11:20:47    at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
11:20:47    at org.sonar.runner.api.Runner.execute(Runner.java:90)
11:20:47    at org.sonar.runner.Main.executeTask(Main.java:70)
11:20:47    at org.sonar.runner.Main.execute(Main.java:59)
11:20:47    at org.sonar.runner.Main.main(Main.java:41)
11:20:47 Caused by: org.sonar.squidbridge.api.AnalysisException: Unable to parse file: C:\slave\workspace\kai\mops_conf_d4_umops_v4_4700\mops_core\MoPS_lua.h
11:20:47    at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:105)
11:20:47    at org.sonar.cxx.sensors.squid.CxxSquidSensor.execute(CxxSquidSensor.java:185)
11:20:47    at org.sonar.batch.sensor.SensorWrapper.analyse(SensorWrapper.java:57)
11:20:47    at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
11:20:47    at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
11:20:47    at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
11:20:47    at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
11:20:47    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
11:20:47    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
11:20:47    at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
11:20:47    at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
11:20:47    at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
11:20:47    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
11:20:47    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
11:20:47    at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
11:20:47    at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
11:20:47    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
11:20:47    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
11:20:47    at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
11:20:47    at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
11:20:47    at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:79)
11:20:47    at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:45)
11:20:47    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:20:47    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:20:47    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:20:47    at java.lang.reflect.Method.invoke(Method.java:498)
11:20:47    at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
11:20:47    ... 9 more
11:20:47 Caused by: java.lang.StackOverflowError
11:20:47    at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
11:20:47    at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
11:20:47    at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
11:20:47    at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
11:20:47    at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
11:20:47    at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
11:20:47    at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
```
* cxx plugin version? 0.9.8
* SonarQube version? 5.6.6

**Comment by guwirth** [comment]
Hi @amitkumar2283, the program is crashing inside of  the scanner without more details:
```
at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:105)
at org.sonar.cxx.sensors.squid.CxxSquidSensor.execute(CxxSquidSensor.java:185)
```
Only possibilities I see are:
* try the C plugin if there is a difference
* try sonar.cxx.cFilesPatterns (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-configuration-properties#sonarcxxcfilespatterns)
* play around with the source file to narrow down the problem
* try to update to later versions of plugin & SQ
