### ISSUE TITLE
Problem with sonar.cxx.jsonCompilationDatabase when it includes testcode you don't want to scan

### ISSUE THREAD

**Issue by john-forrest** [SonarOpenCommunity/sonar-cxx#1474]
### Description

I tried experimenting with sonar.cxx.jsonCompilationDatabase, using the file I'd already generated to use with cppcheck - generated via cmake by adding -DCMAKE_EXPORT_COMPILE_COMMANDS=ON to the config call. I added sonar.cxx.scanOnlySpecifiedSources for good measure.

This does not work the way I expected it to. The cmake call, as I suspect many would do, includes the test code. However, I don't want to scan the test code (under test directory), so I only supply "-Dsonar.sources=src,include" to sonar-scanner. What I want to happen is that sonar-scanner ignores files outside these directories. What actually happened is I got an error along the lines of:

org.sonar.squidbridge.api.AnalysisException: Unable to analyze file: /home/jk-dockerslave/.jenkins/ws/dev***/test/unit-tests/validation/test-pressence-validator.cpp
	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:131)
	at org.sonar.cxx.sensors.squid.CxxSquidSensor.execute(CxxSquidSensor.java:164)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:302)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:297)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:271)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.NullPointerException: file can't be null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at org.sonar.api.batch.sensor.cpd.internal.DefaultCpdTokens.onFile(DefaultCpdTokens.java:58)
	at org.sonar.api.batch.sensor.cpd.internal.DefaultCpdTokens.onFile(DefaultCpdTokens.java:39)
	at org.sonar.cxx.sensors.visitors.CxxCpdVisitor.visitFile(CxxCpdVisitor.java:65)
	at com.sonar.sslr.impl.ast.AstWalker.walkAndVisit(AstWalker.java:67)
	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:110)
	... 33 more

I am assuming this is because the directory is not in the sources list. Is this a deliberate feature and have I missed an option?

* cxx plugin version? 0.9.9
* SonarQube version? 7.1.0

**Comment by ivangalkin** [comment]
Hi All,

I can confirm, that `sonar.sources` option is ignored once `sonar.cxx.scanOnlySpecifiedSources` was set. The question is: is it a bug or a feature?

Regards

**Comment by guwirth** [comment]
> I can confirm, that sonar.sources option is ignored once sonar.cxx.scanOnlySpecifiedSources was set. 

Not really sure if bug or feature? Think original idea was to scan with `sonar.cxx.scanOnlySpecifiedSources` only files which are listed in the JSONCompilationDatabase file and ignore all others. Think that on top this list is filtered with the `sonar.sources` settings was not a requirement.

I don't use the JSONCompilationDatabase: what would be better?

Please keep also in mind that JSON Compilation Database support is experimental only!

**Comment by john-forrest** [comment]
Personally I think it best to only scan files in sonar.sources, or perhaps if a file is given that is not in sonar.sources it is ignored (depending on what is easiest), but I guess that could be seen as a break to some and perhaps there should be another option?
