### ISSUE TITLE
java.lang.StackOverflowError during parse of source file

### ISSUE THREAD

**Issue by bjd** [SonarOpenCommunity/sonar-cxx#1516]
### Steps to reproduce the problem

source file `t.cpp`:
```
#include <sys/socket.h> 
#if !defined(MSG_NOSIGNAL) || (MSG_NOSIGNAL == 0)
#endif
```
sonar-project.properties:
```
sonar.projectKey = test:test
sonar.projectName = test
sonar.cxx.includeDirectories=/usr/include
sonar.sources = t.cpp
sonar.language = c++
sonar.host.url = http://sonar
```
Then run `sonar-scanner -X` 

This ends with a java stackoverflow exception:
```
16:46:10.589 INFO: ------------------------------------------------------------------------
16:46:10.589 INFO: EXECUTION FAILURE
16:46:10.589 INFO: ------------------------------------------------------------------------
16:46:10.589 INFO: Total time: 3.784s
16:46:10.637 INFO: Final Memory: 23M/544M
16:46:10.637 INFO: ------------------------------------------------------------------------
16:46:10.637 ERROR: Error during SonarQube Scanner execution
org.sonar.squidbridge.api.AnalysisException: Unable to parse file: /home/bdijkstra/test/t.cpp
	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:105)
	at org.sonar.cxx.sensors.squid.CxxSquidSensor.execute(CxxSquidSensor.java:173)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:312)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:307)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:281)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:81)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:132)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.StackOverflowError
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:55)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visitNonTerminal(LexerfulAstCreator.java:56)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.visit(LexerfulAstCreator.java:47)
	at org.sonar.sslr.internal.matchers.LexerfulAstCreator.create(LexerfulAstCreator.java:33)
	at com.sonar.sslr.impl.Parser.parse(Parser.java:84)
	at com.sonar.sslr.impl.Parser.parse(Parser.java:78)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalToInt(ExpressionEvaluator.java:62)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalLeaf(ExpressionEvaluator.java:100)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalToInt(ExpressionEvaluator.java:81)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalOneChildAst(ExpressionEvaluator.java:113)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalToInt(ExpressionEvaluator.java:83)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalToInt(ExpressionEvaluator.java:73)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalLeaf(ExpressionEvaluator.java:100)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalToInt(ExpressionEvaluator.java:81)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalOneChildAst(ExpressionEvaluator.java:113)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalToInt(ExpressionEvaluator.java:83)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalToInt(ExpressionEvaluator.java:73)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalLeaf(ExpressionEvaluator.java:100)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalToInt(ExpressionEvaluator.java:81)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalOneChildAst(ExpressionEvaluator.java:113)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalToInt(ExpressionEvaluator.java:83)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalToInt(ExpressionEvaluator.java:73)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalLeaf(ExpressionEvaluator.java:100)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalToInt(ExpressionEvaluator.java:81)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalOneChildAst(ExpressionEvaluator.java:113)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalToInt(ExpressionEvaluator.java:83)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalToInt(ExpressionEvaluator.java:73)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalLeaf(ExpressionEvaluator.java:100)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalToInt(ExpressionEvaluator.java:81)
	at org.sonar.cxx.preprocessor.ExpressionEvaluator.evalOneChildAst(ExpressionEvaluator.java:113)
...etc...
```

This was with:
* cxx plugin version 1.1.0
* SonarQube version 7.2
* Sonar Scanner 3.2.0.1227

I have not yet tested with other versions yet.

**Comment by bjd** [comment]
The `sys/socket.h ` header file declares an enum and creates a `#define` of the same name for each of the enum fields. For this overflow issue the relevant bit appears to be that there is a `#define` with name and value the same and then this name is used multiple times in an `#if` condition.

Further simplified source:
```
#define A A
#if A && A
#endif
```

**Comment by ivangalkin** [comment]
Hi @bjd!

thank you for the bug report and especially for the very precise test example. I confirm the bug in `ExpressionEvaluator` and will try to fix it.

Regards,

**Comment by ivangalkin** [comment]
Some details for the future fix: our `ExpressionEvaluator` doesn't support the so called [Self-Referential Macros](https://gcc.gnu.org/onlinedocs/gcc-3.0.1/cpp_3.html#SEC31).

examples like...

```C++
#define A A
#if A
#endif
```

and

```C++
#define B A
#define A B
#if A
#endif
```

and

```C++
#define C B
#define B C
#define A B
#if A
#endif
```

etc cause an infinite loop in `ExpressionEvaluator`.

* process `#if macro_id0` (`CxxPreprocessor.handleIfLine()`)
* evaluate `macro_id0` (`ExpressionEvaluator.eval()`)
* `macro_id0` is not a char/integer constant (`ExpressionEvaluator.evalLeaf()`)
* lookup `macro_id0` in the dictionary of parsed macros (`CxxPreprocessor.getMacro()`)`
* key `macro_id0` has been found
* recursively evaluate all `macro_id1`, `macro_id2`... `macro_idN`from the macro's body
* **MISSING**: return from recursion if any `macro_idX` was already placed on evaluation stack
