### ISSUE TITLE
[JOURNAL_FLUSHER] WARNING Journal flush operation took 3,010ms last 8 cycles average is 376ms

### ISSUE THREAD

**Issue by zyun823** [SonarOpenCommunity/sonar-cxx#1519]
When analyzing files within my C++ project, He always shows the following error.

'#include "GSPExtDataParser.h"      // for CGSPExtData, CGSPExtDataItem'
18:36:32 18:36:26.066 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 3,010ms last 8 cycles average is 376ms
18:40:20 18:40:14.198 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 2,156ms last 8 cycles average is 269ms
18:42:37 Exception in thread "CHECKPOINT_WRITER" Exception in thread "LOG_FLUSHER" java.lang.OutOfMemoryError: Java heap space
18:42:37 java.lang.OutOfMemoryError: Java heap space
18:42:37 	at java.util.ArrayList.iterator(ArrayList.java:840)
18:42:37 	at java.util.Collections$SynchronizedCollection.iterator(Collections.java:2031)
18:42:37 	at com.persistit.Persistit.pollAlertMonitors(Persistit.java:2285)
18:42:37 	at com.persistit.Persistit$LogFlusher.run(Persistit.java:192)
18:42:37 18:42:32.427 INFO: ------------------------------------------------------------------------
18:42:37 18:42:32.427 INFO: EXECUTION FAILURE
18:42:37 18:42:32.427 INFO: ------------------------------------------------------------------------
18:42:37 18:42:32.427 INFO: Total time: 13:03.711s
18:42:38 18:42:32.532 INFO: Final Memory: 31M/735M
18:42:38 18:42:32.532 INFO: ------------------------------------------------------------------------
18:42:38 18:42:32.532 ERROR: Error during SonarQube Scanner execution
18:42:38 org.sonar.squidbridge.api.AnalysisException: Unable to parse file: C:\jenkins\workspace\GCCP\TScanCode\GCCP_TScanCode(Python)\Trunk\ProductPlatform\Construction\Common\CommonCore\Source\GYS\GBQShareGrossRateUtils.cpp
18:42:38 	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:105)
18:42:38 	at org.sonar.cxx.sensors.squid.CxxSquidSensor.execute(CxxSquidSensor.java:173)
18:42:38 	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
18:42:38 	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)

18:29:34 18:29:28.740 INFO: SonarQube Scanner 3.2.0.1227
18:29:34 18:29:28.740 INFO: Java 1.8.0_172 Oracle Corporation (64-bit)
18:29:34 18:29:28.740 INFO: Windows 7 6.1 amd64
18:29:34 18:29:28.740 INFO: SONAR_SCANNER_OPTS=-Xms512m -Xmx1024m
C++ (Community) 1.1.0 (cxx)

**Comment by ivangalkin** [comment]
hi @zyun823,

does this error appeared after update from sonar-cxx 1.0.0 to sonar-cxx 1.1.0 ?

After some brief analysis I suspect, that the so called `Storage` of  sonar scanner runs out of memory (JVM heap). 

In the version 1.1.0 we introduced additional complexity metrics. These new (file/module etc) metrics, are persisted in the `org.sonar.scanner.storage.Storage`. So the more measurements are persisted, the more Java heap you need. Large files obviously require more storage, since they cause more quality metrics to be calculated. So one have to tune the JVM settings according to the analysed project.

Please if possible increase the max heap for the JVM and re-run the analysis. E.g. if you perform your analysis by means of sonar-scanner you can do something like that:
```BASH
export SONAR_SCANNER_OPTS=-Xms1024m\ -Xmx2048m
sonar-scanner -Dproject.settings=your_project.properties
```

**Comment by zyun823** [comment]
thx，He's a little better，but

[C:\jenkins\workspace\GCCP\TScanCode\GCCP_TScanCode(Python)\Trunk\ProductPlatform\Construction\Region\ShaanXi\ShaanXiGYS\Source\Bid\ServicePlugin\GBQShaanXiUpdateOwnerEBiddingFileServicePlugin.cpp:30]: cannot find the sources for '#include "GNDBIntf.h"'
17:34:21 17:34:17.924 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 3,231ms last 8 cycles average is 403ms
17:39:30 17:39:17.464 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 3,295ms last 8 cycles average is 411ms
17:44:37 17:44:04.991 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 9,759ms last 8 cycles average is 1,631ms
17:48:01 17:47:54.546 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 19,288ms last 8 cycles average is 4,042ms
17:51:37 17:51:15.854 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 6,820ms last 8 cycles average is 4,895ms
17:54:09 17:54:01.056 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 29,342ms last 8 cycles average is 4,520ms
17:56:19 17:56:07.559 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 3,273ms last 8 cycles average is 409ms
17:58:51 17:58:46.147 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 3,218ms last 8 cycles average is 402ms
18:01:05 18:00:52.837 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 3,236ms last 8 cycles average is 806ms
18:02:31 18:02:22.744 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 3,219ms last 8 cycles average is 1,209ms
18:05:19 18:05:07.435 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 9,666ms last 8 cycles average is 2,417ms
18:07:16 18:07:00.419 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 9,709ms last 8 cycles average is 3,228ms
18:09:03 18:08:53.911 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 6,589ms last 8 cycles average is 3,648ms
18:11:00 18:10:51.474 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 17,092ms last 8 cycles average is 5,382ms
18:11:58 18:11:52.578 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 6,350ms last 8 cycles average is 6,176ms
18:13:19 18:13:00.925 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 6,437ms last 8 cycles average is 5,772ms
18:15:38 18:15:26.315 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 12,836ms last 8 cycles average is 6,163ms
18:17:51 18:17:38.831 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 6,446ms last 8 cycles average is 805ms
18:19:31 18:19:22.336 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 3,258ms last 8 cycles average is 407ms
18:22:16 18:22:04.346 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 12,885ms last 8 cycles average is 2,017ms
18:23:54 18:23:44.870 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 3,227ms last 8 cycles average is 403ms
18:26:09 18:26:00.379 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 3,226ms last 8 cycles average is 806ms
18:28:05 18:27:55.802 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 3,270ms last 8 cycles average is 812ms
18:29:48 18:29:38.970 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 3,394ms last 8 cycles average is 1,236ms
18:31:54 18:31:42.041 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 19,314ms last 8 cycles average is 3,650ms


`**SONAR_SCANNER_OPTS=-Xms4096m -Xmx5120m**`

**Comment by rompic** [comment]
I also ran into this and had to downgrade. alternatively I guess I would have to find a beefier pc.

**Comment by ivangalkin** [comment]
Hi @rompic, we already done some changes, which will decrease the required Java Heap. The heap size of versions > 1.1.0 is still higher than before because of the larger number of quality metrics. If you are running sonar analysis by means of sonar-scanner  please consider to increase the heap size like that:

```BASH
export SONAR_SCANNER_OPTS=-Xms<min_heap_size_Mb>m\ -Xmx<max_heap_size_Mb>m
sonar-scanner -Dproject.settings=your_project.properties
```

The min and max heap sizes are very project specific, so please use trial and error approach to find them out.
