### ISSUE TITLE
Not able to launch SonarQube5.6.7 on Windows 7 64bit

### ISSUE THREAD

**Issue by savithap15** [SonarOpenCommunity/sonar-cxx#1542]
Hi,

When i tried running "StartSonar.bat" for Windows64bit am getting below error message:-

SonarQube5.6.7v
==================================================================

--> Wrapper Started as Console
Launching a JVM...
Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
  Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.

WARNING - Unable to load the Wrapper's native library 'wrapper.dll'.
          The file is located on the path at the following location but
          could not be loaded:
            C:\PROJECT\SonarQube\sonarqube-5.6.7_InUse\sonarqube-5.6.7\bin\windows-x86-64\.\lib\wrapper.dll
          Please verify that the file is readable by the current user
          and that the file has not been corrupted in any way.
          One common cause of this problem is running a 32-bit version
          of the Wrapper with a 64-bit version of Java, or vica versa.
          This is a 32-bit JVM.
          Reported cause:
            C:\PROJECT\SonarQube\sonarqube-5.6.7_InUse\sonarqube-5.6.7\bin\windows-x86-64\lib\wrapper.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform
          System signals will not be handled correctly.

2018.08.17 15:28:28 INFO  app[o.s.a.AppFileSystem] Cleaning or creating temp directory C:\PROJECT\SonarQube\sonarqube-5.6.7_InUse\sonarqube-5.6.7\temp
2018.08.17 15:28:29 INFO  app[o.s.p.m.JavaProcessLauncher] Launch process[es]: C:\Program Files (x86)\jre1.8.0_152\jre1.8.0_152\bin\java -Djava.awt.headless=true -Xmx1G -Xms256m -Xss256k -Djava.net.preferIPv4Stack=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=C:\PROJECT\SonarQube\sonarqube-5.6.7_InUse\sonarqube-5.6.7\temp -javaagent:C:\Program Files (x86)\jre1.8.0_152\jre1.8.0_152\lib\management-agent.jar -cp ./lib/common/*;./lib/search/* org.sonar.search.SearchServer C:\PROJECT\SonarQube\sonarqube-5.6.7_InUse\sonarqube-5.6.7\temp\sq-process4917606404783066266properties
2018.08.17 15:28:30 INFO   es[o.s.p.ProcessEntryPoint]  Starting es
2018.08.17 15:28:30 INFO   es[o.s.s.EsSettings]  Elasticsearch listening on 127.0.0.1:9001
2018.08.17 15:28:31 INFO   es[o.elasticsearch.node]  [sonar-1534499908827] version[1.7.5], pid[16408], build[00f95f4/2016-02-02T09:55:30Z]
2018.08.17 15:28:31 INFO   es[o.elasticsearch.node]  [sonar-1534499908827] initializing ...
2018.08.17 15:28:31 INFO   es[o.e.plugins]  [sonar-1534499908827] loaded [], sites []
2018.08.17 15:28:32 INFO   es[o.elasticsearch.env]  [sonar-1534499908827] using [1] data paths, mounts [[System (C:)]], net usable_space [46.8gb], net total_space [237.9gb], types [NTFS]
2018.08.17 15:28:33 WARN   es[o.e.bootstrap]  JNA not found. native methods will be disabled.
2018.08.17 15:28:33 INFO   es[o.elasticsearch.node]  [sonar-1534499908827] initialized
2018.08.17 15:28:33 INFO   es[o.elasticsearch.node]  [sonar-1534499908827] starting ...
2018.08.17 15:28:33 WARN   es[o.s.p.ProcessEntryPoint]  Fail to start es
org.elasticsearch.transport.BindTransportException: Failed to bind to [9001]
	at org.elasticsearch.transport.netty.NettyTransport.bindServerBootstrap(NettyTransport.java:422) ~[elasticsearch-1.7.5.jar:na]
	at org.elasticsearch.transport.netty.NettyTransport.doStart(NettyTransport.java:283) ~[elasticsearch-1.7.5.jar:na]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:85) ~[elasticsearch-1.7.5.jar:na]
	at org.elasticsearch.transport.TransportService.doStart(TransportService.java:153) ~[elasticsearch-1.7.5.jar:na]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:85) ~[elasticsearch-1.7.5.jar:na]
	at org.elasticsearch.node.internal.InternalNode.start(InternalNode.java:257) ~[elasticsearch-1.7.5.jar:na]
	at org.sonar.search.SearchServer.start(SearchServer.java:46) [sonar-search-5.6.7.jar:na]
	at org.sonar.process.ProcessEntryPoint.launch(ProcessEntryPoint.java:102) ~[sonar-process-5.6.7.jar:na]
	at org.sonar.search.SearchServer.main(SearchServer.java:81) [sonar-search-5.6.7.jar:na]
Caused by: org.elasticsearch.common.netty.channel.ChannelException: Failed to bind to: /127.0.0.1:9001
	at org.elasticsearch.common.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272) ~[elasticsearch-1.7.5.jar:na]
	at org.elasticsearch.transport.netty.NettyTransport$1.onPortNumber(NettyTransport.java:413) ~[elasticsearch-1.7.5.jar:na]
	at org.elasticsearch.common.transport.PortsRange.iterate(PortsRange.java:58) ~[elasticsearch-1.7.5.jar:na]
	at org.elasticsearch.transport.netty.NettyTransport.bindServerBootstrap(NettyTransport.java:409) ~[elasticsearch-1.7.5.jar:na]
	... 8 common frames omitted
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.Net.bind(Unknown Source) ~[na:1.8.0_152]
	at sun.nio.ch.Net.bind(Unknown Source) ~[na:1.8.0_152]
	at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source) ~[na:1.8.0_152]
	at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source) ~[na:1.8.0_152]
	at org.elasticsearch.common.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193) ~[elasticsearch-1.7.5.jar:na]
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391) ~[elasticsearch-1.7.5.jar:na]
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315) ~[elasticsearch-1.7.5.jar:na]
	at org.elasticsearch.common.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42) ~[elasticsearch-1.7.5.jar:na]
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[elasticsearch-1.7.5.jar:na]
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[elasticsearch-1.7.5.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_152]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_152]
2018.08.17 15:28:33 INFO   es[o.elasticsearch.node]  [sonar-1534499908827] stopping ...
2018.08.17 15:28:33 INFO   es[o.elasticsearch.node]  [sonar-1534499908827] stopped
2018.08.17 15:28:33 INFO   es[o.elasticsearch.node]  [sonar-1534499908827] closing ...
2018.08.17 15:28:33 INFO   es[o.elasticsearch.node]  [sonar-1534499908827] closed
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
<-- Wrapper Stopped

**Comment by guwirth** [comment]
Hi @savithap15,

for general SQ issues your are in the wrong community, think you should try it here: https://community.sonarsource.com/

Regards,

**Comment by savithap15** [comment]
Tysm for redirecting me to the correct forum.
