### ISSUE TITLE
CxxCompilerVcSensor fails if filenames in log file appear in lowercase

### ISSUE THREAD

**Issue by kmteam** [SonarOpenCommunity/sonar-cxx#1678]
Description:
The CxxCompilerVcSensor fails to get warning information from the Visual Studio .log file because filenames in the log file are lowercase, and files might contain UpperCase letters in the directory.

Working with 
- sonar-scanner 3.2.0.1227
- sonar-cxx version 1.2.1

Ex:
sonar.cxx.vc.regex=(.*>)?(?<file>.*)\\((?<line>\\d+)\\):\\x20warning\\x20(?<id>C\\d+):(?<message>.*)
Line in the .Log file:     1>c:\proyectos nuevos desarrollos\atria capture projects\vs17\utils\reconengine2\codmaker1_codificator.cpp(12): warning C26495: Variable 'CodMaker1_Codificator::_CodVersion' is uninitialized. Always initialize a member variable (type.6).
Real filename=CodMaker1_Codificator.cpp

Output messages:
INFO: Sensor C++ (Community) CxxCompilerVcSensor [cxx]
INFO: Searching reports by relative path with basedir 'C:\Proyectos Nuevos Desarrollos\Atria Capture Projects\VS17\Utils\ReconEngine2' and search prop 'sonar.cxx.vc.reportPath'
INFO: Parser will parse '1' report file(s)
INFO: Processing report 'C:\Proyectos Nuevos Desarrollos\Atria Capture Projects\VS17\Utils\ReconEngine2\Win32\Release\ReconEngine2.log'
INFO: Parsing 'Visual C++' initialized with report 'C:\Proyectos Nuevos Desarrollos\Atria Capture Projects\VS17\Utils\ReconEngine2\Win32\Release\ReconEngine2.log', Charset= 'UTF-8'
INFO: Using pattern : '(.*>)?(?<file>.*)\((?<line>\d+)\):\x20warning\x20(?<id>C\d+):(?<message>.*)'
WARN: Cannot find the file 'c:\proyectos nuevos desarrollos\atria capture projects\vs17\utils\reconengine2\codmaker1_codificator.cpp' in module 'ReconEngine2' base dir 'C:\Proyectos Nuevos Desarrollos\Atria Capture Projects\VS17\Utils\ReconEngine2', skipping violations.

Thank you!

**Comment by ivangalkin** [comment]
hi @kmteam and thank you for reaching out,

this issue was recent fixed by means of #1653 
please use the following link https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts in order to download and test the latest snapshot

@guwirth  this issue is duplication of #1651

**Comment by guwirth** [comment]
@kmteam please try and give us feedback.

**Comment by kmteam** [comment]
Thank you guwirth,

It "almost" worked. Somehow, it crashed processing one file:

`INFO: Processing report 'C:\Proyectos Nuevos Desarrollos\Atria Capture Projects\VS17\Utils\ReconEngine2\Win32\Release\ReconEngine2.log'
INFO: Parsing 'Visual C++' initialized with report 'C:\Proyectos Nuevos Desarrollos\Atria Capture Projects\VS17\Utils\ReconEngine2\Win32\Release\ReconEngine2.log', Charset= 'UTF-8'
INFO: Using pattern : '(.*>)?(?<file>.*)\((?<line>\d+)\):\x20warning\x20(?<id>C\d+):(?<message>.*)'
WARN: Cannot find the file '         FingerprintsCollection.cpp' in module 'ReconEngine2' base dir 'C:\Proyectos Nuevos Desarrollos\Atria Capture Projects\VS17\Utils\ReconEngine2', skipping violations.
ERROR: processReport Exception: C:\Proyectos Nuevos Desarrollos\Atria Capture Projects\VS17\Utils\ReconEngine2\Win32\Release\ReconEngine2.log - not processed '{}'
java.nio.file.InvalidPathException: Illegal char <:> at index 10:          c:\proyectos nuevos desarrollos\atria capture projects\vs17\utils\reconengine2\codmaker1_codificator.cpp
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
        at org.sonar.cxx.sensors.utils.CxxIssuesReportSensor.getInputFileTryRealPath(CxxIssuesReportSensor.java:142)
        at org.sonar.cxx.sensors.utils.CxxIssuesReportSensor.getInputFileIfInProject(CxxIssuesReportSensor.java:200)
        at org.sonar.cxx.sensors.utils.CxxIssuesReportSensor.createNewIssueLocationFile(CxxIssuesReportSensor.java:234)
        at org.sonar.cxx.sensors.utils.CxxIssuesReportSensor.saveViolation(CxxIssuesReportSensor.java:259)
        at org.sonar.cxx.sensors.utils.CxxIssuesReportSensor.saveUniqueViolation(CxxIssuesReportSensor.java:137)
        at org.sonar.cxx.sensors.compiler.CxxCompilerSensor.processReport(CxxCompilerSensor.java:73)
        at org.sonar.cxx.sensors.utils.CxxIssuesReportSensor.executeReport(CxxIssuesReportSensor.java:219)
        at org.sonar.cxx.sensors.utils.CxxIssuesReportSensor.execute(CxxIssuesReportSensor.java:93)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:45)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:88)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:62)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:74)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:164)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:319)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:314)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:288)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:82)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:131)
        at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)

INFO: CXX-COMPILER-VC processed = 9
INFO: Sensor C++ (Community) CxxCompilerVcSensor [cxx] (done) | time=1111ms`

**Comment by ivangalkin** [comment]
hi @kmteam,

thank you for testing. 

we tried to deal with the fact, that the normalization of [windows] paths (see `Path.toRealPath()`) might throw an exception. In such cases we shouldn't not terminate the analysis, because the normalization is more or less optional. Unfortunately not all possible exceptions were coughs. I've extended the code (see #1679).

W.r.t. to the original cause: I don't really know what it might be. We don't perform any URI-to-Path conversions (which seems to be a popular cause), so it might be the JVM/JRE issue.

@kmteam @guwirth 

```
WARN: Cannot find the file ' FingerprintsCollection.cpp' in module 'ReconEngine2' base dir...
```

I am surprised, that ` FingerprintsCollection.cpp` doesn't contain any path but only a file name. The leading space is also suspicious. Is it possible, that the regexp is not able to extract to correct path? @kmteam could you please name the full path how it appears in the ReconEngine2.log? Thank you.

**Comment by kmteam** [comment]
Thanks ivangalkin,

Aparently the regexp is working just fine:
https://regex101.com/r/M1l3K3/1

I tried with both full paths/just filenames in the log report, and the error is similar:

```
INFO: Parser will parse '1' report file(s)
INFO: Processing report '{...}\Win32\Release\ReconEngine2.log'
INFO: Parsing 'Visual C++' initialized with report '{...}Win32\Release\ReconEngine2.log', Charset= 'UTF-8'
INFO: Using pattern : '(.*>)?(?<file>.*)\((?<line>\d+)\):\x20warning\x20(?<id>C\d+):(?<message>.*)'
ERROR: processReport Exception: C:\Proyectos Nuevos Desarrollos\Atria Capture Projects\VS17\Utils\ReconEngine2\Win32\Release\ReconEngine2.log - not processed '{}'
java.nio.file.InvalidPathException: Illegal char <:> at index 10:          c:\proyectos nuevos desarrollos\atria capture projects\vs17\utils\reconengine2\fingerprintscollection.cpp
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
```

**Comment by rudolfgrauberger** [comment]
Hi kmteam,

> Aparently the regexp is working just fine:

Please try the following regular expression:

```properties
sonar.cxx.vc.regex=(.*>)?\\x20*(?<file>.*)\\((?<line>\\d+)\\):\\x20warning\\x20(?<id>C\\d+):(?<message>.*)
```
With your regular expression, the spaces before the path are not extracted ([your regex](https://regex101.com/r/gM1fWD/1) and [my regex](https://regex101.com/r/DfMpg1/1)).


Is it possible to get your log file and properties file?

**Comment by kmteam** [comment]
Thank you rudolf!
With your regexp it's working.

I'm attaching the log and the props file.

Regards,
[sonar-project.zip](https://github.com/SonarOpenCommunity/sonar-cxx/files/2811628/sonar-project.zip)
[ReconEngine2.zip](https://github.com/SonarOpenCommunity/sonar-cxx/files/2811629/ReconEngine2.zip)

**Comment by ivangalkin** [comment]
@rudolfgrauberger  @guwirth looks like we have to update our default regexp to the one, @rudolfgrauberger suggested.

BTW shouldn't we use `\\s` (any whitespace) instead of just `\\x20` (just a space ` `)? This makes the expression more robust IMHO. It's about the part @rudolfgrauberger added and all the remaining appearance of `\\x20`

regards,

**Comment by guwirth** [comment]
> BTW shouldn't we use \\s (any whitespace) instead of just \\x20 (just a space )? This makes the expression more robust IMHO. It's about the part @rudolfgrauberger added and all the remaining appearance of \\x20

@rudolfgrauberger think makes sense to improve it. I’m looking forward to your PR...

**Comment by rudolfgrauberger** [comment]
@guwirth How can I make a PR to the wiki? I don't see the documentation in my fork... How exactly is the process for this?
