### ISSUE TITLE
SonarQube C++ plugin (Community) not working with SonarQube 7.7

### ISSUE THREAD

**Issue by br-rhrbacek** [SonarOpenCommunity/sonar-cxx#1696]
### Description

After updating to SonarQube 7.7, SonarQube C++ plugin (Community) stopped working.

### LOG file

```
java.lang.UnsupportedOperationException: Metric 'files' should not be computed by a Sensor
        at org.sonar.scanner.sensor.DefaultSensorStorage.saveMeasure(DefaultSensorStorage.java:168)
        at org.sonar.scanner.sensor.DefaultSensorStorage.store(DefaultSensorStorage.java:132)
        at org.sonar.api.batch.sensor.measure.internal.DefaultMeasure.doSave(DefaultMeasure.java:95)
        at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:45)
        at org.sonar.cxx.sensors.squid.CxxSquidSensor.saveMeasures(CxxSquidSensor.java:239)
        at org.sonar.cxx.sensors.squid.CxxSquidSensor.save(CxxSquidSensor.java:224)
        at org.sonar.cxx.sensors.squid.CxxSquidSensor.execute(CxxSquidSensor.java:160)
        at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:359)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:354)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:317)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:128)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

### Related information

* cxx plugin version 1.2.2
* SonarQube version 7.7
* files metric was removed from ScannerMetrics in SQ 7.7 (https://github.com/SonarSource/sonarqube/commit/f6b2a269c44043f1c230b646dbb8662aed3fa5a4#diff-958438b627eede67724e05feb7d35e69)

**Comment by guwirth** [comment]
Hi @br-rhrbacek,

cxx 1.2.2 is not released for SQ 7.7. They did some changes, see #1695.

You can download and try:
https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/builds/23281379/artifacts

Regards,

**Comment by br-rhrbacek** [comment]
Hi @guwirth,

Thank you, now everything works again.

**Comment by guwirth** [comment]
closed with #1695

**Comment by palace2001** [comment]
Thanks @guwirth ,
It's good for me!

**Comment by SvyatoslavRazmyslov** [comment]
Hi @guwirth ,
When are you going to release the SonarCXX 1.3 with fixes?
