### ISSUE TITLE
NoClassDefFoundError when run cxx-lint

### ISSUE THREAD

**Issue by ghking1** [SonarOpenCommunity/sonar-cxx#1715]
### Description
NoClassDefFoundError when run cxx-lint, even if I added guava library.

### Steps to reproduce the problem
run command:
```
R:\>java -jar ./cxx-lint-1.2.2.1653.jar -f ./test.cpp
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Maps
        at org.sonar.squidbridge.checks.AbstractOneStatementPerLineCheck.<init>(AbstractOneStatementPerLineCheck.java:31)
        at org.sonar.cxx.checks.metrics.TooManyStatementsPerLineCheck.<init>(TooManyStatementsPerLineCheck.java:45)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.sonar.cxx.cxxlint.CxxLint.main(CxxLint.java:186)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Maps
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 8 more
```

### LOG file
![捕获](https://user-images.githubusercontent.com/8264304/57179951-25df3880-6eb6-11e9-8aff-c770594b6380.JPG)

### Related information

* cxx plugin version: 1.2.2.1653
* SonarQube version: 6.7
* java-jdk version: 1.8.0_191

**Comment by guwirth** [comment]
Hi @ghking1,

this tool is seldom in use. Please try latest snapshot from here: https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts.

General question: Why do you wanna use it? The cxx plugin provides less (no) own static code analysis. With future versions we will remove it completely.
 
Regards,

**Comment by ghking1** [comment]
@guwirth 
I just follow the wiki: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Running-cxx-plugin-before-committing-code
the latest one has the same problem from https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts
if I don't use it, what should I use?

Thank you!

**Comment by guwirth** [comment]
Hello @ghking1,

if the plugin provides no own static code analysis checks it makes no sense to run a local tool. Main intention of the cxx plugin is to read/import reports from other tools. In the past the idea was to create own checks (like e.g. Java plugin). But effort for reinventing the wheel is too high. Use tools like CppCheck, Clang, .... instead.

Regards,

**Comment by ghking1** [comment]
Thank you!
