### ISSUE TITLE
Metric 'files' should not be computed by a Sensor

### ISSUE THREAD

**Issue by fedecaccia** [SonarOpenCommunity/sonar-cxx#1729]
### Description

Running sonar-scanner with a c++ project I get the following error:

    ERROR: Error during SonarQube Scanner execution
    java.lang.UnsupportedOperationException: Metric 'files' should not be computed by a Sensor
    	at org.sonar.scanner.sensor.DefaultSensorStorage.saveMeasure(DefaultSensorStorage.java:168)
    	at org.sonar.scanner.sensor.DefaultSensorStorage.store(DefaultSensorStorage.java:132)
    	at org.sonar.api.batch.sensor.measure.internal.DefaultMeasure.doSave(DefaultMeasure.java:95)
    	at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:45)
    	at org.sonar.cxx.sensors.squid.CxxSquidSensor.saveMeasures(CxxSquidSensor.java:239)
    	at org.sonar.cxx.sensors.squid.CxxSquidSensor.save(CxxSquidSensor.java:224)
    	at org.sonar.cxx.sensors.squid.CxxSquidSensor.execute(CxxSquidSensor.java:160)
    	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
    	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
    	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
    	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
    	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
    	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
    	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
    	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
    	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:400)
    	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:395)
    	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
    	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
    	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
    	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
    	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
    	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
    	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
    	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
    	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
    	at com.sun.proxy.$Proxy0.execute(Unknown Source)
    	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
    	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
    	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
    	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
    	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

### Related information

* cxx plugin version? 1.2.2.1653
* sonar-scanner version 4.0.0.1744
* SonarQube version? 7.9

**Comment by fedecaccia** [comment]
Solved using plugin from https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/builds/23281379/artifacts as mentioned in #1696

**Comment by mittaltripti** [comment]
I am using SonarQube Community version 7.9.4 LTS and sonar-scanner-cli-4.4.0.2170 with sonar-c-plugin-1.3.2.1853.jar and sonar-cxx-plugin-1.3.2.1853.jar

I am getting following error :
09:32:52.500 ERROR: Error during SonarScanner execution
java.lang.UnsupportedOperationException: Unknown metric: CXX-PUBLIC_API
        at org.sonar.scanner.sensor.DefaultSensorStorage.saveMeasure(DefaultSensorStorage.java:159)
        at org.sonar.scanner.sensor.DefaultSensorStorage.store(DefaultSensorStorage.java:132)
        at org.sonar.api.batch.sensor.measure.internal.DefaultMeasure.doSave(DefaultMeasure.java:95)
        at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:45)
        at org.sonar.cxx.sensors.squid.CxxSquidSensor.saveMeasures(CxxSquidSensor.java:269)
        at org.sonar.cxx.sensors.squid.CxxSquidSensor.save(CxxSquidSensor.java:229)
        at org.sonar.cxx.sensors.squid.CxxSquidSensor.execute(CxxSquidSensor.java:165)
        at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:400)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:395)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
