### ISSUE TITLE
sonar-scanner - java.lang.IllegalStateException: The field 'createLineViolation' 

### ISSUE THREAD

**Issue by andersoncruz** [SonarOpenCommunity/sonar-cxx#1771]
I'm running Sonarqube 5.6.6 with Cxx plugin 0.9.8 and after perform a scan I receive this error message:

15:02:49.009 INFO: SonarQube Scanner 4.2.0.1873                                                                                                                                                15:02:49.009 INFO: Java 11.0.2 Oracle Corporation (64-bit)                                                                                                                                     15:02:49.009 INFO: Windows 10 10.0 amd64
15:02:52.784 INFO: Load active rules (done) | time=734ms
15:02:52.816 INFO: Publish mode
15:02:52.816 DEBUG: Start recursive analysis of project modules
15:02:52.817 INFO: Scan componentExample-test
15:02:52.934 INFO: Load server rules
15:02:53.182 DEBUG: GET 200 http://x.x.x.x:9000/api/rules/list.protobuf | time=248ms
15:02:53.220 INFO: Load server rules (done) | time=286ms
15:02:53.355 DEBUG: Initializers :
15:02:53.355 INFO: Base dir: C:\componentexample
15:02:53.355 INFO: Working dir: C:\componentexample\.scannerwork
15:02:53.358 INFO: Source paths: definition, design, specification, test
15:02:53.358 INFO: Source encoding: UTF-8, default locale: en_US
15:02:53.359 INFO: Index files
15:02:53.363 DEBUG: Declared extensions of language C# were converted to sonar.lang.patterns.cs : **/*.cs
15:02:53.363 DEBUG: Declared extensions of language c++ were converted to sonar.lang.patterns.c++ : **/*.cxx,**/*.cpp,**/*.cc,**/*.c,**/*.hxx,**/*.hpp,**/*.hh,**/*.h
15:02:53.363 DEBUG: Declared extensions of language c were converted to sonar.lang.patterns.c : **/*.c,**/*.h
15:02:53.363 DEBUG: Declared extensions of language C++ were converted to sonar.lang.patterns.cpp : **/*.x
15:02:53.363 DEBUG: Declared extensions of language Objective-C were converted to sonar.lang.patterns.objc : **/*.m
15:02:53.363 DEBUG: Declared extensions of language Java were converted to sonar.lang.patterns.java : **/*.java,**/*.jav
15:02:53.363 DEBUG: Declared extensions of language TypeScript were converted to sonar.lang.patterns.ts : **/*.ts,**/*.tsx
15:02:53.364 DEBUG: Declared extensions of language Ruby were converted to sonar.lang.patterns.ruby : **/*.rb
15:02:53.412 DEBUG: Language of file 'definition/src/mock/cpp/MockActivityRuleExecutor.cpp' is detected to be 'c++'
15:02:53.414 DEBUG: Language of file 'definition/src/mock/cpp/MockActivityRuleExecutor.hpp' is detected to be 'c++'
15:02:53.415 DEBUG: Language of file 'definition/src/mock/cpp/MockTransportObjects.cpp' is detected to be 'c++'
15:02:53.417 DEBUG: Language of file 'definition/src/mock/cpp/MockTransportObjects.hpp' is detected to be 'c++'
15:02:53.423 DEBUG: Language of file 'definition/src/mock/ruby/ActivityRuleExecutor.rb' is detected to be 'ruby'
15:02:53.461 DEBUG: Language of file 'definition/src/mock/ruby/ActivityRuleExecutor_TransportObjects.rb' is detected to be 'ruby'
15:02:53.483 DEBUG: Language of file 'definition/src/test/cpp/cppUnitTestRunner.cpp' is detected to be 'c++'
15:02:53.505 DEBUG: Language of file 'definition/target/dependency/main/cpp/cppUnitTestRunner.cpp' is detected to be 'c++'
15:02:53.669 DEBUG: Language of file 'definition/target/test-nar/EnvironmentMake_definition-0.0.1-SNAPSHOT-noarch/main/cpp/cppUnitTestRunner.cpp' is detected to be 'c++'
15:02:53.756 DEBUG: Language of file 'definition/target/unpackage/EnvironmentMake_definition-0.0.1-SNAPSHOT-noarch/main/cpp/cppUnitTestRunner.cpp' is detected to be 'c++'
15:02:53.863 DEBUG: Language of file 'design/src/main/cpp/Mapping/Mapping.cpp' is detected to be 'c++'
15:02:53.864 DEBUG: Language of file 'design/src/main/cpp/Mapping/MappingTable/LookupTableBase.cpp' is detected to be 'c++'
15:02:53.869 DEBUG: Language of file 'design/src/main/interface/API/Mapping/Mapping.hpp' is detected to be 'c++'
15:02:53.871 DEBUG: Language of file 'design/src/main/interface/API/Mapping/MappingTable/LookupTable.hpp' is detected to be 'c++'
15:02:53.872 DEBUG: Language of file 'design/src/main/interface/API/Mapping/MappingTable/LookupTableBase.hpp' is detected to be 'c++'
15:02:53.911 DEBUG: Language of file 'design/src/test/cpp/cppUnitTestRunner.cpp' is detected to be 'c++'
15:02:53.915 DEBUG: Language of file 'design/src/unittest/cpp/Mapping/MappingDefinition.cpp' is detected to be 'c++'
15:02:53.916 DEBUG: Language of file 'design/src/unittest/cpp/Mapping/MappingDefinition.hpp' is detected to be 'c++'
15:02:53.917 DEBUG: Language of file 'design/src/unittest/cpp/Mapping/MappingTest.cpp' is detected to be 'c++'
15:02:54.563 INFO: 19 files indexed
15:02:54.590 INFO: Quality profile for c++: Sonar way
15:02:54.590 INFO: Quality profile for ruby: Sonar Way
15:02:54.596 DEBUG: Code colorizer, supported languages: ruby
15:02:54.840 INFO: ------------------------------------------------------------------------
15:02:54.840 INFO: EXECUTION FAILURE
15:02:54.840 INFO: ------------------------------------------------------------------------
15:02:54.840 INFO: Total time: 5.884s
15:02:54.866 INFO: Final Memory: 11M/47M
15:02:54.866 INFO: ------------------------------------------------------------------------
15:02:54.866 ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: The field 'createLineViolation' does not exist or is not annotated with @RuleProperty in the class com.sonar.cpp.C.E.D
        at org.sonar.api.batch.rule.Checks.configureFields(Checks.java:179)
        at org.sonar.api.batch.rule.Checks.instantiate(Checks.java:163)
        at org.sonar.api.batch.rule.Checks.addAnnotatedChecks(Checks.java:137)
        at com.sonar.cpp.plugin.C.<init>(na:206)
        at com.sonar.cpp.plugin.B.<init>(na:2977)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:145)
        at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:342)
        at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
        at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
        at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
        at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
        at org.picocontainer.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:606)
        at org.picocontainer.DefaultPicoContainer.getComponents(DefaultPicoContainer.java:587)
        at org.sonar.core.platform.ComponentContainer.getComponentsByType(ComponentContainer.java:281)
        at org.sonar.batch.bootstrap.BatchExtensionDictionnary.completeBatchExtensions(BatchExtensionDictionnary.java:134)
        at org.sonar.batch.bootstrap.BatchExtensionDictionnary.getExtensions(BatchExtensionDictionnary.java:128)
        at org.sonar.batch.bootstrap.BatchExtensionDictionnary.getFilteredExtensions(BatchExtensionDictionnary.java:107)
        at org.sonar.batch.bootstrap.BatchExtensionDictionnary.select(BatchExtensionDictionnary.java:74)
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:46)
        at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
        at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:79)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)

I know it's an old version, but I need to do this before upgrade to LTS Sonar.

Any thought on what's happening here ?

**Comment by guwirth** [comment]
Hello @andersoncruz,

SQ 5.6 LTS is an older version. What I see from the exception stack trace is that something inside of `Checks` seems to fail.
```
java.lang.IllegalStateException: The field 'createLineViolation' does not exist or is not annotated with @RuleProperty in the class com.sonar.cpp.C.E.D
```
Searching for `createLineViolation` this is in current version only in `TabCharacterCheck`? There have been more checks in older versions. But maybe it helps to turn some of the checks of and run it again.
* https://github.com/SonarOpenCommunity/sonar-cxx/search?q=createLineViolation&unscoped_q=createLineViolation
* https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/file/TabCharacterCheck.java

Regards,

**Comment by andersoncruz** [comment]
Thanks for the feedback, we decided to move on towards to 6.7.7 LTS . Already been migrated and working with all our legacy projects ( for now ).

After some stability moment we will move again to 7.x LTS to take advantage of new resources and plugins.
