### ISSUE TITLE
pclint Format failed 

### ISSUE THREAD

**Issue by guchenghao8744** [SonarOpenCommunity/sonar-cxx#1953]
I want to output pclint report. but  Format failed. 
pclint version  : 9.0

**Comment by guchenghao8744** [comment]
I want to output pclint report. but  Format failed. 


My report like this:
--- Module:   filea.cpp (C++)
    _
    };
filea.cpp  8  Warning 601: No explicit type for symbol 'X::s', int assumed
filea.cpp  8  Error 10: Expecting ';'
<results>
<issue file ="filea.cpp" line = "6" number = "1527" desc = "static member 'X::a' (line 6, file filea.cpp) not defined"/>
</results>

**Comment by guchenghao8744** [comment]
I try to format the output like this:
Lint-nt  filea.cpp env-vc9.lnt -v -width(0,0^) +xml(results^) -"format=<issue file =\q%%f\q line = \q%%l\q number = \q%%n\q desc = \q%%m\q/>" -"format_specific= " -hFs1 -e900>Pclint_report.xml

**Comment by guchenghao8744** [comment]
INFO: Processing report 'F:\ewtrb_project\zed_bsk\pclint_report.xml'
ERROR: Cannot feed the data into sonar, details: 'com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '-' (code 45) in prolog; expected '<'
 at [row,col {unknown-source}]: [2,1]
	at com.ctc.wstx.sr.StreamScanner.throwUnexpectedChar(StreamScanner.java:647)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2054)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1131)
	at org.codehaus.staxmate.in.SMHierarchicCursor.getNext(SMHierarchicCursor.java:71)
	at org.codehaus.staxmate.in.SMInputCursor.advance(SMInputCursor.java:1631)
	at org.sonar.cxx.sensors.pclint.CxxPCLintSensor$1.stream(CxxPCLintSensor.java:95)
	at org.sonar.cxx.sensors.utils.StaxParser.parse(StaxParser.java:133)
	at org.sonar.cxx.sensors.utils.StaxParser.parse(StaxParser.java:101)
	at org.sonar.cxx.sensors.utils.StaxParser.parse(StaxParser.java:87)
	at org.sonar.cxx.sensors.pclint.CxxPCLintSensor.processReport(CxxPCLintSensor.java:231)
	at org.sonar.cxx.sensors.utils.CxxIssuesReportSensor.executeReport(CxxIssuesReportSensor.java:144)
	at org.sonar.cxx.sensors.utils.CxxIssuesReportSensor.executeImpl(CxxIssuesReportSensor.java:88)
	at org.sonar.cxx.sensors.utils.CxxReportSensor.execute(CxxReportSensor.java:253)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:177)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:291)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:286)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:264)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

**Comment by guwirth** [comment]
Hi @guchenghao8744,

have you read this: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers#pc-lint ?

Regards,

**Comment by guchenghao8744** [comment]
> 嗨@ guchenghao8744，
> 
> 您已阅读以下内容：[https](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers#pc-lint) : [//github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers#pc-lint](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers#pc-lint)吗？
> 
> 问候，
hi @guwirth 
thanks for your reply . I have followed your answer.
``lint-nt filea.cpp -v -width(0,0) +xml(?xml version="1.0" ?) +xml(results) -"format=<issue file =\q%f\q line = \q%l\q number = \q%n\q type=\q%t\q desc =\q%m\q>" -"format_specific= " -hFs1 -e900
``
output like this，
``--- Module:   filea.cpp (C++)
    _
    };
filea.cpp  8  Warning 601: No explicit type for symbol 'X::s', int assumed
filea.cpp  8  Error 10: Expecting ';'
<?xml>
Error 305: Unable to open module 'version=1.0'
</?xml>
``

sorry,my English is not good
