### ISSUE TITLE
NPE on parsing explicit template specialization

### ISSUE THREAD

**Issue by cheide** [SonarOpenCommunity/sonar-cxx#2138]
Attempting to use the sonar-cxx plugin to scan some C++ source causes a NullPointerException, causing the scan to fail. This appears to happen when the code contains explicit template specializations, and can be reproduced with the following reduced case:
```
class Formatter
{
   public:
      Formatter& operator%(int i) { return *this; }
};

template<typename T>
Formatter& LogMsg_applyFormat(Formatter& format, T t)
{
   return format % t;
}

template<> Formatter& LogMsg_applyFormat<int>(Formatter& format, int i);
```
Reworking this as template function overloads instead avoids the NPE.

Scan command:
sonar-scanner.bat -D sonar.projectKey=test -X -D sonar.cxx.file.suffixes=.cxx,.cpp,.cc,.c,.hxx,.hpp,.hh,.h -D sonar.sources=test.h

Log file:
[sonar.log](https://github.com/SonarOpenCommunity/sonar-cxx/files/6428856/sonar.log)

Environment:
 - OS: Windows 10
 - SonarQube version: 8.9.0.43852 Community Edition
 - cxx plugin version: 2.0.0.2650
 - sonar-scanner version: 4.6.1.2450

**Comment by guwirth** [comment]
Hi @cheide,

thanks for your feedback, we will have a look. 

Regards,

**Comment by guwirth** [comment]
Root cause:

``` 
at org.sonar.cxx.visitors.AbstractCxxPublicApiVisitor.visitTemplateDeclaration(AbstractCxxPublicApiVisitor.java:663)
at org.sonar.cxx.visitors.AbstractCxxPublicApiVisitor.visitDeclarator(AbstractCxxPublicApiVisitor.java:535)
at org.sonar.cxx.visitors.AbstractCxxPublicApiVisitor.visitSingleDeclarator(AbstractCxxPublicApiVisitor.java:527)
at org.sonar.cxx.visitors.AbstractCxxPublicApiVisitor.visitDeclaratorList(AbstractCxxPublicApiVisitor.java:480)
at org.sonar.cxx.visitors.AbstractCxxPublicApiVisitor.visitNode(AbstractCxxPublicApiVisitor.java:417)
```

**Comment by guwirth** [comment]
@cheide this is fixed you can try it with latest snapshot. Please wait another hour until your other issue is also merged.

**Comment by guwirth** [comment]
@cheide please try and give feedback: https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts
