### ISSUE TITLE
The plugin [cxx] does not support Java 1.8.0, UnsupportedClassVersionError

### ISSUE THREAD

**Issue by johaag** [SonarOpenCommunity/sonar-cxx#2171]
Hi team,

We are operating SonarQube LTS as a shared service for multiple diverse teams. Only a view of the teams are actually utilizing the sonar-cxx plugin.

While running some tests on SonarQube 8.9 LTS along with sonar-cxx v2.0.0, we noticed, that Java 11 is required to run SonarScanner, even if the sonar-cxx plugin is not (actively) utilized.

Is it possible to configure sonar-cxx v2 in such a way, so that the SonarScanner can be used with Java 8, if sonar-cxx is not utilized, but present on the SonarQube server? Java 8 is still [supported by SonarQube 8.9 LTS](https://docs.sonarqube.org/latest/requirements/requirements/) for SonarScanner, the requirement for Java 11 on scanner side has been shifted to SonarQube 9.x.

If that is possible, it would help us to ease the pain of the major update for our users.

Thank you for looking into this!

Best regards,
Jochen

**Comment by guwirth** [comment]
Hi @johaag,

thanks for your feedback.

> While running some tests on SonarQube 8.9 LTS along with sonar-cxx v2.0.0, we noticed, that Java 11 is required to run SonarScanner, even if the sonar-cxx plugin is not (actively) utilized.

What error message do you get? Is loading the plugin already failing or an API call?

> if sonar-cxx is not utilized, 

What exactly do you mean with not **not utilized**?
* The language part can be turned off by setting `sonar.cxx.file.suffixes=-`, but maybe this check is already failing.
* All other sensors are only called when the corresponding `sonar.cxx.xxx.ReportPaths` is defined. But also this check can fail.

Regards,

**Comment by guwirth** [comment]
Hi @johaag,

Thinking about this I'm not sure if Java 8 JVM is able to read a Java 11 binary at all?

But also wondering why it is so difficult to use Java 11? All what you have to do is:
- download OpenJDK 11 und unzip it (http://jdk.java.net/archive/)
- point with the JAVA_HOME environment variable to the Java 11 location

Think only some CI/CD machines are doing the scanning? So not all have to do it...

Regards,

**Comment by johaag** [comment]
Hi @guwirth,

Thank you for looking into our issue. Sorry that I missed to add the error message in the first place, here it is:
```
 11:44:50.157 INFO: Load plugins index (done) | time=43ms
 11:44:50.268 INFO: Load/download plugins (done) | time=155ms
 11:44:50.345 INFO: ------------------------------------------------------------------------
 11:44:50.345 INFO: EXECUTION FAILURE
 11:44:50.345 INFO: ------------------------------------------------------------------------
 11:44:50.345 INFO: Total time: 1.299s
 11:44:50.435 INFO: Final Memory: 28M/192M
 11:44:50.436 INFO: ------------------------------------------------------------------------
 11:44:50.436 ERROR: Error during SonarQube Scanner execution
 java.lang.IllegalStateException: The plugin [cxx] does not support Java 1.8.0_292
 	at org.sonar.core.platform.PluginClassLoader.instantiatePluginClasses(PluginClassLoader.java:133)
 	at org.sonar.core.platform.PluginClassLoader.load(PluginClassLoader.java:67)
 	at org.sonar.scanner.bootstrap.ScannerPluginRepository.start(ScannerPluginRepository.java:65)
 	at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
 	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
 	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
 	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
 	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
 	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
 	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
 	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
 	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
 	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
 	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
 	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
 Caused by: java.lang.UnsupportedClassVersionError: org/sonar/plugins/cxx/CxxPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
 	at java.lang.ClassLoader.defineClass1(Native Method)
 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
 	at java.security.AccessController.doPrivileged(Native Method)
 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
 	at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
 	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
 	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
 	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
 	at org.sonar.core.platform.PluginClassLoader.instantiatePluginClasses(PluginClassLoader.java:131)
 	... 26 more
```
Seems like loading of the plugin already fails, from what I understand with the help of your question and my little Java knowledge.

> What exactly do you mean with not **not utilized**?

Not utilized means, that the users are not using it actively. The plugin is "disabled" with the help of `sonar.cxx.file.suffixes=-` on the system admin settings as you mentioned, and this setting is not modified by the user. In addition the user does not use any `sonar.cxx.` parameter.

> Thinking about this I'm not sure if Java 8 JVM is able to read a Java 11 binary at all?

From how I read the error message, I assume that this is the problem.

> Think only some CI/CD machines are doing the scanning? So not all have to do it...

Thank you for sharing the procedure on how to update Java. We have more than 200 teams using our shared SonarQube service and they all have their own CI/CD pipelines. From the past we learned, that something like a simple Java update can cause massive support effort, that's why I decided to ask this question here, to learn, if we could delay this necessary Java update on scanner side until the next SonarQube 9.x LTS.

Best regards,
Jochen

**Comment by guwirth** [comment]
Hi @johaag,

looking to the error messages:

```
Caused by: java.lang.UnsupportedClassVersionError: org/sonar/plugins/cxx/CxxPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
...
 java.lang.IllegalStateException: The plugin [cxx] does not support Java 1.8.0_292
 	at org.sonar.core.platform.PluginClassLoader.instantiatePluginClasses(PluginClassLoader.java:133)
 	at org.sonar.core.platform.PluginClassLoader.load(PluginClassLoader.java:67)
```

It seems that the error message is from the Java Runtime trying to load the cxx plugin JAR file. I'm not the absolute Java expert but others told me that there is no way to support different Java versions in one JAR file? Because the plugin is one JAR file it has to be compiled all with the same Java version. Going a step back and converting all back to be Java 8 compatible is a to huge effort.

In case you know a solution you are welcome.

Regards,

**Comment by yankai-victor** [comment]
I had the same problem. Because My java project is compiled by Java 1.8 and I used the command "mvn sonar:sonar -Dsonar.projectKey...“. 
After I used the command "sonar-scanner -Dsonar.projectKey...", the problem was gone.
By the way, my sonarqube is 8.9.1 with java 11, and my java project is on another linux system with java 8.

**Comment by yankai-victor** [comment]
I had the same problem. Because My java project is compiled by Java 1.8 and I used the command "mvn sonar:sonar -Dsonar.projectKey...“. 
After I used the command "sonar-scanner -Dsonar.projectKey...", the problem was gone.
By the way, my sonarqube is 8.9.1 with java 11, and my java project is on another linux system with java 8.
