### ISSUE TITLE
module always handled as keyword (is only an identifier with special meaning in C++20)

### ISSUE THREAD

**Issue by dsakilesh** [SonarOpenCommunity/sonar-cxx#2192]
**Describe the bug**
We have the below error after upgrading the sonar cxx plugin to 2.0.X
`ERROR: MismatchException : 'Mismatch: expected ')' got: 'module -> getTiming ( ) ,   getTaskRuntimeCounter ( ) - time_before )   ( module -> getTiming ( ) ) . filter . add ( ( module -> getTiming ( ) ) . lastCycleTime ) ;   ( module -> getTiming ( ) ) . filteredCycleTime   =   ( module ->getTiming ( ) ) . filter . value ( ) ;' [tests://unittest(1,18)]' rest: '[PREPROCESSOR: module -> getTiming ( ) ,   getTaskRuntimeCounter ( ) - time_before )   ( module -> getTiming ( ) ) . filter . add ( ( module -> getTiming ( ) ) . lastCycleTime ) ;   ( module -> getTiming ( ) ) . filteredCycleTime   =   ( module -> getTiming ( ) ) . filter . value ( ) ;, EOF: EOF]'
`

**To Reproduce**
Before upgrade of the sonar cxx plugin to sonar-cxx 2.0.X, we did not have the issue.

**Expected behavior**
Expect to not fail with the above error

**Desktop (please complete the following information):**
 - OS: Linux
 - SonarQube version: 8.5.1
 - cxx plugin version: 2.0.3
 - sonar-scanner version: 4.5.0.2216
 
What could be the issue here? Is it the file format issue or the plugin itself?

PFA the sonar debug logs for more details.
[sonar_debug.log](https://github.com/SonarOpenCommunity/sonar-cxx/files/6653490/sonar_debug.log)

Let me know if you need more details.

Thanks in advance!

Regards,
Akilesh D S

**Comment by guwirth** [comment]
Hi @dsakilesh,

thanks for your feedback.

Rout cause seems to be a parsing issue:
```
[2021-06-15T06:49:11.323Z] 06:49:11.169 DEBUG: process unit '/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/src/OperatingSystem/OperatingSystemTask.cpp'
...
[2021-06-15T06:49:11.324Z] 06:49:11.178 DEBUG: process include file '/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/src/OperatingSystem/DrvOs.h'
[2021-06-15T06:49:11.324Z] 06:49:11.188 ERROR: MismatchException : 'Mismatch: expected ')' got: 'module -> getTiming ( ) ,   getTaskRuntimeCounter ( ) - time_before )   ( module -> getTiming ( ) ) . filter . add ( ( module -> getTiming ( ) ) . lastCycleTime ) ;   ( module -> getTiming ( ) ) . filteredCycleTime   =   ( module -> getTiming ( ) ) . filter . value ( ) ;' [tests://unittest(1,18)]' rest: '[PREPROCESSOR: module -> getTiming ( ) ,   getTaskRuntimeCounter ( ) - time_before )   ( module -> getTiming ( ) ) . filter . add ( ( module -> getTiming ( ) ) . lastCycleTime ) ;   ( module -> getTiming ( ) ) . filteredCycleTime   =   ( module -> getTiming ( ) ) . filter . value ( ) ;, EOF: EOF]'
```
Which leads to:
```
[2021-06-15T06:49:25.736Z] 06:49:25.573 DEBUG: Highlighting error in file 'OperatingSystemTask.cpp' at start:224:9 end:224:9
[2021-06-15T06:49:25.736Z] 06:49:25.573 DEBUG: Highlighting error in file 'OperatingSystemTask.cpp' at start:239:19 end:239:19
[2021-06-15T06:49:25.736Z] 06:49:25.573 DEBUG: Highlighting error in file 'OperatingSystemTask.cpp' at start:292:13 end:292:13
[2021-06-15T06:49:25.736Z] 06:49:25.573 DEBUG: Highlighting error in file 'OperatingSystemTask.cpp' at start:476:19 end:476:19
...
[2021-06-15T06:49:25.736Z] java.lang.IllegalStateException: Cannot register highlighting rule for characters at Range[from [line=239, lineOffset=9] to [line=239, lineOffset=13]] as it overlaps at least one existing rule
[2021-06-15T06:49:25.736Z] 	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.checkOverlappingBoundaries(DefaultHighlighting.java:60)
[2021-06-15T06:49:25.736Z] 	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.doSave(DefaultHighlighting.java:120)
[2021-06-15T06:49:25.736Z] 	at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:45)
[2021-06-15T06:49:25.736Z] 	at org.sonar.plugins.cxx.CxxSquidSensor.saveHighlighting(CxxSquidSensor.java:516)
[2021-06-15T06:49:25.736Z] 	at org.sonar.plugins.cxx.CxxSquidSensor.save(CxxSquidSensor.java:377)
[2021-06-15T06:49:25.736Z] 	at org.sonar.plugins.cxx.CxxSquidSensor.execute(CxxSquidSensor.java:306)
```
Is there something special in the file `OperatingSystemTask.cpp` at the positions above?

I saw also several  syntax errors. Seems a definition/macro is missing:
```
[2021-06-15T06:49:10.800Z] 06:49:10.771 DEBUG: [/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/matlab/tests/TorquePlausibility/TorquePlausibilityTest.cpp:29]:    syntax error: OUTPUT_DEFINE ( TEST_PresentNMotorPedalCrank_Out , float , OutputTask , ( 0.0f ) ) 
[2021-06-15T06:49:10.800Z] 06:49:10.771 DEBUG: [/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/matlab/tests/TorquePlausibility/TorquePlausibilityTest.cpp:30]:    syntax error: OUTPUT_DEFINE ( TEST_PresentResultingCrankMotorTorque_Out , float , OutputTask , ( 0.0f ) ) 
[2021-06-15T06:49:10.800Z] 06:49:10.771 DEBUG: [/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/matlab/tests/TorquePlausibility/TorquePlausibilityTest.cpp:33]:    syntax error: OUTPUT_DEFINE ( TEST_WalkAssistActive_Out , bool , OutputTask , ( false ) ) 
[2021-06-15T06:49:11.322Z] 06:49:11.100 DEBUG: [/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/src/DeviceLayer/MotorControl/BDU37xx/MotorControl37xx_FsmStateCalibrateRLS.hpp:212]:    syntax error: get_fsm_context ( ) . rotorPositionModule . 
[2021-06-15T06:49:11.322Z] 06:49:11.100 DEBUG: [/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/src/DeviceLayer/MotorControl/BDU37xx/MotorControl37xx_FsmStateCalibrateRLS.hpp:213]:    syntax error: get_fsm_context ( ) . focModule . 
[2021-06-15T06:49:11.322Z] 06:49:11.100 DEBUG: [/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/src/DeviceLayer/MotorControl/BDU37xx/MotorControl37xx_FsmStateCalibrateRLS.hpp:214]:    syntax error: get_fsm_context ( ) . focModule . 
[2021-06-15T06:49:11.322Z] 06:49:11.100 DEBUG: [/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/src/DeviceLayer/MotorControl/BDU37xx/MotorControl37xx_FsmStateCalibrateRLS.hpp:215]:    syntax error: get_fsm_context ( ) . focModule . 
[2021-06-15T06:49:11.322Z] 06:49:11.100 DEBUG: [/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/src/DeviceLayer/MotorControl/BDU37xx/MotorControl37xx_FsmStateCalibrateRLS.hpp:217]:    syntax error: get_fsm_context ( ) . 
[2021-06-15T06:49:11.322Z] 06:49:11.100 DEBUG: [/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/src/DeviceLayer/MotorControl/BDU37xx/MotorControl37xx_FsmStateCalibrateRLS.hpp:218]:    syntax error: get_fsm_context ( ) . rotorPositionModule . 
[2021-06-15T06:49:11.591Z] 06:49:11.334 DEBUG: [/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/matlab/tests/TorqueCoordinator/TorqueCoordinatorTest.cpp:12]:    syntax error: OUTPUT_DEFINE ( TORCO_DriveControllerTorqueRequest_TestOut , float , OutputMulticore , ( 0.0f ) ) 
[2021-06-15T06:49:11.591Z] 06:49:11.334 DEBUG: [/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/matlab/tests/TorqueCoordinator/TorqueCoordinatorTest.cpp:16]:    syntax error: OUTPUT_DEFINE ( TORCO_DesiredCadenceBasedMotorTargetSpeed_TestOut , float , OutputMulticore , ( 0 ) ) 
[2021-06-15T06:49:11.591Z] 06:49:11.334 DEBUG: [/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/matlab/tests/TorqueCoordinator/TorqueCoordinatorTest.cpp:19]:    syntax error: OUTPUT_DEFINE ( TORCO_UpsideDownDetected_TestOut , bool , OutputMulticore , ( false ) ) 
[2021-06-15T06:49:11.591Z] 06:49:11.334 DEBUG: [/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/matlab/tests/TorqueCoordinator/TorqueCoordinatorTest.cpp:20]:    syntax error: OUTPUT_DEFINE ( TORCO_WalkAssistNmotorPcRequest_TestOut , float , OutputMulticore , ( 0.0f ) ) 
[2021-06-15T06:49:11.591Z] 06:49:11.334 DEBUG: [/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/matlab/tests/TorqueCoordinator/TorqueCoordinatorTest.cpp:21]:    syntax error: OUTPUT_DEFINE ( TORCO_WalkAssistActive_TestOut , bool , OutputMulticore , ( false ) ) 
[2021-06-15T06:49:11.591Z] 06:49:11.334 DEBUG: [/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/matlab/tests/TorqueCoordinator/TorqueCoordinatorTest.cpp:22]:    syntax error: OUTPUT_DEFINE ( TORCO_WalkAssistActiveButtonReleased_TestOut , bool , OutputMulticore , ( false ) ) 
[2021-06-15T06:49:11.591Z] 06:49:11.334 DEBUG: [/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/matlab/tests/TorqueCoordinator/TorqueCoordinatorTest.cpp:24]:    syntax error: OUTPUT_DEFINE ( TORCO_ShiftDetActive_TestOut , bool , OutputMulticore , ( false ) ) 
[2021-06-15T06:49:11.591Z] 06:49:11.334 DEBUG: [/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/matlab/tests/TorqueCoordinator/TorqueCoordinatorTest.cpp:28]:    syntax error: OUTPUT_DEFINE ( TORCO_MotorSupportAllowed_TestOut , bool , OutputMulticore , ( true ) ) 
[2021-06-15T06:49:11.591Z] 06:49:11.334 DEBUG: [/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/matlab/tests/TorqueCoordinator/TorqueCoordinatorTest.cpp:30]:    syntax error: OUTPUT_DEFINE ( TORCO_eShiftInterventionActive_TestOut , bool , OutputMulticore , ( false ) ) 
[2021-06-15T06:49:11.591Z] 06:49:11.334 DEBUG: [/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/matlab/tests/TorqueCoordinator/TorqueCoordinatorTest.cpp:34]:    syntax error: OUTPUT_DEFINE ( TORCO_PTM_T1_est_NmPc_TestOut , float , OutputMulticore , ( 95.0f ) ) 
[2021-06-15T06:49:11.591Z] 06:49:11.334 DEBUG: [/var/jenkins/0/workspace/ware_bugfix_sonar.sourceEncoding@2/matlab/tests/TorqueCoordinator/TorqueCoordinatorTest.cpp:36]:    syntax error: OUTPUT_DEFINE ( TORCO_presentNMotorPedalCrank_TestOut , float , OutputMulticore , ( 0.0f ) )
...
```
Regards,

**Comment by dsakilesh** [comment]
Hi @guwirth 

PFB the content in the lines..

224:09`  assert(module != nullptr);`
239:19`  for (const auto& module : this->registeredModules) {`
292:13`  for (auto* module : this->registeredModules) {`
476:19`  for (const auto* module : this->registeredModules) {`

It seems to be erroring when it encounters `module`

**Comment by guwirth** [comment]
@dsakilesh `module` is a identifiers with special meaning in C++20. I will verify it.
https://en.cppreference.com/w/cpp/keyword

A fast workaround is to `#define module __module`.
Is your code C or C++?

**Comment by guwirth** [comment]
Hi @dsakilesh,

did some tests with the SSLR toolkit and can't reproduce it. There seems to be no issue with `module`. Must be something else?
```C++
void f() {
   assert(module != nullptr);
   for (const auto& module : this->registeredModules) {}
   for (auto* module : this->registeredModules) {}
   for (const auto* module : this->registeredModules) {}
}
```
![grafik](https://user-images.githubusercontent.com/6077367/122091522-2d010080-ce09-11eb-92a1-12e9411ee245.png)

**Comment by guwirth** [comment]
@dsakilesh please try with latest snapshot https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts. This does not solve the problem but should continue after a problem as with 1.3.

**Comment by dsakilesh** [comment]
Hi @guwirth 

Thanks for the quick fix.. Its working now

When can we expect a stable release 2.0.4?

Regards,

**Comment by guwirth** [comment]
Hi @dsakilesh,

the fix continues only after the problem and does not fix it. Still like to understand the root cause.
It shows an error in `tests://unittest(1,18)`? Any idea what that could be?

```
ERROR: MismatchException : 'Mismatch: expected ')'
got: 'module->getTiming(),getTaskRuntimeCounter()-time_before)(module->getTiming()).filter.add((module->getTiming()).lastCycleTime);(module->getTiming()).filteredCycleTime=(module->getTiming()).filter.value();'
[tests://unittest(1,18)]'
rest: '[PREPROCESSOR: module->getTiming(),getTaskRuntimeCounter()-time_before)(module->getTiming()).filter.add((module->getTiming()).lastCycleTime);(module->getTiming()).filteredCycleTime=(module->getTiming()).filter.value();,EOF:EOF]'
```
