### ISSUE TITLE
Add "sonar-cxx" to externsions/plugins ,can not start SonarQube 9.x

### ISSUE THREAD

**Issue by Andylau1994** [SonarOpenCommunity/sonar-cxx#2229]
**Description**
Hello,
Thanks for checking out my issue,now I have a problem,when I add  "sonar-cxx" in externsions/plugins,then I can't start sonar,but when i removed "sonar-cxx" , it works,I don't have any ideas about it,Please give me some possible reasons.
thx.

**web.log:**
```
2021.08.19 10:12:32 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.NoSuchMethodError: org.sonar.api.server.rule.RulesDefinition$NewRule.setEffortToFixDescription(Ljava/lang/String;)Lorg/sonar/api/server/rule/RulesDefinition$NewRule;
	at org.sonar.cxx.squidbridge.annotations.AnnotationBasedRulesDefinition.setupSqaleModel(AnnotationBasedRulesDefinition.java:184)
	at org.sonar.cxx.squidbridge.annotations.AnnotationBasedRulesDefinition.addRuleClasses(AnnotationBasedRulesDefinition.java:102)
	at org.sonar.cxx.squidbridge.annotations.AnnotationBasedRulesDefinition.addRuleClasses(AnnotationBasedRulesDefinition.java:88)
	at org.sonar.plugins.cxx.CxxRuleRepository.define(CxxRuleRepository.java:34)
	at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoader.java:53)
	at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:117)
	at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:49)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:87)
	at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:45)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:84)
	at org.sonar.server.platform.PlatformImpl.executeStartupTasks(PlatformImpl.java:198)
	at org.sonar.server.platform.PlatformImpl$1.lambda$doRun$1(PlatformImpl.java:122)
	at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:370)
	at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:122)
	at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:354)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021.08.19 10:12:32 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
2021.08.19 10:12:32 INFO  web[][o.s.s.n.NotificationDaemon] Notification service stopped
```
**Sonarqube Version:**
9.0.1.46107

**sonar-cxx Version**
2.0.4

**Java Version:**
11.0.12

**database**
PostgreSQL 10.5-2

**Comment by guwirth** [comment]
Hi @Andylau1994,

Think the interesting message is:

`java.lang.NoSuchMethodError: org.sonar.api.server.rule.RulesDefinition$NewRule.setEffortToFixDescription(Ljava/lang/String;)Lorg/sonar/api/server/rule/RulesDefinition$NewRule;
`

That means the SQ version 9.0 does no more support the API `RulesDefinition`. The cxx plugin is only tested and released for SQ 7.9 LTS and SQ 8.9 LTS. Supporting non LTS versions is too much effort because they are changing/removing APIs with every iteration.

We will support the 9.x if there is a LTS available.

Regards,

**Comment by Andylau1994** [comment]
It helps me a lot,thx

**Comment by lg2de** [comment]
Hey @guwirth, [9.x LTS is scheduled for november 2022](https://community.sonarsource.com/t/how-to-update-build-in-plugins-in-sonarqube-lts/50948/4).
Do you really want not adapt the plugin for so long time?

Other analyzers, e.g. `sonar-dotnet` as build-in plugin, will be updated frequently but only in the 9.x releases.
I would like to use ALL plugin in the most recent version. So, I must to use the 9.X releases (no manual update possible for build-in plugins), but I cannot because `sonar-cxx` will only be available next year.

According to my understanding the SQ introduces breaking changes only with x.0 versions.
So, why not preparing _now_ a 9.x compatible version?
