### ISSUE TITLE
Question: Reproduce parsing errors on local machine

### ISSUE THREAD

**Issue by amai2012** [SonarOpenCommunity/sonar-cxx#2286]
I have a lot of parsing errors in my codebase.

https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Detect-and-fix-parsing-errors has some suggestions but I lack a short hello-world project for testing.
Is it possible to reproduce the parse errors on my local machine without a full-blown analysis?

**Comment by guwirth** [comment]
Hi @amai2012,

you found already https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Detect-and-fix-parsing-errors.

The best way is normally to define some macros to fix parsing errors. You should always keep in mind, that the cxx parser is only doing a **syntax analysis** (you don't have to provide all includes, macros, types for a semantic analysis):
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Dealing-with-compiler-specific-code-pieces

Add the macros of your project to a header file and include it with https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.forceIncludes. Good samples for headers are here: https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/cxx-sensors/src/main/resources/macros.

To test things locally on your PC you can use the **SSLR toolkit**. Copy paste your code into the toolkit window
https://github.com/SonarOpenCommunity/sonar-cxx/releases/download/cxx-2.0.6/cxx-sslr-toolkit-2.0.6.2925.jar

> * **Hint**: The tool works only with plain ASCII. With Windows you can copy/paste the text over Notepad to get it done.

![grafik](https://user-images.githubusercontent.com/6077367/145213214-9c9730d1-7f06-4389-9f02-fc6e06a3875a.png)

Hope this helps!

Regards,

**Comment by amai2012** [comment]
So far I have found three kind of issues:

- missing compiler-specific macros -> I'm feeding them now via forced include
- errors with complex nested macros from my own codebase -> to be analyzed

And this one:
The following code snippet without macro 
~~~ cpp
struct Portfolio { int get() const; };

int check(const Portfolio& parObj, const int ind)
{
    if (parObj.get() < 0 || parObj.get() >= ind)
    {
        return 0;
    }
    return 1;
}
~~~
triggers 
~~~
com.sonar.sslr.api.RecognitionException: Parse error at line 3 column 10:

    1: struct Portfolio { int get() const; };
    2: 
  -->  int check(const Portfolio& parObj, const int ind)
    4: {
    5:     if (parObj.get() < 0 || parObj.get() >= ind)
    6:     {

	at org.sonar.sslr.internal.vm.Machine.parse(Machine.java:73)
	at com.sonar.sslr.impl.Parser.parse(Parser.java:84)
	at com.sonar.sslr.impl.Parser.parse(Parser.java:78)
	at org.sonar.sslr.internal.toolkit.SourceCodeModel.setSourceCode(SourceCodeModel.java:62)
	at org.sonar.sslr.internal.toolkit.ToolkitPresenter.onSourceCodeParseButtonClick(ToolkitPresenter.java:122)
	at org.sonar.sslr.internal.toolkit.ToolkitViewImpl$5.actionPerformed(ToolkitViewImpl.java:201)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

~~~

**Comment by guwirth** [comment]
Hello @amai2012,

thank you for your investigation.

Could you please further narrow down the last finding. Try each test individual with the SSLR toolkit. Maybe it’s the `const int`?

``` C++
// Test 1
struct Portfolio { int get() const; };
int check(const Portfolio& parObj, const int ind) { return 1; }

// Test 2
int check(const Portfolio& parObj, const int ind) { return 1; }

// Test 3
int check(const int ind) { return 1; }

// Test 4
int check(int ind) { return 1; }
```

Regards,

**Comment by amai2012** [comment]
> Hello @amai2012,
> 
> thank you for your investigation.
> 
> Could you please further narrow down the last finding. Try each test individual with the SSLR toolkit. Maybe it’s the `const int`?
> 
>...

Test 1-4 are passing here, the original example fails.
I've only been able to reduce to:
~~~ cpp
struct Portfolio { int get() const; };

int check( Portfolio& parObj, int ind)
{
    if (parObj.get() < 0 || parObj.get() >= ind)
    {
        return;
    }
}
~~~

I observe some odd behaviour with that sslr-tool here:
I am loading the example from a file (ANSI as of Notepad++) and the `<` char is absent. However explicitly adding it in the Source code window seems to work, it shows up on the right hand side and the error persists...

**Comment by guwirth** [comment]
Hi @amai2012,

I was able to narrow this down (see below). Problem are the brackets `()` in combination with `<...>=`. Fast woraround is to set brackets `((...) || (...))`.

That has maybe something to do with
https://github.com/SonarOpenCommunity/sonar-cxx/blob/fa5575c5231ae181281de20b4a274e27402c0cc5/cxx-squid/src/main/java/org/sonar/cxx/channels/RightAngleBracketsChannel.java#L44

Samples:
``` C++
void check() { // failure
    a() < 0 || c >= 1;
}
void check() { // ok
    a() < 0 || c > 1;
}
void check() { // ok
    a < 0 || c >= 1;
}
//-------------------------------------------------
void check() { // failure
    if ( a.b() < 0 || c >= 1) {}
}
void check() { // failure
    if ( a() < 0 || c >= 1) {}
}
void check() { // failure
    if ( a.b(1) < 0 || c >= 1 ) {}
}
void check() { // ok
    if ( a() < 0 || c > 1) {}
}
void check() { // ok
    if ( (a.b() < 0) || (c >= 1) ) {}
}
void check() { // ok
    if ( a.b < 0 || c >= 1) {}
}
void check() { // ok
    if ( a < 0 || c >= 1) {}
}
```

**Comment by amai2012** [comment]
Thanks for fixing this.
I had no time to verify before, but now picking up 2.0.7 and trying to resolve more issues
