### ISSUE TITLE
Execution is failed with CPD errors in SonarQube 9.9 LTS version

### ISSUE THREAD

**Issue by eshwarkarthikn** [SonarOpenCommunity/sonar-cxx#2558]
Hi,

We are getting CPD errors and execution gets failed while running analysis in SonarQube 9.9 LTS. Could you please help us if you have fix for this? Added the logs below.
```
12:26:22.855 DEBUG: CPD error in file 'TopFile.cpp' at line:48, column:59
12:26:22.855 DEBUG: CPD error in file 'TopFile.cpp' at line:48, column:61
12:26:22.856 DEBUG: CPD error in file 'ActionHandler.cpp' at line:60, column:72
12:26:22.856 DEBUG: CPD error in file 'ActionHandler.cpp' at line:60, column:74
12:26:22.856 DEBUG: CPD error in file 'ActionHandler.cpp' at line:65, column:70
12:26:22.856 DEBUG: CPD error in file 'ActionHandler.cpp' at line:65, column:72
12:26:22.856 DEBUG: CPD error in file 'ActionHandler.cpp' at line:70, column:12
12:26:22.856 DEBUG: CPD error in file 'ActionHandler.cpp' at line:90, column:16
12:26:22.856 DEBUG: CPD error in file 'ActionHandler.cpp' at line:117, column:16
12:26:22.857 DEBUG: Not enough content in 'src/common/glibc/Glibc.hpp' to have CPD blocks, it will not be part of the duplication detection

12:26:22.874 ERROR: Cannot save all measures for file '/****/filename.cpp', cause='IllegalStateException: Cannot register highlighting rule for characters at Range[from [line=93, lineOffset=79] to [line=93, lineOffset=90]] as it overlaps at least one existing rule', stop analysis
12:26:22.883 INFO: ------------------------------------------------------------------------
12:26:22.883 INFO: EXECUTION FAILURE
12:26:22.883 INFO: ------------------------------------------------------------------------
12:26:22.883 INFO: Total time: 24.841s
12:26:23.009 INFO: Final Memory: 55M/320M
12:26:23.009 INFO: ------------------------------------------------------------------------
12:26:23.009 ERROR: Error during SonarScanner execution
java.lang.IllegalStateException: Cannot save all measures for file '/****/filename.cpp'
	at org.sonar.cxx.sensors.utils.CxxUtils.validateRecovery(CxxUtils.java:80)
	at org.sonar.plugins.cxx.CxxSquidSensor.save(CxxSquidSensor.java:432)
	at org.sonar.plugins.cxx.CxxSquidSensor.execute(CxxSquidSensor.java:335)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
	at org.sonar.scanner.sensor.ProjectSensorsExecutor.execute(ProjectSensorsExecutor.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:126)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:81)
	at org.sonarsource.scanner.cli.Main.main(Main.java:62)
Caused by: java.lang.IllegalStateException: Cannot register highlighting rule for characters at Range[from [line=93, lineOffset=79] to [line=93, lineOffset=90]] as it overlaps at least one existing rule
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.checkOverlappingBoundaries(DefaultHighlighting.java:60)
	at org.sonar.batch.sensor.highlighting.internal.DefaultHighlighting.doSave(DefaultHighlighting.java:108)
	at org.sonar.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:45)
	at org.sonar.plugins.cxx.CxxSquidSensor.saveHighlighting(CxxSquidSensor.java:572)
	at org.sonar.plugins.cxx.CxxSquidSensor.save(CxxSquidSensor.java:429)
	... 23 more
```
Thank you!

@felipebz @moriarty @bjd @Zetten  @guwirth

**Comment by guwirth** [comment]
Hi,

error is thrown here
https://github.com/SonarOpenCommunity/sonar-cxx/blob/fbf26a1063fd1330c19b3c4f596bf9797624b65f/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/CxxSquidSensor.java#L549

Root cause is typically a syntax error (or code not supported by the plugin grammar). Could you provide sample code from the error location?

Regards,
