### ISSUE TITLE
Builds failing with  'CXX-public_undocumented_api' does not exist error

### ISSUE THREAD

**Issue by renukaholimath** [SonarOpenCommunity/sonar-cxx#2610]
hi Team,

We have hosted SonarQube Datacenter edition v10.1.0 in our environment. Based on the request of one user, we have installed the "sonar-cxx-plugin-2.1.1.488.jar" plugin on our Pilot instance. After the plugin installation, all the builds are failing with the below error. PFA the complete scanner context error.
[builderror.txt](https://github.com/SonarOpenCommunity/sonar-cxx/files/13958610/builderror.txt)

Is this a known issue? Could you please let us know if there is any fix available for this issue?

Caused by: java.lang.IllegalStateException: Metric with key 'CXX-public_undocumented_api' does not exist
	at org.sonar.ce.task.projectanalysis.metric.MetricRepositoryImpl.getByKey(MetricRepositoryImpl.java:67)
	at org.sonar.ce.task.projectanalysis.api.measurecomputer.MeasureComputerContextImpl.getMeasure(MeasureComputerContextImpl.java:112)
	at org.sonar.cxx.DensityMeasureComputer.compute(DensityMeasureComputer.java:72)
	at org.sonar.cxx.DensityMeasureComputer.compute(DensityMeasureComputer.java:120)
	at org.sonar.ce.task.projectanalysis.measure.MeasureComputersVisitor.visitAny(MeasureComputersVisitor.java:65)
	at org.sonar.ce.task.projectanalysis.component.TypeAwareVisitorWrapper.visitAny(TypeAwareVisitorWrapper.java:77)
	at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitNode(VisitorsCrawler.java:114)
	at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitImpl(VisitorsCrawler.java:97)
	at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visit(VisitorsCrawler.java:69)

Regards,
Renuka

**Comment by guwirth** [comment]
Hello @renukaholimath,

the plugin supports only LTS versions, see compatibility matrix:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compatibility-Matrix

Regards,
