### ISSUE TITLE
C++ plugin causing an issue while running Java/python projects 

### ISSUE THREAD

**Issue by narayam** [SonarOpenCommunity/sonar-cxx#2634]
**Describe the bug**

When I ran the sonarscanner for Java or Python project. we are getting the below error which was caused by C++ Plugin. If I uninstall the C++ plugin Sonarscanner is working fine. Not able to find the root cause. Kindly help me on this issue.

```
ERROR: Error during SonarScanner execution
java.lang.NoClassDefFoundError: org/sonar/cxx/sensors/tests/dotnet/CxxUnitTestResultsAggregator
  at org.sonar.plugins.cxx.CxxPlugin.getSensorsImpl(CxxPlugin.java:110)
  at org.sonar.plugins.cxx.CxxPlugin.define(CxxPlugin.java:80)
  at org.sonar.scanner.bootstrap.ExtensionInstaller.install(ExtensionInstaller.java:57)
  at org.sonar.scanner.scan.SpringProjectScanContainer.addScannerExtensions(SpringProjectScanContainer.java:327)
  at org.sonar.scanner.scan.SpringProjectScanContainer.doBeforeStart(SpringProjectScanContainer.java:156)
  at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:186)
  at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
  at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:137)
  at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
  at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
  at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
  at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
  at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
  at jdk.proxy1/jdk.proxy1.$Proxy0.execute(Unknown Source)
  at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
  at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
  at org.sonarsource.scanner.cli.Main.execute(Main.java:126)
  at org.sonarsource.scanner.cli.Main.execute(Main.java:81)
  at org.sonarsource.scanner.cli.Main.main(Main.java:62)
Caused by: java.lang.ClassNotFoundException: org.sonar.cxx.sensors.tests.dotnet.CxxUnitTestResultsAggregator
  at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
  at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
  at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
  ... 24 more
ERROR: 
ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
```

**To Reproduce**
Its not reproducable.
Past 25 day sonarqube works fine with C++ plugin, but today we getting the above error for Java and python projects. After I unistall the C++ plugin sonarqube working fine. (often we are facing this issue, I used unistall the C++ plugin and install other version of C++ plugin). And not able to find the permenant solution.

**Expected behavior**
I want to be a sonarqube working fine with C++ plugin. Need to fix the above issue.

**Desktop (please complete the following information):**
 - OS:  Linux - RHEL 8.9
 - SonarQube version: Community Edition - Version 9.9.1 (build 69595)
 - cxx plugin version: sonar-cxx-plugin-2.1.2.588.jar
 - sonar-scanner version: Sonar-scanner-cli:5.0.1
 - Java: Java version “17.0.7” 2023-04-18 LTS
 
**Additional context**
docker run --rm -e SONAR_HOST_URL=https://sonar.com/ -e ‘SONAR_SCANNER_OPTS=-Dsonar.projectKey=management -Dsonar.branch.name=master -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300’ -e SONAR_TOKEN=XXXXXXXXXXXXX -v /tmp/sonar/management:/opt/sonar-scanner/.sonar/cache -v /workspace/management_master:/usr/src sonar-scanner-cli:5.0.1

**Comment by guwirth** [comment]
Hi @narayam,

> Past 25 day sonarqube works fine with C++ plugin, but today we getting the above error for Java and python projects.

What has changed in your setup?

> cxx plugin version: sonar-cxx-plugin-2.1.2.588.jar

Is not an official release. Last released version was 2.1.1 with https://github.com/SonarOpenCommunity/sonar-cxx/releases/download/cxx-2.1.1/sonar-cxx-plugin-2.1.1.488.jar. Please try again with this version.

Regards,

**Comment by narayam** [comment]
okay thanks let me try

**Comment by narayam** [comment]
@guwirth as you suggested I have updated the C++ plugin version 2.1.1.488. Its worked without any issue. But after a month, we are getting same issue.

_ERROR: Error during SonarScanner execution
java.lang.NoClassDefFoundError: org/sonar/cxx/sensors/tests/dotnet/CxxUnitTestResultsAggregator
	at org.sonar.plugins.cxx.CxxPlugin.getSensorsImpl(CxxPlugin.java:110)
	at org.sonar.plugins.cxx.CxxPlugin.define(CxxPlugin.java:80)
	at org.sonar.scanner.bootstrap.ExtensionInstaller.install(ExtensionInstaller.java:57)
	at org.sonar.scanner.scan.SpringProjectScanContainer.addScannerExtensions(SpringProjectScanContainer.java:327)
	at org.sonar.scanner.scan.SpringProjectScanContainer.doBeforeStart(SpringProjectScanContainer.java:156)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:186)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:137)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at jdk.proxy1/jdk.proxy1.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:126)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:81)
	at org.sonarsource.scanner.cli.Main.main(Main.java:62)
Caused by: java.lang.ClassNotFoundException: org.sonar.cxx.sensors.tests.dotnet.CxxUnitTestResultsAggregator
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)_

**Comment by guwirth** [comment]
Hi @narayam,

thanks for trying.  What has changed in your setup? Sounds that SQ version, cxx version and config was stable?

Error is `org.sonar.cxx.sensors.tests.dotnet.CxxUnitTestResultsAggregator` in `CxxPlugin.define`
https://github.com/SonarOpenCommunity/sonar-cxx/blob/484c9a5b663cf715376811849633d070b7df3320/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/CxxPlugin.java#L110

That’s one of the first steps loading the `CxxPlugin`, long before executing the plugin. Don’t understand why this sometimes is working, sometimes not?

Regards,

**Comment by guwirth** [comment]
@narayam

* error during load/init of plugin https://github.com/SonarOpenCommunity/sonar-cxx/blob/484c9a5b663cf715376811849633d070b7df3320/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/CxxPlugin.java#L110
* before loading/reading the configuration
* before executing a sensor/report

Can only be a problem with SonarQube version, cxx version, Java or environment.
