### ISSUE TITLE
java.lang.NoSuchMethodError while running sonar runner

### ISSUE THREAD

**Issue by raingod800** [SonarOpenCommunity/sonar-cxx#785]
Dear All,

I am trying to use the C/C++ community plug-in with our codebase

https://github.com/SonarOpenCommunity/sonar-cxx

I have only set up cppcheck to get the report for which I give the path in the properties file

But now when I run the sonar server and then run the scanner, I get this:

sonar-runner.bat
C:\sonar-runner\sonar-scanner-2.5\bin\..
INFO: Scanner configuration file: C:\sonar-runner\sonar-scanner-2.5\bin\..\conf\sonar-runner.properties
INFO: SonarQube Scanner 2.5
INFO: Java 1.8.0_65 Oracle Corporation (64-bit)
INFO: Windows 7 6.1 amd64
INFO: Load global repositories
INFO: Load global repositories (done) | time=203ms
INFO: Load plugins index
INFO: Load plugins index (done) | time=0ms
INFO: Default locale: "en_GB", source code encoding: "UTF-8"
INFO: Process project properties
INFO: Load project repositories
INFO: Load project repositories (done) | time=109ms
INFO: Apply project exclusions
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=124ms
INFO: Load active rules
INFO: Load active rules (done) | time=1235ms
INFO: SCM provider autodetection failed. No SCM provider claims to support this project. Please use sonar.scm.provider to define SCM of your project.
INFO: Publish mode
INFO: Load server rules
INFO: Load server rules (done) | time=639ms
INFO: 31 files indexed
INFO: 0 files ignored because of inclusion/exclusion patterns
INFO: Quality profile for c++: Sonar way
Exception in thread "main" java.lang.NoSuchMethodError: org.sonar.api.resources.Project.getFileSystem()Lorg/sonar/api/resources/ProjectFileSystem;
        at org.sonar.plugins.cxx.squid.CxxSquidSensor.shouldExecuteOnProject(CxxSquidSensor.java:81)
        at org.sonar.batch.bootstrap.BatchExtensionDictionnary.shouldKeep(BatchExtensionDictionnary.java:260)
        at org.sonar.batch.bootstrap.BatchExtensionDictionnary.getFilteredExtensions(BatchExtensionDictionnary.java:101)
        at org.sonar.batch.bootstrap.BatchExtensionDictionnary.select(BatchExtensionDictionnary.java:74)
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:46)
        at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:98)
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:185)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:243)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:238)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:228)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
        at org.sonar.batch.task.ScanTask.execute(ScanTask.java:55)
        at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
        at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:122)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
        at org.sonar.runner.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:67)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.sonar.runner.impl.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:61)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:274)
        at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:165)
        at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:152)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:118)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:80)
        at org.sonarsource.scanner.cli.Main.main(Main.java:66)

I am not sure which method is wrong. 

Earlier I was trying the commercial plug-in and used build-wrapper while building the code. Now I have stopped using build-wrapper, so I need to build the code with some community wrapper though?

My properties file looks like this:

sonar.projectKey=org.CxxPlugin:Sample
sonar.projectName=C :: Test :: Testmodule
sonar.projectVersion=1.0
sonar.sources="Path to Code"
sonar.sourceEncoding=UTF-8
sonar.cxx.cppcheck.reportPath=cppcheck-report.xml

Many thanks for your help!
Kind Regards,
Gaurav

**Comment by jmecosta** [comment]
hi,

can you share your config, cxx version, sonar version?

if you want a wrapper, and you use msbuild, you can use this: https://github.com/jmecsoftware/sonar-cxx-msbuild-tasks

**Comment by raingod800** [comment]
Hi Jorge,

Thanks for your email. The code is actually all C code, I was hoping that
C++ plug-in works for C code. Sonarqube version is 5.3, sonar scanner
version is 2.5, the properties file is like this:

sonar.projectKey=org.CxxPlugin:Sample
sonar.projectName=C :: Test :: Testmodule
sonar.projectVersion=1.0
sonar.sources="Path to Code"
sonar.sourceEncoding=UTF-8
sonar.cxx.cppcheck.reportPath=cppcheck-report.xml

I am not sure about the purpose of wrapper, we use scons to build the code
and would like to do the static analysis of the code using the community
plug-in.

I was able to successfully do the analysis using the evaluation version of
the C/C++ sonar plugin, but then I uninstalled the commercial plug-in and
tried the community plug-in.

Please give some pointers...

Many thanks,
Gaurav

**Comment by jmecosta** [comment]
what version of the c++ plugin version?

check this thread for more info about c: https://github.com/SonarOpenCommunity/sonar-cxx/issues/772

the wrapper is for msbuild build systems, not for you unfortunately.

**Comment by raingod800** [comment]
I am using version 0.9.1 for C++ plug in please...will it work for C code
too?

Thanks!

**Comment by jmecosta** [comment]
try using the last release: https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/cxx-0.9.4 if that one does not work. install the last snapshot for https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts

and following the instructions in pdwiki

in principle it should work

**Comment by raingod800** [comment]
Many many thanks Jorge, i installed 0.9.4 and it worked like a wonder!!

i will try including the directories next :-)

One basis question....
I am confused about the need for build wrapper (as was there in the
commerical plug-in). Do I need anything corresponding to that or is
cppcheck enough to point to the code issues..?

I am only supplying the cppcheck output and it is detecting issues in code

Thanks & Regards,
Gaurav

**Comment by jmecosta** [comment]
there is no wrapper in your case, everything should be produced before running the analysis.

please check the wiki, https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Running-tools there is information that you will probably need.

good luck.

**Comment by raingod800** [comment]
Hi Jorge,

I read the tips you gave on running C++ plug in on the C project,

https://github.com/SonarOpenCommunity/sonar-cxx/issues/772


 however i still get an error.

I have added the following in the sonar properties file:

sonar.cxx.suffixes.sources=.cpp,.c
sonar.cxx.cFilesPatterns=*.c,*.C


However, the following error comes:



INFO: EXECUTION FAILURE
INFO:
------------------------------------------------------------------------
INFO: Total time: 1:32.576s
INFO: Final Memory: 63M/769M
INFO:
------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
*ERROR: You must install a plugin that supports the language 'c'*

It seems 0.9.4 doesn't support language C, is there some way to make the
plug-in work for C files please?

Thanks & Regards,
Gaurav

**Comment by raingod800** [comment]
Hi Jorge,

Please ignore my previous query regarding "*You must install a plugin that
supports the language 'c'"*

It actually got resolved by adding:

sonar.cxx.suffixes.sources=.cpp,.c
sonar.cxx.cFilesPatterns=*.c,*.C


I wasn't applying it properly


Many thanks!

Kind Regard,s
