### ISSUE TITLE
File removed from repository can't be analyse

### ISSUE THREAD

**Issue by rlucca** [SonarOpenCommunity/sonar-cxx#801]
Hi there,

I'm getting the wrong below to a file that no longer exist in the repository. It appears that the file was removed recently, what I should do to sonnar-scanner to be done succesfully? I think about put it in sonar.exclusions list because of [this](http://stackoverflow.com/questions/21323276/sonarqube-exclude-a-directory), but I'm not sure if it's a good solution.

Ways to reproduced:

1.  Get a repository with files: src/a.c, src/b.c
2. Run the sonar-scanner, it'll be done succesfully;
3. Remove a file (src/a.c or src/b.c);
4. Run the sonar-scanner, it'll fail because a file can't be parsed;

```
ERROR: Error during Sonar runner execution
org.sonar.runner.impl.RunnerException: Unable to execute Sonar
        at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
        at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
        at java.security.AccessController.doPrivileged(Native Method) 
        at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
        at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
        at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
        at org.sonar.runner.api.Runner.execute(Runner.java:100)
        at org.sonar.runner.Main.executeTask(Main.java:70)
        at org.sonar.runner.Main.execute(Main.java:59)
        at org.sonar.runner.Main.main(Main.java:53)
Caused by: org.sonar.squidbridge.api.AnalysisException: Unable to analyze file: /buildslaves/buildslave_sonar/sonar-fw-next/build/tools/appliance/shell/shell.h
        at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:127)
        at org.sonar.plugins.cxx.squid.CxxSquidSensor.analyse(CxxSquidSensor.java:126)
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:59)
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:51)
        at org.sonar.batch.phases.DatabaseModePhaseExecutor.execute(DatabaseModePhaseExecutor.java:120)
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:264)
        at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
        at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:235)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:230)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:220)
        at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
        at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
        at org.sonar.batch.scan.ScanTask.scan(ScanTask.java:57)
        at org.sonar.batch.scan.ScanTask.execute(ScanTask.java:45)
        at org.sonar.batch.bootstrap.TaskContainer.doAfterStart(TaskContainer.java:135)
        at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
        at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
        at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:158)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:95)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
        at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
        ... 9 more
Caused by: org.sonar.api.utils.SonarException: java.io.FileNotFoundException: /buildslaves/buildslave_sonar/sonar-fw-next/build/tools/appliance/shell/shell.h (No such file or directory)
        at org.sonar.cxx.checks.FileEncodingCheck.visitFile(FileEncodingCheck.java:57)
        at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:110)
        ... 35 more
Caused by: java.io.FileNotFoundException: /buildslaves/buildslave_sonar/sonar-fw-next/build/tools/appliance/shell/shell.h (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)   
        at com.google.common.io.Files$1.getInput(Files.java:100)
        at com.google.common.io.Files$1.getInput(Files.java:97)
        at com.google.common.io.CharStreams$2.getInput(CharStreams.java:91)
        at com.google.common.io.CharStreams$2.getInput(CharStreams.java:88)
        at com.google.common.io.CharStreams.readLines(CharStreams.java:306)
        at com.google.common.io.Files.readLines(Files.java:580)
        at org.sonar.cxx.checks.FileEncodingCheck.visitFile(FileEncodingCheck.java:55)
        ... 36 more
```

**Comment by jmecosta** [comment]
hi,

i dont think you should run new analysis without having a clean checkout directory, this ensures the data that you see in server is accurate. its best to use preview or file analysis modes in such cases.

now regarding the error, thats odd, since the plugin has no interaction with source control to know a file was removed. by any chance did you remove the file while the analysis was running. thats the only way that could fail.

can you share you setup also by the way

**Comment by rlucca** [comment]
Hi there,

I'll see if I can reproduce this always. I tried reproduce the issue in a
other server (using sonarqube 4.5.6 LTS and the last version of the plugin)
and the problem is not happening... Maybe it is a problem from sonarqube
core (version 5.1.1)...

More info later on.

**Comment by rlucca** [comment]
I used a new version of sonar-scanner and the issues is resolved. :)

Thanks by your time.
