### ISSUE TITLE
unhandled IllegalStateException in CxxCoverageSensor 

### ISSUE THREAD

**Issue by Bertk** [SonarOpenCommunity/sonar-cxx#832]
A coverage reports refers more lines than existing in the source file and the static code analysis fails (2 files affected out of 876 source files). This is probably a coverage tool issue. The sensor should be enhanced to ignore this wrong data created by a tool error and log a warning instead. 
```
ERROR: Saving cov measure 'coverage_line_hits_data' = 'null' failed
ERROR: Obtained 'coverage_line_hits_data' = '34=1;43=1;55=0;66=0;68=0;80=0;91=0;93=0;103=0;112=0;114=0;128=0;139=0;141=0;153=0;162=0;164=0;177=0;186=0;188=0;201=0;218=0;220=0;231=0;248=0;250=0;262=0;274=0;276=0;288=0;315=0;317=0;328=0;341=0;343=0;355=0;368=0;370=0;382=0;396=0;408=0;410=0;424=0;480=0;487=0;512=0;515=0;531=0;535=0' failed
ERROR: Ctype : 'UT_COVERAGE'     Exception 'Can't create measure for line 531 for file 'xxxxxxx.cpp' with 520 lines'
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 3:41.860s
INFO: Final Memory: 90M/3394M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Can't create measure for line 531 for file 'xxxxxxx.cpp' with 520 lines
        at org.sonar.batch.sensor.coverage.CoverageExclusions.validateMaxLine(CoverageExclusions.java:158)
        at org.sonar.batch.sensor.coverage.CoverageExclusions.validate(CoverageExclusions.java:129)
        at org.sonar.batch.deprecated.DeprecatedSensorContext.saveMeasure(DeprecatedSensorContext.java:204)
        at org.sonar.plugins.cxx.coverage.CxxCoverageSensor.saveMeasures(CxxCoverageSensor.java:174)
        at org.sonar.plugins.cxx.coverage.CxxCoverageSensor.analyse(CxxCoverageSensor.java:99)
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
        at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:102)
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:185)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:120)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:264)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:259)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:249)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.batch.scan.ProjectScanContainer.startComponents(ProjectScanContainer.java:127)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:120)
        at org.sonar.batch.task.ScanTask.execute(ScanTask.java:55)
        at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:120)
        at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:122)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
        at org.sonar.runner.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:67)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.sonar.runner.impl.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:61)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:274)
        at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:165)
        at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:152)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:133)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:82)
        at org.sonarsource.scanner.cli.Main.main(Main.java:66)
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
analyze-VS-Solution.bat end 07.04.2016 - 14:27:17

```

**Comment by jmecosta** [comment]
related with this https://github.com/SonarOpenCommunity/sonar-cxx/pull/757

**Comment by BobSilent** [comment]
If you simple ignore these tool errors, the percent Coverage information will differ from the tool report to sonarqube report.

the failing is also valid for csharp plugin, it will also fail for wrong information

try to fix in Coverage Tool

**Comment by jmecosta** [comment]
Our setup allows these issues for example for global coverage that we gather once a week. And during a week the source and the coverage information are likely to differ

My pull request introduces flag to allow this to happen being to default to fail since I agree the results in sonar should match the coverage tool and unit test are and should always match

**Comment by guwirth** [comment]
Handled by #758
