### ISSUE TITLE
RFF: SonarQube v5.6 and C++ Community Plugin v0.9.6

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#882]
**Issue to track remaining open issues**

* SQ 5.6 is available
* SQ 5.6 RC2 API is available but no other plugin is using it yet. They are all still on 4.5.x (see POM files of Java, Javascript and CSharp). Don't know when they are planning to upgrade?
* We are using 5.6 SQ and API now and all deprecated APIs seems still to work? Build works, Unit Tests work, Integration Tests work.
* Know issues: #878, #879

**Download v0.9.6:** https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts

**Comment by ShogunWeb** [comment]
tested the download on my SQ5.6, but it fails during execution with error.
I have the same problem when I compile from the source...

Caused by: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.copyOf(Ljava/util/Collection;)Lcom/google/common/collect/ImmutableList;
at com.sonar.sslr.api.Token.<init>(Token.java:58)
	at com.sonar.sslr.api.Token.<init>(Token.java:36)
	at com.sonar.sslr.api.Token$Builder.build(Token.java:274)
	at org.sonar.cxx.preprocessor.CxxPreprocessor.registerMacros(CxxPreprocessor.java:229)
	at org.sonar.cxx.preprocessor.CxxPreprocessor.<init>(CxxPreprocessor.java:267)
	at org.sonar.cxx.preprocessor.CxxPreprocessor.<init>(CxxPreprocessor.java:216)
	at org.sonar.cxx.parser.CxxParser.create(CxxParser.java:66)
	at org.sonar.cxx.CxxAstScanner.create(CxxAstScanner.java:90)
	at org.sonar.plugins.cxx.squid.CxxSquidSensor.analyse(CxxSquidSensor.java:129)
	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
....

**Comment by guwirth** [comment]
@ShogunWeb thanks for your feedback.

Out integration tests are all running so I wondering what's different in your case?

> but it fails during execution with error.

* What are you exactly meaning with this point?
 * error during server start-up?
 * or error during analysis?
* Which features are you using?
 * During which analysis phase do you get the error (need more information from your log file)?
 * Which sensor is failing?
* ...

**Comment by ShogunWeb** [comment]
Sorry for the lack of information on my first post, and thank you for your questions to help me more specific !

That's an error during an analysis using sonar-scanner 2.6.1.

It seems to be CxxSquidSensor

Here is a longer part of the log:

INFO: -------------  Scan metafor
INFO: Language is forced to c++
INFO: Load server rules
INFO: Load server rules (done) | time=125ms
INFO: Base dir: /code_repository/metafor
INFO: Working dir: /code_repository/metafor/.sonar
INFO: Source paths: src
INFO: Source encoding: UTF-8, default locale: fr_BE
INFO: Index files
WARN: Invalid character encountered in file /code_repository/metafor/src/oo_meta/mtShapeFunctions/TetraQuadShapeFunction.cpp at line 179 for encoding UTF-8. Please fix file content or configure the encoding to be used using property 'sonar.sourceEncoding'.
INFO: 3165 files indexed
INFO: Quality profile for c++: Sonar way
INFO: JaCoCoSensor: JaCoCo report not found : /code_repository/metafor/target/jacoco.exec
INFO: JaCoCoItSensor: JaCoCo IT report not found: /code_repository/metafor/target/jacoco-it.exec
INFO: Sensor Lines Sensor
INFO: Sensor Lines Sensor (done) | time=111ms
INFO: Sensor CxxSquidSensor
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.copyOf(Ljava/util/Collection;)Lcom/google/common/collect/ImmutableList;
	at com.sonar.sslr.api.Token.<init>(Token.java:58)
	at com.sonar.sslr.api.Token.<init>(Token.java:36)
	at com.sonar.sslr.api.Token$Builder.build(Token.java:274)
	at org.sonar.cxx.preprocessor.CxxPreprocessor.registerMacros(CxxPreprocessor.java:229)
	at org.sonar.cxx.preprocessor.CxxPreprocessor.<init>(CxxPreprocessor.java:267)
	at org.sonar.cxx.preprocessor.CxxPreprocessor.<init>(CxxPreprocessor.java:216)
	at org.sonar.cxx.parser.CxxParser.create(CxxParser.java:66)
	at org.sonar.cxx.CxxAstScanner.create(CxxAstScanner.java:90)
	at org.sonar.plugins.cxx.squid.CxxSquidSensor.analyse(CxxSquidSensor.java:129)
	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
	at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)


Is that enough information to better identify where the problem comes from ?  
I don't get errors when I run sonar on projects with other languages (e.g. java). And the error mentions sonar.cxx, that's  why I suppose there's a problem linked to the sonar-cxx plugin...

Don't hesitate to ask if you need another info.

**Comment by guwirth** [comment]
@ShogunWeb looking to last cxx position it is:
```
at org.sonar.cxx.preprocessor.CxxPreprocessor.registerMacros(CxxPreprocessor.java:229)
```
https://github.com/SonarOpenCommunity/sonar-cxx/blob/42f0627242c616f3e6a75765b31664c2b1fea830/cxx-squid/src/main/java/org/sonar/cxx/preprocessor/CxxPreprocessor.java#L229

`registerMacros` is called from two positions:
* this is in ctor and called for all projects: https://github.com/SonarOpenCommunity/sonar-cxx/blob/42f0627242c616f3e6a75765b31664c2b1fea830/cxx-squid/src/main/java/org/sonar/cxx/preprocessor/CxxPreprocessor.java#L267
* this only for c files (sonar.cxx.cFilesPatterns): https://github.com/SonarOpenCommunity/sonar-cxx/blob/42f0627242c616f3e6a75765b31664c2b1fea830/cxx-squid/src/main/java/org/sonar/cxx/preprocessor/CxxPreprocessor.java#L317

Seems like it is crashing at the first location. But still don't understand what is different because this line is called in all our integration tests?

@all: someone else problems with SQ 5.6 and 0.9.6?

**Comment by jmecosta** [comment]
@ShogunWeb are you use latest sonar-scanner, or some custom plugin installed? we are using 5.6 for a couple of weeks in production without observing this behaviour

**Comment by guwirth** [comment]
I did also some **tests** on a local machine (Win7 64bit) and compared results:
* SQ 5.1.2 / cxx 0.9.5 / MySql database
* SQ 5.6 / cxx 0.9.6 / MySql database

**used sensors:**
* sonar.cxx.cppcheck.reportPath=reports/cppcheck.xml
* sonar.cxx.other.reportPath=reports/cxx-*.xml
* sonar.cxx.coverage.reportPath=reports/coverage-*.xml
* sonar.cxx.xunit.reportPath=reports/*.test.boostd.exe.log.xml
* sonar.cxx.xunit.provideDetails=false
* sonar.cxx.xunit.xsltURL=boosttest-1.x-to-junit-1.0.xsl

**results:**
* no issues and results are the same
* SQALE values are no more supported for "other"
* new SonarQube quality model not supported for "other": http://www.sonarqube.org/bugs-and-vulnerabilities-are-1st-class-citizens-in-sonarqube-quality-model-along-with-code-smells/

**Comment by guwirth** [comment]
@jmecosta which sensors are you using?

**Comment by guwirth** [comment]
@Bertk do you also using 5.6 already?

**Comment by guwirth** [comment]
@all proposal: if no big issues with 0.9.6 would let version as is and release it. SQ 5.6 API compatibility is a bigger effort and could be done later one. Looking to Java, JavaScript, CSharp plugins they are started removing the deprecated APIs also **after** release of SQ 5.6.

What are you thinking?

**Comment by jmecosta** [comment]
Looks good, I would only clarify the other sale model and release

**Comment by Bertk** [comment]
I use SQ 5.6 only on a test system and did not identify issues with the C++ Community plug-in.

Typically I use:
- MSVC compiler warnings
- CppCheck
- Vera++
- RATS
- PC-lint

**Comment by guwirth** [comment]
@all will prepare release notes and release current version as is without further release candidates.

**Comment by zeprone** [comment]
Hi,

I have the same issue
SQ 5.6
Scanner 2.6.1
java 1.8.0_66
redhat6

**Comment by fluidjeel** [comment]
Hi,

I have the same issue as well. Please re-open or let us know a solution.

SQ 5.6
Sonar-runner - 2.4
java 1.8.0_66
Ubuntu - 14.04

**Comment by guwirth** [comment]
@fluidjeel & @zeprone which version  of the cxx plugin you are using?

**Comment by fluidjeel** [comment]
@guwirth I was using sonar-cxx 0.9.6. Now I have upgraded to sonar-cxx 0.9.7-SNAPSHOT provided in #898 and the issue has disappeared

**Comment by zeprone** [comment]
Hi, sorry for the delay, same than @fluidjeel for both part.

**Comment by notlistening** [comment]
Same issue here with:
SQ: 5.6 LTS
sonar-cxx: 0.96 
Java: 8 release 11

Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.copyOf(Ljava/util/Collection;)Lcom/google/common/collect/ImmutableList;
	at com.sonar.sslr.api.Token.<init>(Token.java:58)
	at com.sonar.sslr.api.Token.<init>(Token.java:36)
	at com.sonar.sslr.api.Token$Builder.build(Token.java:274)
	at org.sonar.cxx.preprocessor.CxxPreprocessor.registerMacros(CxxPreprocessor.java:229)
	at org.sonar.cxx.preprocessor.CxxPreprocessor.<init>(CxxPreprocessor.java:267)
	at org.sonar.cxx.preprocessor.CxxPreprocessor.<init>(CxxPreprocessor.java:216)
	at org.sonar.cxx.parser.CxxParser.create(CxxParser.java:66)
	at org.sonar.cxx.CxxAstScanner.create(CxxAstScanner.java:90)
	at org.sonar.plugins.cxx.squid.CxxSquidSensor.analyse(CxxSquidSensor.java:129)
	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
	at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
