### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by socooly** [SonarOpenCommunity/sonar-cxx#929]
When I build the c++ project, encounted an error and can not continue, the error message like below:

Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.copyOf(Ljava/util/Collection;)Lcom/google/common/collect/ImmutableList;
	at com.sonar.sslr.api.Token.<init>(Token.java:58)
	at com.sonar.sslr.api.Token.<init>(Token.java:36)
	at com.sonar.sslr.api.Token$Builder.build(Token.java:274)
	at org.sonar.cxx.preprocessor.CxxPreprocessor.registerMacros(CxxPreprocessor.java:229)
	at org.sonar.cxx.preprocessor.CxxPreprocessor.<init>(CxxPreprocessor.java:267)
	at org.sonar.cxx.preprocessor.CxxPreprocessor.<init>(CxxPreprocessor.java:216)
	at org.sonar.cxx.parser.CxxParser.create(CxxParser.java:66)
	at org.sonar.cxx.CxxAstScanner.create(CxxAstScanner.java:90)
	at org.sonar.plugins.cxx.squid.CxxSquidSensor.analyse(CxxSquidSensor.java:129)
	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
	at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
	at org.sonar.runner.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonar.runner.impl.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:61)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:274)
	at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:165)
	at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:152)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:133)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:82)
	at org.sonarsource.scanner.cli.Main.main(Main.java:66)

**Comment by jmecosta** [comment]
see #898 for a workaround
