### ISSUE TITLE
Sonar 6.0 update database migration fails with NoSuchMethodError

### ISSUE THREAD

**Issue by ercpe** [SonarOpenCommunity/sonar-cxx#956]
The database migration in the update process to Sonar 6.0 fails because of the cxx plugin:

    java.lang.NoSuchMethodError: org.sonar.api.platform.ServerFileSystem.getExtensions(Ljava/lang/String;[Ljava/lang/String;)Ljava/util/List;
            at org.sonar.plugins.cxx.utils.CxxAbstractRuleRepository.define(CxxAbstractRuleRepository.java:68) ~[na:na]
            at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoader.java:54) ~[sonar-server-6.0.jar:na]
            at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:97) ~[sonar-server-6.0.jar:na]
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
            at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
            at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110) ~[picocontainer-2.15.jar:na]
            at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89) ~[picocontainer-2.15.jar:na]
            at org.sonar.core.platform.ComponentContainer$1.start(ComponentContainer.java:320) ~[sonar-core-6.0.jar:na]
            at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84) ~[picocontainer-2.15.jar:na]
            at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169) ~[picocontainer-2.15.jar:na]
            at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132) ~[picocontainer-2.15.jar:na]
            at org.picocontainer.behaviors.Stored.start(Stored.java:110) ~[picocontainer-2.15.jar:na]
            at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016) ~[picocontainer-2.15.jar:na]
            at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009) ~[picocontainer-2.15.jar:na]
            at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767) ~[picocontainer-2.15.jar:na]
            at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:141) ~[sonar-core-6.0.jar:na]
            at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:84) ~[sonar-server-6.0.jar:na]
            at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:45) ~[sonar-server-6.0.jar:na]
            at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:80) ~[sonar-server-6.0.jar:na]
            at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:44) ~[sonar-server-6.0.jar:na]
            at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:77) ~[sonar-server-6.0.jar:na]
            at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:201) ~[sonar-server-6.0.jar:na]
            at org.sonar.server.platform.Platform.doStart(Platform.java:114) ~[sonar-server-6.0.jar:na]
            at org.sonar.server.platform.Platform.doStart(Platform.java:99) ~[sonar-server-6.0.jar:na]
            at org.sonar.server.db.migrations.PlatformDatabaseMigration.doRestartContainer(PlatformDatabaseMigration.java:133) ~[sonar-server-6.0.jar:na]
            at org.sonar.server.db.migrations.PlatformDatabaseMigration.doDatabaseMigration(PlatformDatabaseMigration.java:109) ~[sonar-server-6.0.jar:na]
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
            at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]

**Comment by guwirth** [comment]
@ercpe same as #926

**Comment by ercpe** [comment]
Yes, it's a duplicate of #926
