### ISSUE TITLE
How to handle a file deleted from the repository?

### ISSUE THREAD

**Issue by rlucca** [SonarOpenCommunity/sonar-cxx#979]
Hi there,

Since some of the developers deleted a file from the repository, I'm getting a exception from sonar-runner. What is the correct way to handler that? I see in the log a warning "Missing blame information for the following files" and after the files list I get a "This may lead to missing/broken features in SonarQube. Is the files mentioned here to blame?

```
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Unable to save file sources
    at org.sonar.batch.index.SourcePersister.persist(SourcePersister.java:84)
    at org.sonar.batch.phases.DatabaseModePhaseExecutor.executePersisters(DatabaseModePhaseExecutor.java:165)
    at org.sonar.batch.phases.DatabaseModePhaseExecutor.execute(DatabaseModePhaseExecutor.java:133)
    at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:264)
    at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
    at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
    at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:235)
    at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:230)
    at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:220)
    at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
    at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
    at org.sonar.batch.scan.ScanTask.scan(ScanTask.java:57)
    at org.sonar.batch.scan.ScanTask.execute(ScanTask.java:45)
    at org.sonar.batch.bootstrap.TaskContainer.doAfterStart(TaskContainer.java:135)
    at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
    at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
    at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:158)
    at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:95)
    at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
    at org.sonar.runner.batch.BatchIsolatedLauncher.executeOldVersion(BatchIsolatedLauncher.java:86)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.sonar.runner.impl.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:61)
    at com.sun.proxy.$Proxy0.executeOldVersion(Unknown Source)
    at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:283)
    at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:165)
    at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:152)
    at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:118)
    at org.sonarsource.scanner.cli.Main.execute(Main.java:80)
    at org.sonarsource.scanner.cli.Main.main(Main.java:66)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(ArrayList.java:400)
    at java.util.ArrayList.get(ArrayList.java:413)
    at com.google.protobuf.RepeatedFieldBuilder.getBuilder(RepeatedFieldBuilder.java:245)
    at org.sonar.server.source.db.FileSourceDb$Data$Builder.getLinesBuilder(FileSourceDb.java:2911)
    at org.sonar.batch.index.SourceDataFactory.applyLineMeasure(SourceDataFactory.java:183)
    at org.sonar.batch.index.SourceDataFactory.applyLineMeasures(SourceDataFactory.java:99)
    at org.sonar.batch.index.SourceDataFactory.consolidateData(SourceDataFactory.java:76)
    at org.sonar.batch.index.SourcePersister.computeData(SourcePersister.java:152)
    at org.sonar.batch.index.SourcePersister.persist(SourcePersister.java:93)
    at org.sonar.batch.index.SourcePersister.persist(SourcePersister.java:81)
    ... 31 more
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
```

**Comment by guwirth** [comment]
Hi @rlucca which versions are you using?
* SonarQube?
* Cxx plugin?
* which SCM are you using (svn, git, ...)?

> I see in the log a warning "Missing blame information for the following files" 

As far as I know this message is not a cxx plugin message?
It is from the SQ core or one of the plugins?

**Comment by rlucca** [comment]
SQ - Version 5.1.1
CxxPlugin - 0.9.4-SNAPSHOT
SCM - git version 2.0.1 (sonar-runner) e git version 1.7.9.5 (server side)

I'm not sure. How I can identify if it is a log from the plugin or from the SQ core?

**Comment by guwirth** [comment]
> I'm not sure. How I can identify if it is a log from the plugin or from the SQ core?

@rlucca easiest is always to search for the error message in the source code. We have no such error message and do also not handle SCM issues. Would recommend you to ask in the official SonarQube group. I fear they will answer you to update to at least SQ 5.6...

**Comment by guwirth** [comment]
@rlucca  I close this, please reopen if still an issue.
