### ISSUE TITLE
CxxHighlighter is requesting multiple highlights for overlapping section/lines

### ISSUE THREAD

**Issue by CCob** [SonarOpenCommunity/sonar-cxx#996]
When analyzing files within my C++ project, multiple highlighters have been requested for the same section of text within the source.  It seems SonarQube will check for overlapping highlight ranges and throw errors when it finds overlapping highlight sections.

Here is the line that SonarQube is complaining about

```
        qWarning() << "Failed to open file " << sourceFilename << " for reading";
```

And here is the exception

```
org.sonar.squidbridge.api.AnalysisException: Unable to analyze file: File.cpp
	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:131)
	at org.sonar.plugins.cxx.squid.CxxSquidSensor.execute(CxxSquidSensor.java:128)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:247)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:242)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:232)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:118)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.IllegalStateException: Cannot register highlighting rule for characters at Range[from [line=163, lineOffset=38] to [line=163, lineOffset=46]] as it overlaps at least one existing rule
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.checkOverlappingBoudaries(DefaultHighlighting.java:59)
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.doSave(DefaultHighlighting.java:122)
	at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:43)
	at org.sonar.plugins.cxx.highlighter.CxxHighlighter.leaveFile(CxxHighlighter.java:118)
	at com.sonar.sslr.impl.ast.AstWalker.walkAndVisit(AstWalker.java:71)
	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:110)
	... 31 more
```

**Comment by guwirth** [comment]
Hi @CCob, what exactly is in line=163, lineOffset=38 to lineOffset=46?

**Comment by CCob** [comment]
It's at the top of the ticket before the exception trace.

**Comment by guwirth** [comment]
What is lineOffset=38 to lineOffset=46? Which token / string?

**Comment by CCob** [comment]
@guwirth, 38 - 46 is the following string

```
 file " 
```

**Comment by tomikais** [comment]
Hi,
I have the the same issue:
org.sonar.squidbridge.api.AnalysisException: Unable to analyze file: 
	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:131)
	at org.sonar.plugins.cxx.squid.CxxSquidSensor.execute(CxxSquidSensor.java:141)
	at org.sonar.batch.sensor.SensorWrapper.analyse(SensorWrapper.java:57)
	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
	at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.IllegalStateException: Cannot register highlighting rule for characters at Range[from [line=73, lineOffset=90] to [line=73, lineOffset=96]] as it overlaps at least one existing rule
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.checkOverlappingBoudaries(DefaultHighlighting.java:59)
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.doSave(DefaultHighlighting.java:124)
	at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:43)
	at org.sonar.plugins.cxx.highlighter.CxxHighlighter.leaveFile(CxxHighlighter.java:118)
	at com.sonar.sslr.impl.ast.AstWalker.walkAndVisit(AstWalker.java:71)
	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:110)
	... 31 more

Regards, Thomas

**Comment by CCob** [comment]
Can you paste what is at line 73?

**Comment by guwirth** [comment]
Hi @CCob and @tomikais, problem was last time not reproducible. Can you provide a simple file were error occurs please. Thx.

**Comment by CCob** [comment]
@tomikais is your project at Qt project?

**Comment by tomikais** [comment]
Hi @CCob, Hi @guwirth,

here is line 73: `globalPrefs.unserialize(false /*user*/, QStringLiteral("all") /*appType*/, true /*admin*/);`
Yes, it's a Qt project! That's very strange because that line is also in our current branch and there isn't any crash. Is it possible that the log reported the wrong line?!

Regards, Thomas

**Comment by CCob** [comment]
Have you removed indentation?  lineOffset 90-96 does not exist.  It is only 91 characters long

**Comment by tomikais** [comment]
`    globalPrefs.unserialize(false /*user*/, QStringLiteral("all") /*appType*/, true /*admin*/);`

Sorry I'd removed the 4 spaces in front of the line.

**Comment by CCob** [comment]
OK, so that would make the requested highlighter range ```in*/);```  Which is essentially the last 6 characters of that line

**Comment by tomikais** [comment]
I don't think that line cause the issue because this line already exist for a long time and we don't have this issue in our branch build which also contains this line. What do you think @guwirth ?

**Comment by guwirth** [comment]
>  Is it possible that the log reported the wrong line?

@tomikais especially in Qt there is a lot of macro magic. Maybe that's the reason for showing a diferent line?

Saw at least this (https://woboq.com/blog/qstringliteral.html):

```C++
// wchar_t is 2 bytes  (condition a bit simplified)
#define QT_UNICODE_LITERAL_II(str) L##str
typedef wchar_t qunicodechar;
# define QT_UNICODE_LITERAL(str) QT_UNICODE_LITERAL_II(str)

template <int N>
struct QStaticStringData
{
    QStringData str;
    qunicodechar data[N + 1];
};

#define QStringLiteral(str) \
    ([]() -> QString { \
        enum { Size = sizeof(QT_UNICODE_LITERAL(str))/2 - 1 }; \
        static const QStaticStringData<Size> qstring_literal = { \
            Q_STATIC_STRING_DATA_HEADER_INITIALIZER(Size), \
            QT_UNICODE_LITERAL(str) }; \
        QStringDataPtr holder = { &qstring_literal.str }; \
        const QString s(holder); \
        return s; \
    }()) \
 
globalPrefs.unserialize(false /*user*/, QStringLiteral("all") /*appType*/, true /*admin*/);
```
That's the reason why I'm asking for a complete file to reproduce the problem. You also have to copy the macros into the file. Maybe you can precompile the file and send us the result?

**Comment by tomikais** [comment]
@guwirth Thank you for getting in touch. I understand that you are need the code but I can't send you that code. Is it possible that the CXX plugin can send the string to log, which cause this issue, instead of showing the numbers?

**Comment by guwirth** [comment]
@tomikais 

> Is it possible that the CXX plugin can send the string to log, which cause this issue, instead of showing the numbers?

adding a more meaningful error message makes sense

> I understand that you are need the code but I can't send you that code.

We don't need your original code, only an isolated sample snippet to reproduce the issue. For the code above this is 
```C++
#define QT_UNICODE_LITERAL_II(str) ???
#define QT_UNICODE_LITERAL(str) ???
#define QT_UNICODE_LITERAL ???
#define Q_STATIC_STRING_DATA_HEADER_INITIALIZER ???
#define QT_UNICODE_LITERAL ???
#define QStringLiteral(str) ???
QStringData ???
QStaticStringData ???
QStringDataPtr ???
QString ???

globalPrefs.unserialize(false /*user*/, QStringLiteral("all") /*appType*/, true /*admin*/);
```
As already mentioned easiest is to run only preprocessor and send us the result for the code line after macro handling.

**Comment by mgresko** [comment]
I am able to reproduce this error

```
169 static int io_close (lua_State *L) {
170   if (lua_isnone(L, 1))  /* no argument? */
171     lua_getfield(L, LUA_REGISTRYINDEX, IO_OUTPUT);  /* use standard output */
172   tofile(L);  /* make sure argument is an open stream */
173   return aux_close(L);
174 }
```

Caused by: java.lang.IllegalStateException: Cannot register highlighting rule for characters at Range[from [line=171, lineOffset=52] to [line=171, lineOffset=77]] as it overlaps at least one existing rule

Line 171, offset 52 is the character before the start of the comment.

**Comment by guwirth** [comment]
@mgresko thanks for providing this. But also with this code snippet it's not reproducable in an unit test. Can you provide all macros please:
```C++
#define LUA_REGISTRYINDEX ???
#define IO_OUTPUT ???
```
Any other macros? lua_getfield?

**Comment by tomikais** [comment]
@guwirth I used `/P` (preprocess to a file) and `/C` (keep comments) to preprocess my example to a file. Here is the result of that line:
`    globalPrefs.unserialize(false /*user*/, ([]() -> QString { enum { Size = sizeof(u"" "all")/2 - 1 }; static const QStaticStringData<Size> qstring_literal = { { { { (-1) } }, Size, 0, 0, sizeof(QStringData) }, u"" "all" }; QStringDataPtr holder = { qstring_literal.data_ptr() }; const QString qstring_literal_temp(holder); return qstring_literal_temp; }()) /*appType*/, true /*admin*/);` 
original line:
`    globalPrefs.unserialize(false /*user*/, QStringLiteral("all") /*appType*/, true /*admin*/);`
fyi: 4 spaces in front of the line.

Did you extend your log mechanism?

**Comment by CCob** [comment]
@tomikais does the preprocessed file still have that line at 73?

**Comment by tomikais** [comment]
Yes, with `/C` (keep comments): `** GNU Lesser General Public License Usage` 
Part of the QAbstractButton class comment. I don't think this cause the issue^^ :-)

**Comment by mgresko** [comment]
@guwirth I believe this is all the relevant code

```
#define LUA_REGISTRYINDEX	LUAI_FIRSTPSEUDOIDX
#define LUAI_FIRSTPSEUDOIDX	(-LUAI_MAXSTACK - 1000)
#define LUAI_MAXSTACK		1000000
#define IO_OUTPUT	(IO_PREFIX "output")
#define IO_PREFIX	"_IO_"
#define LUA_API		extern
```
```
LUA_API void lua_getfield (lua_State *L, int idx, const char *k) {
  StkId t;
  lua_lock(L);
  t = index2addr(L, idx);
  api_checkvalidindex(L, t);
  setsvalue2s(L, L->top, luaS_new(L, k));
  api_incr_top(L);
  luaV_gettable(L, t, L->top - 1, L->top - 1);
  lua_unlock(L);
}
```

**Comment by mgresko** [comment]
@guwirth running against lua in the lua-5.2 branch will reproduce the error

https://github.com/LuaDist/lua/tree/lua-5.2

**Comment by guwirth** [comment]
Reproducible with:
```C++
const wchar_t  *t8 = /*comment1*/ u"" /*comment2*/ "hello world" /*comment3*/; // issue #996
```
String concatenation and comment is inside of merged string.

**Comment by CCob** [comment]
Nice work.  I'll give this a try

**Comment by tomikais** [comment]
Does the fix work?

**Comment by CCob** [comment]
Don't know yet, haven't had a chance to test

**Comment by CCob** [comment]
@guwirth Fix confirmed, I no longer get the exception on my code base.  Thanks

**Comment by tomikais** [comment]
yeah, bug fix is working fine. Thank you!
